/**
 * wasm2js browser profile of `@solvapay/server-wasm` — public-safe pure logic.
 *
 * No webhook / transport-client / MCP / secret-adjacent exports (§7.8).
 * Importing this module installs the converted core synchronously.
 */

export const SOLVAPAY_BROWSER_JS_CORE: 'solvapay-browser-js-core'

export {
  wasmVersion,
  wasmBuildInfo,
  validateBusinessDetails,
  deriveTaxIdType,
  resolveTaxBehavior,
  getTaxIdExample,
  getTaxIdFieldLabel,
  getTaxIdHelperText,
  getBusinessCountryOptions,
  resolveBuyerCountry,
  getCustomerAddressFieldErrors,
  isCustomerAddressComplete,
  isPostalCodeRequired,
  isStateRequired,
  getStateFieldLabel,
  getPostalCodeFieldLabel,
  getPostalCodePlaceholder,
  POSTAL_CODE_REQUIRED_COUNTRIES,
  STATE_REQUIRED_COUNTRIES,
  creditsToDisplayMinorUnits,
  isZeroDecimalCurrency,
  isUnlimitedRemaining,
  minorUnitsPerMajor,
  resolveSellerIdentityDisplay,
  getSellerTaxIdentifierDisplayLabel,
  SELLER_TAX_IDENTIFIER_DISPLAY_LABEL_BY_TYPE,
  charges,
  headlineCharges,
  perUnitCharge,
  billingCycle,
  trialDays,
  includedUnits,
  countsUsage,
  meterName,
  usageRate,
  peggedCreditsPerUnit,
  creditsPerUnitFromBalance,
  planPricingShape,
  resolveAccountState,
  deriveDefaultView,
  resolvePlanShape,
  planConsequence,
  deriveActiveProducts,
  historyRows,
  formatCompactCredits,
  resolveDisplayMode,
  formatPrice,
  formatSubtotalLabel,
  formatVatSummaryLabel,
  resolveTaxTreatmentNote,
  shouldShowTaxRow,
  toMajorUnits,
  REVERSE_CHARGE_NOTE,
  TAX_NOT_COLLECTED_NOTE,
} from '../pkg/browser-js/solvapay_wasm'
