// @generated by dto-gen (--rs-conformance-out) — do not edit. Regenerate with: pnpm gen

#![allow(dead_code)]

/// Host-adapter fn names shared with other language harnesses.
pub const HOST_FNS: &[&str] = &[
    "withRetry",
    "pollBalanceUntilIncreased",
    "TOPUP_BALANCE_POLL_DELAYS_MS",
    "BALANCE_RECONCILE_DELAYS_MS",
    "resolveAuthenticatedUser",
    "driveGate",
    "drivePayable",
];
