//! Golden test: emitted `__init__.pyi` must match the committed stub once the
//! `@generated` header is stripped (step 42T).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;
use std::path::{Path, PathBuf};

use dto_gen::emit_pyi_py;
use dto_gen::ir::{Ir, IrErrorTemplates};
use dto_gen::lower_catalog::lower_catalog;
use dto_gen::manifest::Manifest;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("repo root")
        .to_path_buf()
}

fn lower_ir() -> Ir {
    let manifest_path = repo_root().join("contract/manifest/sdk-contract.yaml");
    let raw = fs::read_to_string(&manifest_path).expect("read manifest");
    let manifest: Manifest = serde_norway::from_str(&raw).expect("parse manifest");
    let mut ir = Ir {
        types: Default::default(),
        overlay_helpers: Default::default(),
        overlays: Default::default(),
        routes: vec![],
        error_templates: IrErrorTemplates::default(),
        entry_points: Default::default(),
        binding_symbols: Default::default(),
    };
    lower_catalog(&mut ir, &manifest).expect("lower catalog");
    ir
}

fn strip_generated_header(src: &str) -> String {
    let trimmed = src.trim_start();
    if let Some(rest) = trimmed.strip_prefix("# @generated") {
        let after_first_line = rest.split_once('\n').map(|(_, tail)| tail).unwrap_or("");
        after_first_line.trim_start().to_string()
    } else {
        trimmed.to_string()
    }
}

fn assert_matches(emitted: &str, committed_path: &Path, tag: &str) {
    let committed = fs::read_to_string(committed_path)
        .unwrap_or_else(|e| panic!("read committed {}: {e}", committed_path.display()));
    let got = strip_generated_header(emitted);
    let want = strip_generated_header(&committed);
    if got != want {
        let g: Vec<&str> = got.lines().collect();
        let w: Vec<&str> = want.lines().collect();
        let mut first = 0;
        while first < g.len() && first < w.len() && g[first] == w[first] {
            first += 1;
        }
        let ctx = |v: &[&str]| {
            let start = first.saturating_sub(2);
            let end = (first + 4).min(v.len());
            v[start..end].join("\n")
        };
        panic!(
            "emitted {tag} does not match committed at line ~{first}\n--- emitted ---\n{}\n--- committed ---\n{}",
            ctx(&g),
            ctx(&w)
        );
    }
}

#[test]
fn pyi_py_matches_committed() {
    let ir = lower_ir();
    let emitted = emit_pyi_py(&ir).expect("emit __init__.pyi");
    assert!(
        emitted.starts_with("# @generated by dto-gen — do not edit."),
        "missing @generated header"
    );
    assert!(
        !emitted.contains("Any") && !emitted.contains("__getattr__"),
        "strict stub must not leak Any / __getattr__"
    );
    assert_matches(
        &emitted,
        &repo_root().join("rust/bindings/python/python/solvapay/__init__.pyi"),
        "__init__.pyi",
    );
}
