//! Golden tests for generated Rust facade client + blocking twins.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use dto_gen::ir::{Ir, IrErrorTemplates};
use dto_gen::{emit_client_rs, lower_bindings, lower_catalog, Manifest};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("repo root")
        .to_path_buf()
}

fn ir() -> Ir {
    let raw =
        fs::read_to_string(root().join("contract/manifest/sdk-contract.yaml")).expect("manifest");
    let manifest: Manifest = serde_norway::from_str(&raw).expect("parse manifest");
    let mut ir = Ir {
        types: Default::default(),
        overlay_helpers: Default::default(),
        overlays: Default::default(),
        routes: vec![],
        error_templates: IrErrorTemplates::default(),
        entry_points: Default::default(),
        binding_symbols: Default::default(),
    };
    lower_catalog(&mut ir, &manifest).expect("lower catalog");
    lower_bindings(&mut ir, &manifest).expect("lower bindings");
    ir
}

fn rustfmt(source: &str, tag: &str) -> String {
    let mut path = std::env::temp_dir();
    path.push(format!(
        "dto_gen_rs_client_{}_{}.rs",
        std::process::id(),
        tag
    ));
    {
        let mut f = fs::File::create(&path).expect("create temp");
        f.write_all(source.as_bytes()).expect("write temp");
    }
    let status = Command::new("rustfmt")
        .arg("--edition=2021")
        .arg(&path)
        .status()
        .expect("spawn rustfmt");
    assert!(status.success(), "rustfmt failed for {tag}");
    let out = fs::read_to_string(&path).expect("read temp");
    let _ = fs::remove_file(&path);
    out
}

#[test]
fn rust_client_and_blocking_match_committed() {
    let ir = ir();
    let emitted = emit_client_rs(&ir).expect("emit Rust client");
    assert_eq!(
        rustfmt(&emitted.client_generated_rs, "client"),
        fs::read_to_string(root().join("rust/crates/solvapay/src/client_generated.rs"))
            .expect("client_generated")
    );
    assert_eq!(
        rustfmt(&emitted.blocking_generated_rs, "blocking"),
        fs::read_to_string(root().join("rust/crates/solvapay/src/blocking_generated.rs"))
            .expect("blocking_generated")
    );
    assert_eq!(
        emitted.client_generated_rs.matches("pub async fn ").count(),
        36
    );
    assert_eq!(emitted.blocking_generated_rs.matches("pub fn ").count(), 36);
    assert!(emitted
        .client_generated_rs
        .contains("@generated by dto-gen — do not edit"));
    assert!(emitted.client_generated_rs.contains("/// # Arguments"));
}
