//! Golden test: fixture-runner registry emitter covers wrap invoke bodies
//! and the committed registration set.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;

use dto_gen::emit_fixture_runner_rs::emit_fixture_runner;
use dto_gen::ir::{Ir, IrBindingArtifact, IrBindingCall, IrErrorTemplates};
use dto_gen::lower_bindings::lower_bindings;
use dto_gen::lower_catalog::lower_catalog;
use dto_gen::manifest::Manifest;

fn paths() -> repo_paths::RepoPaths {
    repo_paths::load().expect("repo-paths")
}

fn lower_ir() -> Ir {
    let manifest_path = paths().contract_input("sdkManifest").expect("sdkManifest");
    let raw = fs::read_to_string(&manifest_path).expect("read manifest");
    let manifest: Manifest = serde_norway::from_str(&raw).expect("parse manifest");
    let mut ir = Ir {
        types: Default::default(),
        overlay_helpers: Default::default(),
        overlays: Default::default(),
        routes: vec![],
        error_templates: IrErrorTemplates::default(),
        entry_points: Default::default(),
        binding_symbols: Default::default(),
    };
    lower_catalog(&mut ir, &manifest).expect("lower catalog");
    lower_bindings(&mut ir, &manifest).expect("lower bindings");
    ir
}

fn committed_register_ids() -> Vec<String> {
    let src = fs::read_to_string(paths().generated_path("fixtureRunner").expect("fixtureRunner"))
        .expect("registry.rs");
    let mut ids = Vec::new();
    let mut rest = src.as_str();
    while let Some(idx) = rest.find("registry.register(") {
        rest = &rest[idx + "registry.register(".len()..];
        let q = rest.find('"').expect("id quote");
        rest = &rest[q + 1..];
        let q2 = rest.find('"').expect("id end");
        ids.push(rest[..q2].to_owned());
        rest = &rest[q2 + 1..];
    }
    ids
}

#[test]
fn fixture_runner_emits_wrap_invoke_bodies_and_committed_ids() {
    let ir = lower_ir();
    let emitted = emit_fixture_runner(&ir).expect("emit fixture-runner");
    assert!(
        emitted.contains("//! @generated by dto-gen"),
        "missing generated header"
    );
    assert!(emitted.contains("pub fn create_default_registry()"));

    let wrap_ids: Vec<_> = ir
        .binding_symbols
        .values()
        .filter(|s| {
            s.artifact != IrBindingArtifact::Client
                && matches!(s.call, IrBindingCall::Wrap { .. })
                && s.id != "verifyWebhook"
        })
        .map(|s| s.id.as_str())
        .collect();
    assert_eq!(wrap_ids.len(), 41, "expected 41 derivable wrap symbols");
    for id in wrap_ids {
        assert!(
            emitted.contains(&format!("registry.register(\n        \"{id}\"")),
            "missing wrap registration {id}"
        );
    }

    let committed = committed_register_ids();
    assert!(
        committed.len() >= 73,
        "expected at least the original 73 registrations, got {}",
        committed.len()
    );
    for id in &committed {
        assert!(
            emitted.contains(&format!("\"{id}\"")),
            "missing committed id {id}"
        );
    }
    assert!(
        emitted.contains("\"resolveFallbackGateLimits\""),
        "free wrap resolveFallbackGateLimits must be registered"
    );
}

#[test]
fn fixture_runner_emit_is_byte_idempotent() {
    let ir = lower_ir();
    let first = emit_fixture_runner(&ir).expect("first");
    let second = emit_fixture_runner(&ir).expect("second");
    assert_eq!(first, second);
}
