//! Golden test for generated Go portable helpers.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod support;

use std::fs;

use dto_gen::emit_helpers_go;

#[test]
fn go_helpers_match_committed() {
    let ir = support::lower_bindings_ir();
    let emitted = emit_helpers_go(&ir).expect("emit helpers_generated.go");
    let committed = fs::read_to_string(
        support::paths()
            .generated_path("goHelpers")
            .expect("goHelpers"),
    )
    .expect("helpers_generated.go");
    assert_eq!(emitted, committed);
    assert!(emitted.contains("// Code generated by dto-gen. DO NOT EDIT."));
    assert!(emitted.contains("func DeriveTaxIdType(ctx context.Context"));
    assert!(emitted.contains("nativecall.CallSync"));
}
