//! Golden tests for generated Rust facade client + blocking twins.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;
use std::io::Write;
use std::process::Command;

use dto_gen::ir::{Ir, IrErrorTemplates};
use dto_gen::{emit_client_rs, lower_catalog, Manifest};

fn paths() -> repo_paths::RepoPaths {
    repo_paths::load().expect("repo-paths")
}

fn ir() -> Ir {
    let raw = fs::read_to_string(paths().contract_input("sdkManifest").expect("sdkManifest"))
        .expect("manifest");
    let manifest: Manifest = serde_norway::from_str(&raw).expect("parse manifest");
    let mut ir = Ir {
        types: Default::default(),
        overlay_helpers: Default::default(),
        overlays: Default::default(),
        routes: vec![],
        error_templates: IrErrorTemplates::default(),
        entry_points: Default::default(),
        binding_symbols: Default::default(),
        core_types: Default::default(),
        core_types_ts: Default::default(),
        core_fns: Default::default(),
        transport_fns: Default::default(),
    };
    lower_catalog(&mut ir, &manifest).expect("lower catalog");
    let residue = dto_gen::load_binding_residue(
        &paths()
            .contract_input("bindingResidue")
            .expect("bindingResidue"),
    )
    .expect("residue");
    dto_gen::lower_all_bindings(
        &mut ir,
        &manifest,
        &paths().contract_input("coreSrc").expect("coreSrc"),
        &residue,
        Some(
            &paths()
                .contract_input("transportSrc")
                .expect("transportSrc"),
        ),
    )
    .expect("lower bindings");
    ir
}

fn rustfmt(source: &str, tag: &str) -> String {
    let mut path = std::env::temp_dir();
    path.push(format!(
        "dto_gen_rs_client_{}_{}.rs",
        std::process::id(),
        tag
    ));
    {
        let mut f = fs::File::create(&path).expect("create temp");
        f.write_all(source.as_bytes()).expect("write temp");
    }
    let status = Command::new("rustfmt")
        .arg("--edition=2021")
        .arg(&path)
        .status()
        .expect("spawn rustfmt");
    assert!(status.success(), "rustfmt failed for {tag}");
    let out = fs::read_to_string(&path).expect("read temp");
    let _ = fs::remove_file(&path);
    out
}

#[test]
fn rust_client_and_blocking_match_committed() {
    let ir = ir();
    let emitted = emit_client_rs(&ir).expect("emit Rust client");
    assert_eq!(
        rustfmt(&emitted.client_generated_rs, "client"),
        fs::read_to_string(paths().generated_path("rsClient").expect("rsClient"))
            .expect("client_generated")
    );
    assert_eq!(
        rustfmt(&emitted.blocking_generated_rs, "blocking"),
        fs::read_to_string(paths().generated_path("rsBlocking").expect("rsBlocking"))
            .expect("blocking_generated")
    );
    assert_eq!(
        emitted.client_generated_rs.matches("pub async fn ").count(),
        36
    );
    assert_eq!(emitted.blocking_generated_rs.matches("pub fn ").count(), 36);
    assert!(emitted
        .client_generated_rs
        .contains("@generated by dto-gen — do not edit"));
    assert!(emitted.client_generated_rs.contains("/// # Arguments"));
}
