// @generated by dto-gen (--boundary-asserts-rs-out) — do not edit. Regenerate with: pnpm gen
const _: fn(Option<&str>, Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::activation::validate_activate_plan_params;
const _: fn(&AuthResolutionInput) -> Result<AuthenticatedUser, HelperErrorResult> =
    solvapay_core::auth_resolution::resolve_authenticated_user;
const _: fn(f64, f64) -> Option<f64> = solvapay_core::balance_poll::evaluate_balance_observation;
const _: fn() -> Value = solvapay_core::business_details::business_country_display_names;
const _: () = assert_boundary::<BusinessCountryOption>();
const _: fn() -> Value = solvapay_core::business_details::country_to_tax_id_type;
const _: fn(&str) -> Option<TaxIdType> = solvapay_core::business_details::derive_tax_id_type;
const _: () = assert_boundary::<BusinessCountryOption>();
const _: fn(&BusinessDetailsInput) -> Value =
    solvapay_core::business_details::get_customer_address_field_errors;
const _: fn(&BusinessDetailsInput) -> bool =
    solvapay_core::business_details::is_customer_address_complete;
const _: fn(&str) -> bool = solvapay_core::business_details::is_postal_code_required;
const _: fn(&str) -> bool = solvapay_core::business_details::is_state_required;
const _: fn(&str) -> bool = solvapay_core::business_details::is_tax_id_type;
const _: () = assert_boundary::<BusinessDetailsInput>();
const _: fn() -> Value = solvapay_core::business_details::tax_id_example_by_country;
const _: fn(&BusinessDetailsInput) -> ValidateBusinessDetailsResult =
    solvapay_core::business_details::validate_business_details;
const _: fn(Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::checkout::validate_checkout_session_params;
const _: fn(&CreditsToDisplayInput) -> Option<i64> =
    solvapay_core::credit_display::credits_to_display_minor_units;
const _: fn(&str) -> bool = solvapay_core::credit_display::is_zero_decimal_currency;
const _: fn(&str) -> u32 = solvapay_core::credit_display::minor_units_per_major;
const _: fn(&str, Option<&str>, Option<&str>, Option<&str>, i64) -> CreateCustomerParams =
    solvapay_core::customer_sync::build_create_customer_params;
const _: fn(&str) -> CreateErrorKind = solvapay_core::customer_sync::classify_create_error;
const _: fn(&str) -> CustomerRefKind = solvapay_core::customer_sync::classify_customer_ref;
const _: fn(&str) -> LookupErrorKind = solvapay_core::customer_sync::classify_lookup_error;
const _: fn(Option<&str>, Option<&str>) -> CoercedCustomerOptions =
    solvapay_core::customer_sync::coerce_customer_options;
const _: fn(&str) -> bool = solvapay_core::customer_sync::is_email_conflict;
const _: fn(Option<&Value>, Option<&Value>) -> Result<EnsureCustomerNextOutput, HelperErrorResult> =
    solvapay_core::ensure_customer::ensure_customer_next;
const _: fn(&str, Option<&Value>) -> CustomerSnapshot =
    solvapay_core::gate_driver::build_customer_snapshot;
const _: fn(Option<&Value>, Option<&Value>) -> Result<GateNextOutput, HelperErrorResult> =
    solvapay_core::gate_driver::gate_next;
const _: fn(Option<&Value>, Option<&Value>) -> Result<GetHistoryNextOutput, HelperErrorResult> =
    solvapay_core::history::get_history_next;
const _: fn(Option<&Value>) -> Result<HistoryRows, HelperErrorResult> =
    solvapay_core::history::history_rows;
const _: fn(Option<&Value>, Option<&Value>) -> Result<InvokePayableNextOutput, HelperErrorResult> =
    solvapay_core::invoke_payable::invoke_payable_next;
const _: fn(&str) -> Option<Value> = solvapay_core::jwt_util::decode_jwt_payload_unverified;
const _: fn(&str, Option<&str>, i64) -> DefaultMcpBearerExpectations =
    solvapay_core::jwt_util::default_mcp_bearer_expectations;
const _: fn(f64) -> bool = solvapay_core::limits::is_unlimited_remaining;
const _: fn(
    Option<&str>,
    Option<&str>,
    Option<&str>,
) -> Result<CheckLimitsParams, HelperErrorResult> =
    solvapay_core::limits::resolve_check_limits_params;
const _: () = assert_boundary::<HelperErrorResult>();
const _: fn(Option<&Value>) -> Option<NarratorPlanShape> =
    solvapay_core::mcp::resolve_narrator_plan_shape;
const _: fn(&str, &Value) -> PromptUserMessage = solvapay_core::mcp::build_prompt_user_message;
const _: fn(Option<&Value>) -> McpDisplayModeState = solvapay_core::mcp::resolve_display_mode;
const _: () = assert_boundary::<ResponseEnvelope>();
const _: fn(&ResponseEnvelope) -> McpPayableToolResult =
    solvapay_core::mcp::build_payable_tool_result;
const _: fn(&str, &PaywallGate) -> McpPaywallToolResult = solvapay_core::mcp::paywall_tool_result;
const _: () = assert_boundary::<HelperErrorResult>();
const _: fn() -> Value = solvapay_core::mcp::mcp_tool_names_json;
const _: fn() -> McpViewMaps = solvapay_core::mcp::mcp_view_maps;
const _: fn(Option<&Value>) -> Result<Value, HelperErrorResult> =
    solvapay_core::mcp::compile_string_field_input_schema_json;
const _: fn(&Value) -> Value = solvapay_core::mcp::ensure_output_schema_object_type;
const _: () = assert_boundary::<HelperErrorResult>();
const _: fn(f64, &str) -> f64 = solvapay_core::money_format::to_major_units;
const _: fn(Option<&str>) -> HelperErrorResult =
    solvapay_core::payment::attach_business_details_validation_error;
const _: fn(&PaymentIntentSource, &str) -> PaymentIntentProjection =
    solvapay_core::payment::project_payment_intent_result;
const _: fn(Option<&str>, Option<&str>) -> TopupProcessOutcome =
    solvapay_core::payment::project_topup_process_outcome;
const _: fn(Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::payment::validate_attach_business_details_params;
const _: fn(Option<&str>, Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::payment::validate_create_payment_intent_params;
const _: fn(Option<&str>, Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::payment::validate_process_payment_intent_params;
const _: fn(Option<f64>, Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::payment::validate_topup_payment_intent_params;
const _: fn(bool, &str, Option<&Value>, Option<&str>) -> PaywallOutcome =
    solvapay_core::paywall_decision::decide_paywall_outcome;
const _: fn(f64) -> CachedLimitsEvaluation =
    solvapay_core::paywall_decision::evaluate_cached_limits;
const _: fn(bool, f64, f64) -> FreshLimitsEvaluation =
    solvapay_core::paywall_decision::evaluate_claimed_limits;
const _: fn(bool, f64) -> FreshLimitsEvaluation =
    solvapay_core::paywall_decision::evaluate_fresh_limits;
const _: fn(&Value, f64) -> Value = solvapay_core::paywall_decision::overlay_claimed_limits;
const _: () = assert_boundary::<SdkError>();
const _: fn(Option<&str>) -> PaywallGateLimits =
    solvapay_core::paywall_decision::resolve_fallback_gate_limits;
const _: fn(&str, &PaywallGateLimits) -> PaywallGate =
    solvapay_core::paywall_gate::build_paywall_gate;
const _: fn() -> Value = solvapay_core::paywall_gate::paywall_structured_content_schema;
const _: fn(&PaywallGate) -> PaywallClientPayload =
    solvapay_core::paywall_payload::paywall_client_payload;
const _: () = assert_boundary::<PaywallState>();
const _: () = assert_boundary::<PaywallState>();
const _: fn(Option<&PaywallLimits>) -> PaywallState =
    solvapay_core::paywall_state::classify_paywall_state;
const _: fn(Option<&PaywallLimits>) -> CreditSignals = solvapay_core::paywall_state::credit_signals;
const _: fn(&PaywallState) -> PaywallNextAction = solvapay_core::paywall_state::next_action_for;
const _: fn(Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::plans::validate_list_plans_params;
const _: fn(Option<&Value>) -> Option<BillingCycle> = solvapay_core::pricing_options::billing_cycle;
const _: () = assert_boundary::<Charge>();
const _: fn(Option<&Value>) -> bool = solvapay_core::pricing_options::counts_usage;
const _: fn(Option<&Value>, Option<&Value>, Option<&str>) -> Option<i64> =
    solvapay_core::pricing_options::credits_per_unit_from_balance;
const _: () = assert_boundary::<Charge>();
const _: fn(Option<&Value>, Option<&str>) -> Option<i64> =
    solvapay_core::pricing_options::included_units;
const _: fn(f64, f64, Option<f64>) -> i64 = solvapay_core::pricing_options::pegged_credits_per_unit;
const _: fn(Option<&Value>, Option<&str>) -> Option<Charge> =
    solvapay_core::pricing_options::per_unit_charge;
const _: fn(Option<&Value>) -> PlanPricingShape =
    solvapay_core::pricing_options::plan_pricing_shape;
const _: () = assert_boundary::<Tier>();
const _: fn(Option<&Value>) -> Option<i64> = solvapay_core::pricing_options::trial_days;
const _: fn(Option<&Value>, Option<&str>) -> Option<UsageRate> =
    solvapay_core::pricing_options::usage_rate;
const _: fn(Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::product::validate_get_product_params;
const _: fn(&str, &str) -> Result<(), SdkError> =
    solvapay_core::product_readiness::assert_valid_product_ref;
const _: fn(&ProductReadinessInput) -> ProductReadinessResult =
    solvapay_core::product_readiness::evaluate_product_readiness;
const _: () = assert_boundary::<ActiveProduct>();
const _: fn(Option<&str>, &str, Option<&str>) -> bool =
    solvapay_core::purchase::is_cached_customer_ref_valid;
const _: fn(Option<&Value>, Option<&str>) -> Option<Value> =
    solvapay_core::purchase::select_active_plan_purchase;
const _: fn(&str) -> HelperErrorResult = solvapay_core::renewal::classify_cancel_error;
const _: fn(&str) -> HelperErrorResult = solvapay_core::renewal::classify_reactivate_error;
const _: fn(&Value) -> Result<Value, HelperErrorResult> =
    solvapay_core::renewal::normalize_cancel_response;
const _: fn(&Value) -> Result<Value, HelperErrorResult> =
    solvapay_core::renewal::normalize_reactivate_response;
const _: fn(Option<&str>) -> Option<HelperErrorResult> =
    solvapay_core::renewal::validate_purchase_ref;
const _: fn(&Value) -> bool = solvapay_core::route_error::is_error_result;
const _: fn(&RouteErrorInput) -> HelperErrorResult = solvapay_core::route_error::map_route_error;
const _: fn(&SellerIdentityInput) -> SellerIdentityDisplay =
    solvapay_core::seller_identity::resolve_seller_identity_display;
const _: fn(Option<&str>) -> bool = solvapay_core::tax_summary::should_show_tax_row;
const _: fn(Option<&Value>, Option<&Value>) -> Result<TopupProcessNextOutput, HelperErrorResult> =
    solvapay_core::topup_process::topup_process_next;
const _: fn(Option<&Value>, Option<&Value>) -> UsageSnapshot =
    solvapay_core::usage::project_usage_snapshot;
const _: fn(&str) -> bool = solvapay_core::usage::should_retry_usage_error;
const _: fn(&str, &str, &str, i64) -> Result<Value, WebhookError> =
    solvapay_core::webhook::verify_webhook;
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<ActivatePlanDto>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<AssignCreditsRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<AttachBusinessDetailsParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CancelPurchaseParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CheckLimitsRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CloneProductOverrides>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreateCheckoutSessionRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreateCustomerRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreateCustomerSessionRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreatePaymentIntentParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreatePlanParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreateProductRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<CreateTopupPaymentIntentParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<DisableAutoRechargeParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<GetAutoRechargeParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<GetCreditActivityParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<GetCustomerParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<GetCustomerBalanceParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<GetPaymentMethodParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<GetUserInfoParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<ListPurchasesParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<ProcessPaymentIntentParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<ReactivatePurchaseParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SaveAutoRechargeParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<TrackUsageRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<TrackUsageBulkRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<UpdateCustomerParams>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<UpdatePlanRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<UpdateProductRequest>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
const _: () = assert_boundary::<SdkError>();
