/**
 * Fixture corpus census. Counts JSON fixtures under contract/fixtures,
 * classifies executed / delegated / unbound, and writes
 * contract/fixtures/census.generated.json.
 *
 *   pnpm census:record
 *   pnpm census:check
 */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { REPO_ROOT } from '../shared/paths.js'
import { generatedEntry } from '../shared/repo-paths.js'
import { isDirectRun, parseErrorResult, runScriptMain, type CliResult } from '../codegen/lib/cli.js'

export const CENSUS_PATH = generatedEntry('fixtureCensus').path
export const CENSUS_FILENAME = 'census.generated.json'

/** Driver-loop host simulations skipped by every language harness by design. */
export const DELEGATED_FNS = new Set(['driveGate', 'drivePayable'])

/**
 * Client fixtures are still `skipped_unbound` in the Rust fixture-runner until
 * `client_replay` lands. Flip this when those ops register in the runner.
 */
export const CLIENT_FIXTURES_UNBOUND = false

type BindingSnapshot = {
  bindings: Record<string, { artifact?: string }>
}

export type FixtureCensus = {
  _comment: string
  parsed: number
  executed: number
  delegated: number
  unbound: number
  suites: Record<string, number>
}

function absRel(rel: string): string {
  return path.join(REPO_ROOT, ...rel.split('/'))
}

function fixturesRoot(): string {
  return path.join(REPO_ROOT, 'contract', 'fixtures')
}

export function isCensusFile(filePath: string): boolean {
  return path.basename(filePath) === CENSUS_FILENAME
}

function walkJsonFiles(dir: string, acc: string[]): void {
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      walkJsonFiles(full, acc)
      continue
    }
    if (!name.endsWith('.json') || isCensusFile(full)) continue
    acc.push(full)
  }
}

function readSnapshot(): BindingSnapshot {
  const abs = absRel(generatedEntry('bindingSymbols').path)
  return JSON.parse(readFileSync(abs, 'utf8')) as BindingSnapshot
}

export function classifyFn(
  fn: string,
  snapshot: BindingSnapshot,
  clientUnbound: boolean = CLIENT_FIXTURES_UNBOUND,
): 'delegated' | 'unbound' | 'executed' {
  if (DELEGATED_FNS.has(fn)) return 'delegated'
  const artifact = snapshot.bindings[fn]?.artifact
  if (clientUnbound && artifact === 'client') return 'unbound'
  return 'executed'
}

export function buildCensus(
  files: readonly { suite: string; fn: string }[],
  snapshot: BindingSnapshot,
  clientUnbound: boolean = CLIENT_FIXTURES_UNBOUND,
): FixtureCensus {
  const suites: Record<string, number> = {}
  let executed = 0
  let delegated = 0
  let unbound = 0
  for (const file of files) {
    suites[file.suite] = (suites[file.suite] ?? 0) + 1
    const bucket = classifyFn(file.fn, snapshot, clientUnbound)
    if (bucket === 'delegated') delegated += 1
    else if (bucket === 'unbound') unbound += 1
    else executed += 1
  }
  const parsed = files.length
  if (parsed !== executed + delegated + unbound) {
    throw new Error(
      `census buckets do not sum to parsed: ${parsed} != ${executed}+${delegated}+${unbound}`,
    )
  }
  return {
    _comment:
      '@generated by pnpm census:record — do not edit. Regenerated: pnpm gen / pnpm census:record',
    parsed,
    executed,
    delegated,
    unbound,
    suites: Object.fromEntries(Object.keys(suites).sort().map(key => [key, suites[key]])),
  }
}

function loadFixtureFiles(): Array<{ suite: string; fn: string }> {
  const files: string[] = []
  walkJsonFiles(fixturesRoot(), files)
  files.sort()
  return files.map(filePath => {
    const raw = JSON.parse(readFileSync(filePath, 'utf8')) as {
      suite?: unknown
      input?: { fn?: unknown }
    }
    if (typeof raw.suite !== 'string' || raw.suite.length === 0) {
      throw new Error(`${filePath}: missing suite`)
    }
    if (typeof raw.input?.fn !== 'string' || raw.input.fn.length === 0) {
      throw new Error(`${filePath}: missing input.fn`)
    }
    return { suite: raw.suite, fn: raw.input.fn }
  })
}

export function writeCensus(): { census: FixtureCensus; text: string } {
  const census = buildCensus(loadFixtureFiles(), readSnapshot())
  const text = `${JSON.stringify(census, null, 2)}\n`
  writeFileSync(absRel(CENSUS_PATH), text)
  return { census, text }
}

export interface CliOptions {
  check: boolean
}

function printUsage(): string {
  return `Usage:
  pnpm census:record
  pnpm census:check
`
}

export function parseArgs(argv: string[]): CliOptions {
  let check = false
  for (const arg of argv) {
    if (arg === '--check') {
      check = true
      continue
    }
    if (arg === '--help' || arg === '-h') {
      throw new Error(printUsage().trim())
    }
    throw new Error(`Unknown argument: ${arg}`)
  }
  return { check }
}

export function runCensus(options: CliOptions): CliResult {
  const previousText = existsSync(absRel(CENSUS_PATH))
    ? readFileSync(absRel(CENSUS_PATH), 'utf8')
    : ''
  const { census, text } = writeCensus()
  if (options.check && previousText !== text) {
    return {
      exitCode: 1,
      stdout: '',
      stderr: `census: ${CENSUS_PATH} is stale — run pnpm census:record\n`,
    }
  }
  return {
    exitCode: 0,
    stdout: `census: parsed=${census.parsed} executed=${census.executed} delegated=${census.delegated} unbound=${census.unbound}\n`,
    stderr: '',
  }
}

export async function runCli(argv: string[]): Promise<CliResult> {
  try {
    return runCensus(parseArgs(argv))
  } catch (error) {
    return parseErrorResult(error, printUsage())
  }
}

if (isDirectRun(import.meta.url, process.argv[1])) {
  void runScriptMain(runCli)
}
