//! @generated by dto-gen (--python-bindings-out) — do not edit. Regenerate with: pnpm gen
//! Sync JSON-envelope PyO3 exports for decision / paywall / retry cores (Step 41-b).
//!
//! Each function takes one JSON-args string and returns one envelope string
//! (`{"ok":true,"value":…}` | `{"ok":false,"error":…}`). Arg shapes mirror
//! `tools/conformance/fixture-runner/src/bindings/{helpers,paywall_*,retry}.rs`.

use pyo3::prelude::*;
use serde_json::Value;
use solvapay_core::{
    assert_valid_product_ref, attach_business_details_validation_error, billing_cycle,
    build_create_customer_params, build_gate_message, build_nudge_message, build_paywall_gate,
    charges, classify_cancel_error, classify_create_error, classify_customer_ref,
    classify_lookup_error, classify_paywall_state, classify_reactivate_error,
    coerce_customer_options, counts_usage, credits_per_unit_from_balance, decide_paywall_outcome,
    ensure_customer_next, evaluate_balance_observation, evaluate_cached_limits,
    evaluate_fresh_limits, evaluate_product_readiness, extract_backend_customer_ref, gate_next,
    headline_charges, included_units, is_cached_customer_ref_valid, is_email_conflict,
    is_error_result, map_route_error, meter_name, normalize_cancel_response,
    normalize_reactivate_response, paywall_client_payload, pegged_credits_per_unit,
    per_unit_charge, project_payment_intent_result, project_topup_process_outcome,
    project_usage_snapshot, require_product_ref, resolve_authenticated_user,
    resolve_check_limits_params, resolve_fallback_gate_limits, resolve_product_ref,
    resolve_purchase_customer_ref, resolve_return_url, select_active_purchases,
    should_retry_usage_error, trial_days, validate_activate_plan_params,
    validate_attach_business_details_params, validate_checkout_session_params,
    validate_create_payment_intent_params, validate_get_product_params, validate_list_plans_params,
    validate_process_payment_intent_params, validate_purchase_ref,
    validate_topup_payment_intent_params, AuthResolutionInput, Backoff, GateContent,
    PaymentIntentSource, PaywallGate, PaywallGateLimits, PaywallLimits, PaywallState,
    ProductReadinessInput, RetryPolicy, RouteErrorInput, RouteErrorKind, SdkError,
    DEFAULT_INITIAL_DELAY_MS, DEFAULT_MAX_RETRIES,
};

use crate::args::{
    args_map, option_helper_err, optional_f64, optional_string, optional_typed, optional_u16,
    optional_u32, optional_u64, optional_value, require_array, require_bool, require_f64,
    require_i64, require_object, require_string, require_typed, require_u32, result_as_value,
    to_value,
};
use crate::error::run_envelope_sync;

// --- customer-sync ---

/// Binding for `classifyCustomerRef`.
#[pyfunction(name = "classify_customer_ref")]
pub fn classify_customer_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let customer_ref = require_string(&args, "customerRef")?;
        to_value(&classify_customer_ref(&customer_ref))
    })
}

/// Binding for `coerceCustomerOptions`.
#[pyfunction(name = "coerce_customer_options")]
pub fn coerce_customer_options_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let email = optional_string(&args, "email")?;
        let name = optional_string(&args, "name")?;
        to_value(&coerce_customer_options(email.as_deref(), name.as_deref()))
    })
}

/// Binding for `buildCreateCustomerParams` (`nowMs` is required; no clock string).
#[pyfunction(name = "build_create_customer_params")]
pub fn build_create_customer_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let customer_ref = require_string(&args, "customerRef")?;
        let external_ref = optional_string(&args, "externalRef")?;
        let email = optional_string(&args, "email")?;
        let name = optional_string(&args, "name")?;
        let now_ms = require_i64(&args, "nowMs")?;
        to_value(&build_create_customer_params(
            &customer_ref,
            external_ref.as_deref(),
            email.as_deref(),
            name.as_deref(),
            now_ms,
        ))
    })
}

/// Binding for `extractBackendCustomerRef`.
#[pyfunction(name = "extract_backend_customer_ref")]
pub fn extract_backend_customer_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let response = require_object(&args, "response")?;
        let fallback = require_string(&args, "fallback")?;
        Ok(Value::String(extract_backend_customer_ref(
            response, &fallback,
        )))
    })
}

/// Binding for `classifyLookupError`.
#[pyfunction(name = "classify_lookup_error")]
pub fn classify_lookup_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let message = require_string(&args, "message")?;
        to_value(&classify_lookup_error(&message))
    })
}

/// Binding for `classifyCreateError`.
#[pyfunction(name = "classify_create_error")]
pub fn classify_create_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let message = require_string(&args, "message")?;
        to_value(&classify_create_error(&message))
    })
}

/// Binding for `isEmailConflict`.
#[pyfunction(name = "is_email_conflict")]
pub fn is_email_conflict_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let message = require_string(&args, "message")?;
        Ok(Value::Bool(is_email_conflict(&message)))
    })
}

// --- activation ---

/// Binding for `validateActivatePlanParams`.
#[pyfunction(name = "validate_activate_plan_params")]
pub fn validate_activate_plan_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = optional_string(&args, "productRef")?;
        let plan_ref = optional_string(&args, "planRef")?;
        option_helper_err(validate_activate_plan_params(
            product_ref.as_deref(),
            plan_ref.as_deref(),
        ))
    })
}

// --- payment ---

/// Binding for `validateCreatePaymentIntentParams`.
#[pyfunction(name = "validate_create_payment_intent_params")]
pub fn validate_create_payment_intent_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let plan_ref = optional_string(&args, "planRef")?;
        let product_ref = optional_string(&args, "productRef")?;
        option_helper_err(validate_create_payment_intent_params(
            plan_ref.as_deref(),
            product_ref.as_deref(),
        ))
    })
}

/// Binding for `validateTopupPaymentIntentParams`.
#[pyfunction(name = "validate_topup_payment_intent_params")]
pub fn validate_topup_payment_intent_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let amount = optional_f64(&args, "amount")?;
        let currency = optional_string(&args, "currency")?;
        option_helper_err(validate_topup_payment_intent_params(
            amount,
            currency.as_deref(),
        ))
    })
}

/// Binding for `validateProcessPaymentIntentParams`.
#[pyfunction(name = "validate_process_payment_intent_params")]
pub fn validate_process_payment_intent_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let payment_intent_id = optional_string(&args, "paymentIntentId")?;
        let product_ref = optional_string(&args, "productRef")?;
        option_helper_err(validate_process_payment_intent_params(
            payment_intent_id.as_deref(),
            product_ref.as_deref(),
        ))
    })
}

/// Binding for `validateAttachBusinessDetailsParams`.
#[pyfunction(name = "validate_attach_business_details_params")]
pub fn validate_attach_business_details_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let payment_intent_id = optional_string(&args, "paymentIntentId")?;
        option_helper_err(validate_attach_business_details_params(
            payment_intent_id.as_deref(),
        ))
    })
}

/// Binding for `attachBusinessDetailsValidationError`.
#[pyfunction(name = "attach_business_details_validation_error")]
pub fn attach_business_details_validation_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let first_issue_message = optional_string(&args, "firstIssueMessage")?;
        to_value(&attach_business_details_validation_error(
            first_issue_message.as_deref(),
        ))
    })
}

/// Binding for `projectPaymentIntentResult`.
#[pyfunction(name = "project_payment_intent_result")]
pub fn project_payment_intent_result_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let processor_payment_id = require_string(&args, "processorPaymentId")?;
        let client_secret = require_string(&args, "clientSecret")?;
        let publishable_key = require_string(&args, "publishableKey")?;
        let customer_ref = require_string(&args, "customerRef")?;
        let account_id = optional_string(&args, "accountId")?;
        to_value(&project_payment_intent_result(
            &PaymentIntentSource {
                processor_payment_id,
                client_secret,
                publishable_key,
                account_id,
            },
            &customer_ref,
        ))
    })
}

/// Binding for `projectTopupProcessOutcome`.
#[pyfunction(name = "project_topup_process_outcome")]
pub fn project_topup_process_outcome_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let status = optional_string(&args, "status")?;
        let message = optional_string(&args, "message")?;
        to_value(&project_topup_process_outcome(
            status.as_deref(),
            message.as_deref(),
        ))
    })
}

// --- checkout ---

/// Binding for `resolveReturnUrl`.
#[pyfunction(name = "resolve_return_url")]
pub fn resolve_return_url_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let body_return_url = optional_string(&args, "bodyReturnUrl")?;
        let options_return_url = optional_string(&args, "optionsReturnUrl")?;
        let origin = optional_string(&args, "origin")?;
        match resolve_return_url(
            body_return_url.as_deref(),
            options_return_url.as_deref(),
            origin.as_deref(),
        ) {
            None => Ok(Value::Null),
            Some(url) => Ok(Value::String(url)),
        }
    })
}

/// Binding for `validateCheckoutSessionParams`.
#[pyfunction(name = "validate_checkout_session_params")]
pub fn validate_checkout_session_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = optional_string(&args, "productRef")?;
        option_helper_err(validate_checkout_session_params(product_ref.as_deref()))
    })
}

// --- purchase ---

/// Binding for `isCachedCustomerRefValid`.
#[pyfunction(name = "is_cached_customer_ref_valid")]
pub fn is_cached_customer_ref_valid_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let external_ref = optional_string(&args, "externalRef")?;
        let user_id = require_string(&args, "userId")?;
        let customer_ref = optional_string(&args, "customerRef")?;
        Ok(Value::Bool(is_cached_customer_ref_valid(
            external_ref.as_deref(),
            &user_id,
            customer_ref.as_deref(),
        )))
    })
}

/// Binding for `resolvePurchaseCustomerRef`.
#[pyfunction(name = "resolve_purchase_customer_ref")]
pub fn resolve_purchase_customer_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let customer_ref = optional_string(&args, "customerRef")?;
        let user_id = require_string(&args, "userId")?;
        Ok(Value::String(resolve_purchase_customer_ref(
            customer_ref.as_deref(),
            &user_id,
        )))
    })
}

/// Binding for `selectActivePurchases`.
#[pyfunction(name = "select_active_purchases")]
pub fn select_active_purchases_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let purchases = require_array(&args, "purchases")?;
        Ok(Value::Array(select_active_purchases(purchases)))
    })
}

// --- renewal ---

/// Binding for `classifyCancelError`.
#[pyfunction(name = "classify_cancel_error")]
pub fn classify_cancel_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let message = require_string(&args, "message")?;
        to_value(&classify_cancel_error(&message))
    })
}

/// Binding for `classifyReactivateError`.
#[pyfunction(name = "classify_reactivate_error")]
pub fn classify_reactivate_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let message = require_string(&args, "message")?;
        to_value(&classify_reactivate_error(&message))
    })
}

/// Binding for `normalizeCancelResponse`.
///
/// Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**.
#[pyfunction(name = "normalize_cancel_response")]
pub fn normalize_cancel_response_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let response = args.get("response").cloned().unwrap_or(Value::Null);
        result_as_value(normalize_cancel_response(&response))
    })
}

/// Binding for `normalizeReactivateResponse`.
///
/// Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**.
#[pyfunction(name = "normalize_reactivate_response")]
pub fn normalize_reactivate_response_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let response = args.get("response").cloned().unwrap_or(Value::Null);
        result_as_value(normalize_reactivate_response(&response))
    })
}

/// Binding for `validatePurchaseRef`.
#[pyfunction(name = "validate_purchase_ref")]
pub fn validate_purchase_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let purchase_ref = optional_string(&args, "purchaseRef")?;
        option_helper_err(validate_purchase_ref(purchase_ref.as_deref()))
    })
}

// --- usage ---

/// Binding for `projectUsageSnapshot`.
#[pyfunction(name = "project_usage_snapshot")]
pub fn project_usage_snapshot_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let purchase = match args.get("activePurchase") {
            None | Some(Value::Null) => None,
            Some(v) => Some(v),
        };
        let limits = match args.get("limits") {
            None | Some(Value::Null) => None,
            Some(v) => Some(v),
        };
        to_value(&project_usage_snapshot(purchase, limits))
    })
}

// --- limits ---

/// Binding for `resolveCheckLimitsParams`.
///
/// Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**. Precedence is meterName, then usageType, then `requests`.
#[pyfunction(name = "resolve_check_limits_params")]
pub fn resolve_check_limits_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = optional_string(&args, "productRef")?;
        let meter_name = optional_string(&args, "meterName")?;
        let usage_type = optional_string(&args, "usageType")?;
        result_as_value(resolve_check_limits_params(
            product_ref.as_deref(),
            meter_name.as_deref(),
            usage_type.as_deref(),
        ))
    })
}

// --- usage ---

/// Binding for `shouldRetryUsageError`.
#[pyfunction(name = "should_retry_usage_error")]
pub fn should_retry_usage_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let message = require_string(&args, "message")?;
        Ok(Value::Bool(should_retry_usage_error(&message)))
    })
}

// --- plans ---

/// Binding for `validateListPlansParams`.
#[pyfunction(name = "validate_list_plans_params")]
pub fn validate_list_plans_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = optional_string(&args, "productRef")?;
        option_helper_err(validate_list_plans_params(product_ref.as_deref()))
    })
}

// --- error ---

/// Binding for `isErrorResult`.
#[pyfunction(name = "is_error_result")]
pub fn is_error_result_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let value = args.get("result").cloned().unwrap_or(Value::Null);
        Ok(Value::Bool(is_error_result(&value)))
    })
}

/// Binding for `mapRouteError` (`kind`: `"solvapay"` | `"error"` | `"unknown"`).
#[pyfunction(name = "map_route_error")]
pub fn map_route_error_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let kind = match require_string(&args, "kind")?.as_str() {
            "solvapay" => RouteErrorKind::SolvaPay,
            "error" => RouteErrorKind::Error,
            "unknown" => RouteErrorKind::Unknown,
            other => {
                return Err(SdkError::transport(
                    format!("args.kind must be 'solvapay' | 'error' | 'unknown', got {other:?}"),
                    false,
                ));
            }
        };
        let message = optional_string(&args, "message")?;
        let default_message = optional_string(&args, "defaultMessage")?;
        let operation_name = require_string(&args, "operationName")?;
        let status = optional_u16(&args, "status")?;
        to_value(&map_route_error(&RouteErrorInput {
            kind,
            message,
            status,
            operation_name,
            default_message,
        }))
    })
}

// --- product ---

/// Binding for `validateGetProductParams`.
#[pyfunction(name = "validate_get_product_params")]
pub fn validate_get_product_params_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = optional_string(&args, "productRef")?;
        option_helper_err(validate_get_product_params(product_ref.as_deref()))
    })
}

// --- paywall-decision ---

/// Binding for `resolveProductRef`.
#[pyfunction(name = "resolve_product_ref")]
pub fn resolve_product_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let metadata_product = optional_string(&args, "metadataProduct")?;
        let env_product = optional_string(&args, "envProduct")?;
        to_value(&resolve_product_ref(
            metadata_product.as_deref(),
            env_product.as_deref(),
        ))
    })
}

/// Binding for `evaluateCachedLimits`.
#[pyfunction(name = "evaluate_cached_limits")]
pub fn evaluate_cached_limits_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let remaining = require_f64(&args, "remaining")?;
        to_value(&evaluate_cached_limits(remaining))
    })
}

/// Binding for `evaluateFreshLimits`.
#[pyfunction(name = "evaluate_fresh_limits")]
pub fn evaluate_fresh_limits_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let within_limits = require_bool(&args, "withinLimits")?;
        let remaining = require_f64(&args, "remaining")?;
        to_value(&evaluate_fresh_limits(within_limits, remaining))
    })
}

/// Binding for `decidePaywallOutcome`.
#[pyfunction(name = "decide_paywall_outcome")]
pub fn decide_paywall_outcome_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let within_limits = require_bool(&args, "withinLimits")?;
        let product = require_string(&args, "product")?;
        let checkout_url = optional_string(&args, "checkoutUrl")?;
        let limits = optional_value(&args, "limits");
        to_value(&decide_paywall_outcome(
            within_limits,
            &product,
            limits.as_ref(),
            checkout_url.as_deref(),
        ))
    })
}

/// Binding for `resolveFallbackGateLimits`.
#[pyfunction(name = "resolve_fallback_gate_limits")]
pub fn resolve_fallback_gate_limits_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let checkout_url = optional_string(&args, "checkoutUrl")?;
        to_value(&resolve_fallback_gate_limits(checkout_url.as_deref()))
    })
}

// --- paywall state / gate / payload ---

/// Binding for `classifyPaywallState`.
#[pyfunction(name = "classify_paywall_state")]
pub fn classify_paywall_state_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let limits = optional_typed::<PaywallLimits>(&args, "limits")?;
        to_value(&classify_paywall_state(limits.as_ref()))
    })
}

/// Binding for `buildGateMessage`.
#[pyfunction(name = "build_gate_message")]
pub fn build_gate_message_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let state = require_typed::<PaywallState>(&args, "state")?;
        let gate = require_typed::<GateContent>(&args, "gate")?;
        Ok(Value::String(build_gate_message(&state, &gate)))
    })
}

/// Binding for `buildNudgeMessage`.
#[pyfunction(name = "build_nudge_message")]
pub fn build_nudge_message_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let state = require_typed::<PaywallState>(&args, "state")?;
        let limits = optional_typed::<PaywallLimits>(&args, "limits")?;
        Ok(Value::String(build_nudge_message(&state, limits.as_ref())))
    })
}

/// Binding for `buildPaywallGate`.
#[pyfunction(name = "build_paywall_gate")]
pub fn build_paywall_gate_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = require_string(&args, "productRef")?;
        let limits = require_typed::<PaywallGateLimits>(&args, "limits")?;
        to_value(&build_paywall_gate(&product_ref, &limits))
    })
}

/// Binding for `paywallErrorToClientPayload`.
///
/// Requires `message` + `structuredContent`; payload content comes from the gate
/// (message is unused for payload body — fixture-runner parity).
#[pyfunction(name = "paywall_error_to_client_payload")]
pub fn paywall_error_to_client_payload_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let _message = require_string(&args, "message")?;
        let gate = require_typed::<PaywallGate>(&args, "structuredContent")?;
        to_value(&paywall_client_payload(&gate))
    })
}

// --- paywall-decision ---

/// Binding for `requireProductRef`. Throws when neither source is set.
#[pyfunction(name = "require_product_ref")]
pub fn require_product_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let metadata_product = optional_string(&args, "metadataProduct")?;
        let env_product = optional_string(&args, "envProduct")?;
        Ok(Value::String(require_product_ref(
            metadata_product.as_deref(),
            env_product.as_deref(),
        )?))
    })
}

// --- product-readiness ---

/// Binding for `evaluateProductReadiness`.
#[pyfunction(name = "evaluate_product_readiness")]
pub fn evaluate_product_readiness_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let input: ProductReadinessInput = serde_json::from_str(&args_json).map_err(|err| {
            SdkError::transport(format!("invalid ProductReadinessInput: {err}"), false)
        })?;
        to_value(&evaluate_product_readiness(&input))
    })
}

// --- paywall-decision ---

/// Binding for `gateNext`.
#[pyfunction(name = "gate_next")]
pub fn gate_next_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let state = optional_value(&args, "state");
        let event = optional_value(&args, "event");
        result_as_value(gate_next(state.as_ref(), event.as_ref()))
    })
}

// --- retry ---

/// Binding for `retryNextDelayMs`.
///
/// Args: `{ maxRetries?, initialDelay?, backoffStrategy?, attempt }`.
/// Envelope value is delay milliseconds, or `null` when retries are exhausted.
#[pyfunction(name = "retry_next_delay_ms")]
pub fn retry_next_delay_ms(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let attempt = require_u32(&args, "attempt")?;
        let mut policy = RetryPolicy {
            max_retries: DEFAULT_MAX_RETRIES,
            initial_delay_ms: DEFAULT_INITIAL_DELAY_MS,
            backoff: Backoff::Fixed,
        };
        if let Some(max_retries) = optional_u32(&args, "maxRetries")? {
            policy.max_retries = max_retries;
        }
        if let Some(initial_delay) = optional_u64(&args, "initialDelay")? {
            policy.initial_delay_ms = initial_delay;
        }
        if let Some(strategy) = optional_string(&args, "backoffStrategy")? {
            policy.backoff = match strategy.as_str() {
                "fixed" => Backoff::Fixed,
                "linear" => Backoff::Linear,
                "exponential" => Backoff::Exponential,
                other => {
                    return Err(SdkError::transport(
                        format!(
                            "args.backoffStrategy must be fixed|linear|exponential, got {other}"
                        ),
                        false,
                    ));
                }
            };
        }
        match policy.next_delay(attempt) {
            None => Ok(Value::Null),
            Some(delay) => {
                let ms = u64::try_from(delay.as_millis()).unwrap_or(u64::MAX);
                Ok(Value::from(ms))
            }
        }
    })
}

// --- product-readiness ---

/// Binding for `assertValidProductRef`. Throws on empty, placeholder, or non-prd_ refs.
#[pyfunction(name = "assert_valid_product_ref")]
pub fn assert_valid_product_ref_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let product_ref = require_string(&args, "productRef")?;
        let context = require_string(&args, "context")?;
        assert_valid_product_ref(&product_ref, &context)?;
        Ok(Value::Null)
    })
}

// --- paywall-decision ---

/// Binding for `ensureCustomerNext`.
#[pyfunction(name = "ensure_customer_next")]
pub fn ensure_customer_next_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let state = optional_value(&args, "state");
        let event = optional_value(&args, "event");
        result_as_value(ensure_customer_next(state.as_ref(), event.as_ref()))
    })
}

// --- plans ---

/// Binding for `charges`.
#[pyfunction(name = "charges")]
pub fn charges_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        to_value(&charges(priced.as_ref()))
    })
}

// --- auth-resolution ---

/// Binding for `resolveAuthenticatedUser`.
#[pyfunction(name = "resolve_authenticated_user")]
pub fn resolve_authenticated_user_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let input = require_typed::<AuthResolutionInput>(&args, "input")?;
        result_as_value(resolve_authenticated_user(&input))
    })
}

// --- balance-poll ---

/// Binding for `evaluateBalanceObservation`.
#[pyfunction(name = "evaluate_balance_observation")]
pub fn evaluate_balance_observation_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let baseline = require_f64(&args, "baseline")?;
        let credits = require_f64(&args, "credits")?;
        to_value(&evaluate_balance_observation(baseline, credits))
    })
}

// --- plans ---

/// Binding for `headlineCharges`.
#[pyfunction(name = "headline_charges")]
pub fn headline_charges_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        to_value(&headline_charges(priced.as_ref()))
    })
}

/// Binding for `perUnitCharge`.
#[pyfunction(name = "per_unit_charge")]
pub fn per_unit_charge_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        let meter = optional_string(&args, "meter")?;
        to_value(&per_unit_charge(priced.as_ref(), meter.as_deref()))
    })
}

/// Binding for `billingCycle`.
#[pyfunction(name = "billing_cycle")]
pub fn billing_cycle_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        to_value(&billing_cycle(priced.as_ref()))
    })
}

/// Binding for `trialDays`.
#[pyfunction(name = "trial_days")]
pub fn trial_days_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        to_value(&trial_days(priced.as_ref()))
    })
}

/// Binding for `includedUnits`.
#[pyfunction(name = "included_units")]
pub fn included_units_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        let meter = optional_string(&args, "meter")?;
        to_value(&included_units(priced.as_ref(), meter.as_deref()))
    })
}

/// Binding for `peggedCreditsPerUnit`.
#[pyfunction(name = "pegged_credits_per_unit")]
pub fn pegged_credits_per_unit_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let charge_minor = require_f64(&args, "chargeMinor")?;
        let credits_per_minor_unit = require_f64(&args, "creditsPerMinorUnit")?;
        let usd_to_charge_rate = optional_f64(&args, "usdToChargeRate")?;
        to_value(&pegged_credits_per_unit(
            charge_minor,
            credits_per_minor_unit,
            usd_to_charge_rate,
        ))
    })
}

/// Binding for `creditsPerUnitFromBalance`.
#[pyfunction(name = "credits_per_unit_from_balance")]
pub fn credits_per_unit_from_balance_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        let balance = optional_value(&args, "balance");
        let meter = optional_string(&args, "meter")?;
        to_value(&credits_per_unit_from_balance(
            priced.as_ref(),
            balance.as_ref(),
            meter.as_deref(),
        ))
    })
}

/// Binding for `meterName`.
#[pyfunction(name = "meter_name")]
pub fn meter_name_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        to_value(&meter_name(priced.as_ref()))
    })
}

/// Binding for `countsUsage`.
#[pyfunction(name = "counts_usage")]
pub fn counts_usage_binding(args_json: String) -> String {
    run_envelope_sync(|| {
        let args = args_map(&args_json)?;
        let priced = optional_value(&args, "priced");
        Ok(Value::Bool(counts_usage(priced.as_ref())))
    })
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_docs_in_private_items,
    missing_docs
)]
mod tests {
    use super::{build_paywall_gate_binding, classify_customer_ref_binding, retry_next_delay_ms};
    use serde_json::Value;

    fn parse_envelope(json: &str) -> Value {
        serde_json::from_str(json).expect("envelope must be JSON")
    }

    #[test]
    fn classify_customer_ref_envelope_round_trips() {
        let env = parse_envelope(&classify_customer_ref_binding(
            r#"{"customerRef":"cus_abc123"}"#.to_owned(),
        ));
        assert_eq!(env["ok"], true);
        assert_eq!(env["value"], "backend");
    }

    #[test]
    fn build_paywall_gate_envelope_matches_shape() {
        let env = parse_envelope(&build_paywall_gate_binding(
            r#"{"productRef":"prod_1","limits":{"remaining":0}}"#.to_owned(),
        ));
        assert_eq!(env["ok"], true);
        assert!(env["value"]["kind"].is_string());
        assert_eq!(env["value"]["product"], "prod_1");
    }

    #[test]
    fn retry_next_delay_exhaustion_is_null() {
        let env = parse_envelope(&retry_next_delay_ms(
            r#"{"attempt":2,"maxRetries":2}"#.to_owned(),
        ));
        assert_eq!(env["ok"], true);
        assert!(env["value"].is_null());
    }

    #[test]
    fn retry_next_delay_fixed_default() {
        let env = parse_envelope(&retry_next_delay_ms(r#"{"attempt":0}"#.to_owned()));
        assert_eq!(env["ok"], true);
        assert_eq!(env["value"], 500);
    }
}
