# Cloud Build Configuration for Frontend Development Environment
# Triggered on: Git push to dev branch
# Deploys to: openai-actions-dev Cloud Run service

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/solvapay-examples/openai-actions:dev-$SHORT_SHA'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/solvapay-examples/openai-actions:dev-latest'
      - '-f'
      - 'examples/nextjs-openai-custom-gpt-actions/Dockerfile.cloudrun'
      # NEXT_PUBLIC_* variables (build-time, client-side)
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_AGENT_REF=$_NEXT_PUBLIC_AGENT_REF'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=$_NEXT_PUBLIC_GA_MEASUREMENT_ID'
      # Server-side variables (runtime)
      - '--build-arg'
      - 'SOLVAPAY_SECRET_KEY=$_SOLVAPAY_SECRET_KEY'
      - '--build-arg'
      - 'SOLVAPAY_API_BASE_URL=$_SOLVAPAY_API_BASE_URL'
      - '--build-arg'
      - 'SOLVAPAY_CLIENT_ID=$_SOLVAPAY_CLIENT_ID'
      - '--build-arg'
      - 'SOLVAPAY_CLIENT_SECRET=$_SOLVAPAY_CLIENT_SECRET'
      - '--build-arg'
      - 'SOLVAPAY_AUTH_URL=$_SOLVAPAY_AUTH_URL'
      - '--build-arg'
      - 'SOLVAPAY_TOKEN_URL=$_SOLVAPAY_TOKEN_URL'
      - '--build-arg'
      - 'SOLVAPAY_USERINFO_URL=$_SOLVAPAY_USERINFO_URL'
      - '--build-arg'
      - 'SOLVAPAY_FRONTEND_URL=$_SOLVAPAY_FRONTEND_URL'
      - '--build-arg'
      - 'SUPABASE_JWT_SECRET=$_SUPABASE_JWT_SECRET'
      - '--build-arg'
      - 'SUPABASE_DB_URL=$_SUPABASE_DB_URL'
      - '--build-arg'
      - 'SUPABASE_SERVICE_ROLE_KEY=$_SUPABASE_SERVICE_ROLE_KEY'
      - '--build-arg'
      - 'PUBLIC_URL=$_PUBLIC_URL'
      - '.'
    timeout: '900s'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/solvapay-examples/openai-actions'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run (Development)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloudrun'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'openai-actions-dev'
      - '--image=europe-west2-docker.pkg.dev/$PROJECT_ID/solvapay-examples/openai-actions:dev-latest'
      - '--platform=managed'
      - '--region=europe-west2'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--concurrency=80'
      - '--timeout=60'
      - '--allow-unauthenticated'
      - '--port=8080'
    waitFor: ['push-image']

# Images to be pushed to Artifact Registry
images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/solvapay-examples/openai-actions:dev-$SHORT_SHA'
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/solvapay-examples/openai-actions:dev-latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1200s'

# Tags for filtering builds
tags: ['dev', 'frontend', 'development']

