/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * napi client wrapping Rust [`SolvaPayClient`] over [`ReqwestTransport`].
 *
 * Every method takes one JSON-args string and returns one envelope string
 * (`{"ok":true,"value":…}` | `{"ok":false,"error":…}`).
 */
export declare class NativeClient {
  /**
   * Constructs a client over `ReqwestTransport` + `ClientShell`.
   *
   * # Arguments
   *
   * * `api_key` - Bearer token.
   * * `api_base_url` - Optional origin; defaults to `https://api.solvapay.com`.
   *
   * # Errors
   *
   * Returns a napi error when the reqwest client cannot be built.
   */
  constructor(apiKey: string, apiBaseUrl?: string | undefined | null)
  /** `POST /v1/sdk/customers` */
  createCustomer(argsJson: string): Promise<string>
  /**
   * `PATCH /v1/sdk/customers/{customerRef}`
   *
   * Args JSON is `{ customerRef, ...body }` — Rust splits path vs body.
   */
  updateCustomer(argsJson: string): Promise<string>
  /** Customer lookup by ref / externalRef / email. */
  getCustomer(argsJson: string): Promise<string>
  /** Grant credits to a customer. */
  assignCredits(argsJson: string): Promise<string>
  /** Credit balance for a customer. */
  getCustomerBalance(argsJson: string): Promise<string>
  /** User info for a customer/product pair. */
  getUserInfo(argsJson: string): Promise<string>
  /** Hosted checkout session. */
  createCheckoutSession(argsJson: string): Promise<string>
  /** Customer portal session. */
  createCustomerSession(argsJson: string): Promise<string>
  /** Merchant profile (`args_json` ignored; pass `"{}"`). */
  getMerchant(argsJson: string): Promise<string>
  /** Platform config (`args_json` ignored; pass `"{}"`). */
  getPlatformConfig(argsJson: string): Promise<string>
  /** `POST /v1/sdk/payment-intents` (plan checkout). */
  createPaymentIntent(argsJson: string): Promise<string>
  /** `POST /v1/sdk/payment-intents` (credit top-up). */
  createTopupPaymentIntent(argsJson: string): Promise<string>
  /** `POST /v1/sdk/payment-intents/{id}/process` */
  processPaymentIntent(argsJson: string): Promise<string>
  /** `POST /v1/sdk/payment-intents/{id}/business-details` */
  attachBusinessDetails(argsJson: string): Promise<string>
  /** `POST /v1/sdk/activate` */
  activatePlan(argsJson: string): Promise<string>
  /** `POST /v1/sdk/limits` */
  checkLimits(argsJson: string): Promise<string>
  /** `POST /v1/sdk/usages` */
  trackUsage(argsJson: string): Promise<string>
  /** `POST /v1/sdk/usages/bulk` */
  trackUsageBulk(argsJson: string): Promise<string>
  /**
   * `GET /v1/sdk/products/{productRef}`
   *
   * Args JSON is `{ productRef }`.
   */
  getProduct(argsJson: string): Promise<string>
  /** `GET /v1/sdk/products` (`args_json` ignored; pass `"{}"`). */
  listProducts(argsJson: string): Promise<string>
  /** `POST /v1/sdk/products` */
  createProduct(argsJson: string): Promise<string>
  /**
   * `PUT /v1/sdk/products/{productRef}`
   *
   * Args JSON is `{ productRef, ...params }`.
   */
  updateProduct(argsJson: string): Promise<string>
  /**
   * `DELETE /v1/sdk/products/{productRef}`
   *
   * Args JSON is `{ productRef }`. Success value is `null`.
   */
  deleteProduct(argsJson: string): Promise<string>
  /**
   * `POST /v1/sdk/products/{productRef}/clone`
   *
   * Args JSON is `{ productRef, name? }`.
   */
  cloneProduct(argsJson: string): Promise<string>
  /** `POST /v1/sdk/products/mcp/bootstrap` */
  bootstrapMcpProduct(argsJson: string): Promise<string>
  /**
   * `PUT /v1/sdk/products/{productRef}/mcp/plans`
   *
   * Args JSON is `{ productRef, ...params }`.
   */
  configureMcpPlans(argsJson: string): Promise<string>
  /**
   * `GET /v1/sdk/products/{productRef}/plans`
   *
   * Args JSON is `{ productRef }`.
   */
  listPlans(argsJson: string): Promise<string>
  /** `POST /v1/sdk/products/{productRef}/plans` (`productRef` in body). */
  createPlan(argsJson: string): Promise<string>
  /**
   * `PUT /v1/sdk/products/{productRef}/plans/{planRef}`
   *
   * Args JSON is `{ productRef, planRef, ...params }`.
   */
  updatePlan(argsJson: string): Promise<string>
  /**
   * `DELETE /v1/sdk/products/{productRef}/plans/{planRef}`
   *
   * Args JSON is `{ productRef, planRef }`. Success value is `null`.
   */
  deletePlan(argsJson: string): Promise<string>
  /** `POST /v1/sdk/purchases/{purchaseRef}/cancel` */
  cancelPurchase(argsJson: string): Promise<string>
  /** `POST /v1/sdk/purchases/{purchaseRef}/reactivate` */
  reactivatePurchase(argsJson: string): Promise<string>
  /** `GET /v1/sdk/payment-method` */
  getPaymentMethod(argsJson: string): Promise<string>
  /** `GET /v1/sdk/auto-recharge` */
  getAutoRecharge(argsJson: string): Promise<string>
  /** `PUT /v1/sdk/auto-recharge` */
  saveAutoRecharge(argsJson: string): Promise<string>
  /** `DELETE /v1/sdk/auto-recharge` */
  disableAutoRecharge(argsJson: string): Promise<string>
}

/**
 * Binding for `assertResponseResult` — brand failures are Transport errors
 * (TS wrapper rethrows as plain `Error` for fixture name parity).
 */
export declare function assertResponseResult(argsJson: string): string

/** Binding for `attachBusinessDetailsValidationError`. */
export declare function attachBusinessDetailsValidationError(argsJson: string): string

/** Binding for `buildCreateCustomerParams` (`nowMs` is required; no clock string). */
export declare function buildCreateCustomerParams(argsJson: string): string

/** Binding for `buildGateMessage`. */
export declare function buildGateMessage(argsJson: string): string

/** Binding for `buildNudgeMessage`. */
export declare function buildNudgeMessage(argsJson: string): string

/** Binding for `buildPaywallGate`. */
export declare function buildPaywallGate(argsJson: string): string

/** Binding for `buildPromptDescriptorMetadata`. */
export declare function buildPromptDescriptorMetadata(argsJson: string): string

/** Binding for `buildPromptUserMessage`. */
export declare function buildPromptUserMessage(argsJson: string): string

/** Binding for `buildToolDescriptorMetadata`. */
export declare function buildToolDescriptorMetadata(argsJson: string): string

/** Binding for `classifyCancelError`. */
export declare function classifyCancelError(argsJson: string): string

/** Binding for `classifyCreateError`. */
export declare function classifyCreateError(argsJson: string): string

/** Binding for `classifyCustomerRef`. */
export declare function classifyCustomerRef(argsJson: string): string

/** Binding for `classifyLookupError`. */
export declare function classifyLookupError(argsJson: string): string

/** Binding for `classifyPaywallState`. */
export declare function classifyPaywallState(argsJson: string): string

/** Binding for `classifyReactivateError`. */
export declare function classifyReactivateError(argsJson: string): string

/** Binding for `coerceCustomerOptions`. */
export declare function coerceCustomerOptions(argsJson: string): string

/** Binding for `creditsToDisplayMinorUnits` (`null` when undefined). */
export declare function creditsToDisplayMinorUnits(argsJson: string): string

/** Binding for `decidePaywallOutcome`. */
export declare function decidePaywallOutcome(argsJson: string): string

/** Binding for `deriveIcons` — absent/empty branding → JSON `null`. */
export declare function deriveIcons(argsJson: string): string

/** Binding for `deriveTaxIdType`. */
export declare function deriveTaxIdType(argsJson: string): string

/** Binding for `evaluateCachedLimits`. */
export declare function evaluateCachedLimits(argsJson: string): string

/** Binding for `evaluateFreshLimits`. */
export declare function evaluateFreshLimits(argsJson: string): string

/** Binding for `extractBackendCustomerRef`. */
export declare function extractBackendCustomerRef(argsJson: string): string

/** Binding for `getBusinessCountryOptions`. */
export declare function getBusinessCountryOptions(argsJson: string): string

/** Binding for `getSellerTaxIdentifierDisplayLabel`. */
export declare function getSellerTaxIdentifierDisplayLabel(argsJson: string): string

/** Binding for `getTaxIdExample`. */
export declare function getTaxIdExample(argsJson: string): string

/** Binding for `getTaxIdFieldLabel`. */
export declare function getTaxIdFieldLabel(argsJson: string): string

/** Binding for `getTaxIdHelperText`. */
export declare function getTaxIdHelperText(argsJson: string): string

/** Binding for `isCachedCustomerRefValid`. */
export declare function isCachedCustomerRefValid(argsJson: string): string

/** Binding for `isEmailConflict`. */
export declare function isEmailConflict(argsJson: string): string

/** Binding for `isErrorResult`. */
export declare function isErrorResult(argsJson: string): string

/** Binding for `isZeroDecimalCurrency`. */
export declare function isZeroDecimalCurrency(argsJson: string): string

/** Binding for `makeResponseResult`. */
export declare function makeResponseResult(argsJson: string): string

/** Binding for `mapRouteError` (`kind`: `"solvapay"` | `"error"` | `"unknown"`). */
export declare function mapRouteError(argsJson: string): string

/** Binding for `MCP_TOOL_NAMES`. */
export declare function MCP_TOOL_NAMES(argsJson: string): string

/** Binding for `mcpViewMaps`. */
export declare function mcpViewMaps(argsJson: string): string

/** Binding for `minorUnitsPerMajor`. */
export declare function minorUnitsPerMajor(argsJson: string): string

/**
 * Returns the crate version string (`CARGO_PKG_VERSION`).
 *
 * Used as a hello-world smoke export proving the native addon loads.
 */
export declare function napiVersion(): string

/**
 * Binding for `normalizeCancelResponse`.
 *
 * Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**.
 */
export declare function normalizeCancelResponse(argsJson: string): string

/**
 * Binding for `normalizeReactivateResponse`.
 *
 * Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**.
 */
export declare function normalizeReactivateResponse(argsJson: string): string

/**
 * Binding for `paywallErrorToClientPayload`.
 *
 * Requires `message` + `structuredContent`; payload content comes from the gate
 * (message is unused for payload body — fixture-runner parity).
 */
export declare function paywallErrorToClientPayload(argsJson: string): string

/** Binding for `paywallToolResult` (also used by `McpAdapter.formatGate`). */
export declare function paywallToolResult(argsJson: string): string

/** Binding for `projectPaymentIntentResult`. */
export declare function projectPaymentIntentResult(argsJson: string): string

/** Binding for `projectTopupProcessOutcome`. */
export declare function projectTopupProcessOutcome(argsJson: string): string

/** Binding for `projectUsageSnapshot`. */
export declare function projectUsageSnapshot(argsJson: string): string

/**
 * Binding for `resolveCheckLimitsParams`.
 *
 * Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**.
 */
export declare function resolveCheckLimitsParams(argsJson: string): string

/** Binding for `resolveFallbackGateLimits`. */
export declare function resolveFallbackGateLimits(argsJson: string): string

/** Binding for `resolveProductRef`. */
export declare function resolveProductRef(argsJson: string): string

/** Binding for `resolvePurchaseCustomerRef`. */
export declare function resolvePurchaseCustomerRef(argsJson: string): string

/** Binding for `resolveReturnUrl`. */
export declare function resolveReturnUrl(argsJson: string): string

/** Binding for `resolveSellerIdentityDisplay`. */
export declare function resolveSellerIdentityDisplay(argsJson: string): string

/** Binding for `resolveTaxBehavior`. */
export declare function resolveTaxBehavior(argsJson: string): string

/**
 * Binding for `retryNextDelayMs`.
 *
 * Args: `{ maxRetries?, initialDelay?, backoffStrategy?, attempt }`.
 * Envelope value is delay milliseconds, or `null` when retries are exhausted.
 */
export declare function retryNextDelayMs(argsJson: string): string

/** Binding for `selectActivePurchases`. */
export declare function selectActivePurchases(argsJson: string): string

/** Binding for `SELLER_TAX_IDENTIFIER_DISPLAY_LABEL_BY_TYPE`. */
export declare function SELLER_TAX_IDENTIFIER_DISPLAY_LABEL_BY_TYPE(argsJson: string): string

/** Binding for `validateActivatePlanParams`. */
export declare function validateActivatePlanParams(argsJson: string): string

/** Binding for `validateAttachBusinessDetailsParams`. */
export declare function validateAttachBusinessDetailsParams(argsJson: string): string

/** Binding for `validateBusinessDetails`. */
export declare function validateBusinessDetails(argsJson: string): string

/** Binding for `validateCheckoutSessionParams`. */
export declare function validateCheckoutSessionParams(argsJson: string): string

/** Binding for `validateCreatePaymentIntentParams`. */
export declare function validateCreatePaymentIntentParams(argsJson: string): string

/** Binding for `validateGetProductParams`. */
export declare function validateGetProductParams(argsJson: string): string

/** Binding for `validateListPlansParams`. */
export declare function validateListPlansParams(argsJson: string): string

/** Binding for `validateProcessPaymentIntentParams`. */
export declare function validateProcessPaymentIntentParams(argsJson: string): string

/** Binding for `validatePublicBaseUrl` — invalid → error message string; valid → `null`. */
export declare function validatePublicBaseUrl(argsJson: string): string

/** Binding for `validatePurchaseRef`. */
export declare function validatePurchaseRef(argsJson: string): string

/** Binding for `validateTopupPaymentIntentParams`. */
export declare function validateTopupPaymentIntentParams(argsJson: string): string

/**
 * Verifies a SolvaPay webhook signature.
 *
 * Returns the parsed JSON body as a string on success. On failure throws a JS
 * `Error` whose `code` is the snake_case webhook error code (via napi
 * `Error.status` → JS `Error.code`).
 *
 * The clock is host-injected: the TypeScript facade passes
 * `Math.floor(Date.now() / 1000)` so a mocked host clock (fixtures, tests)
 * flows through deterministically. Omitting `nowUnixSecs` falls back to the
 * wall clock, keeping legacy three-argument native callers working.
 *
 * # Arguments
 *
 * * `body` - Raw request body string.
 * * `signature` - `SV-Signature` header value.
 * * `secret` - Webhook secret (`whsec_…`).
 * * `now_unix_secs` - Optional host clock as unix seconds; wall clock when omitted.
 */
export declare function verifyWebhook(
  body: string,
  signature: string,
  secret: string,
  nowUnixSecs?: number | undefined | null,
): string
