/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Returns the crate version string (`CARGO_PKG_VERSION`).
 *
 * Used as a hello-world smoke export proving the native addon loads.
 */
export declare function napiVersion(): string

/**
 * Verifies a SolvaPay webhook signature using the host wall clock.
 *
 * Returns the parsed JSON body as a string on success. On failure throws a JS
 * `Error` whose `code` is the snake_case webhook error code (via napi
 * `Error.status` → JS `Error.code`).
 *
 * # Arguments
 *
 * * `body` - Raw request body string.
 * * `signature` - `SV-Signature` header value.
 * * `secret` - Webhook secret (`whsec_…`).
 */
export declare function verifyWebhook(body: string, signature: string, secret: string): string
