/**
 * @generated by dto-gen (--ts-parity-out) — do not edit. Regenerate with: pnpm gen
 */
/** Signature-parity suite (§2.8) — presence, arity, sync matrix, defaults, errors. */

import { describe, expect, expectTypeOf, it, vi } from 'vitest'
import { SolvaPayError } from '@solvapay/core'
import {
  ANONYMOUS_CUSTOMER_REF,
  CUSTOMER_DEDUP_MAX_CACHE_SIZE,
  CUSTOMER_DEDUP_TTL_MS,
  PaywallError,
  REQUEST_ID_FORMAT,
  USAGE_ACTION_TYPE,
} from '../paywall'
import type { SolvaPayClient } from '../types/client'
import type { SolvaPayClientGenerated } from '../types/client.generated'
import * as nativeDecisions from '../native-decisions'
import { withRetry } from '../utils'

describe('signature-parity (generated)', () => {
  const expectedMaxRetries = 2
  const expectedInitialDelayMs = 500
  const expectedLimitsCacheTTLMs = 10000
  const expectedCustomerDedupTTLMs = 60000
  const expectedCustomerDedupMaxCacheSize = 1000
  const expectedAnonymousCustomerRef = 'anonymous'
  const expectedRequestIdFormat = 'solvapay_{epochMs}_{random9}'
  const expectedUsageActionType = 'api_call'

  describe('defaults', () => {
it('withRetry uses frozen retry defaults', async () => {
const seen: { maxRetries: number; initialDelay: number }[] = []
const spy = vi.spyOn(nativeDecisions, 'retryNextDelayMs').mockImplementation((opts) => {
seen.push({ maxRetries: opts.maxRetries, initialDelay: opts.initialDelay })
return null
})
await expect(withRetry(async () => {
throw new Error('retry-once')
})).rejects.toThrow('retry-once')
spy.mockRestore()
expect(seen[0]?.maxRetries).toBe(expectedMaxRetries)
expect(seen[0]?.initialDelay).toBe(expectedInitialDelayMs)
})
it('retryNextDelayMs saturates at the frozen maxRetries', () => {
expect(
nativeDecisions.retryNextDelayMs({
maxRetries: expectedMaxRetries,
initialDelay: expectedInitialDelayMs,
backoffStrategy: 'fixed',
attempt: 0,
}),
).toBe(expectedInitialDelayMs)
expect(
nativeDecisions.retryNextDelayMs({
maxRetries: expectedMaxRetries,
initialDelay: expectedInitialDelayMs,
backoffStrategy: 'fixed',
attempt: expectedMaxRetries,
}),
).toBeNull()
})
it('paywall cache TTL default matches the frozen limitsCacheTTLMs', async () => {
const { SolvaPayPaywall } = await import('../paywall')
const paywall = new SolvaPayPaywall({} as never)
expect(Reflect.get(paywall, 'limitsCacheTTL')).toBe(expectedLimitsCacheTTLMs)
})
it('customer-dedup and usage defaults match the contract', () => {
expect(CUSTOMER_DEDUP_TTL_MS).toBe(expectedCustomerDedupTTLMs)
expect(CUSTOMER_DEDUP_MAX_CACHE_SIZE).toBe(expectedCustomerDedupMaxCacheSize)
expect(ANONYMOUS_CUSTOMER_REF).toBe(expectedAnonymousCustomerRef)
expect(REQUEST_ID_FORMAT).toBe(expectedRequestIdFormat)
expect(USAGE_ACTION_TYPE).toBe(expectedUsageActionType)
})
})

  describe('error mapping', () => {
it('SolvaPayError preserves status/code', () => {
const err = new SolvaPayError('boom', { status: 400, code: 'bad_request' })
expect(err.status).toBe(400)
expect(err.code).toBe('bad_request')
})
it('PaywallError carries structuredContent', () => {
const err = new PaywallError('Payment required', {
kind: 'payment_required',
product: 'prd_x',
checkoutUrl: 'https://example.com/checkout',
message: 'Payment required',
shortMessage: 'Payment required',
})
expect(err.name).toBe('PaywallError')
expect(err.structuredContent.kind).toBe('payment_required')
})
})

  describe('client methods', () => {
    it('activatePlan presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['activatePlan']>().toEqualTypeOf<
SolvaPayClientGenerated['activatePlan']
>()
type P = Parameters<NonNullable<SolvaPayClient['activatePlan']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['activatePlan']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('assignCredits presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['assignCredits']>().toEqualTypeOf<
SolvaPayClientGenerated['assignCredits']
>()
type P = Parameters<NonNullable<SolvaPayClient['assignCredits']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['assignCredits']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('attachBusinessDetails presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['attachBusinessDetails']>().toEqualTypeOf<
SolvaPayClientGenerated['attachBusinessDetails']
>()
type P = Parameters<NonNullable<SolvaPayClient['attachBusinessDetails']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['attachBusinessDetails']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('bootstrapMcpProduct presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['bootstrapMcpProduct']>().toEqualTypeOf<
SolvaPayClientGenerated['bootstrapMcpProduct']
>()
type P = Parameters<NonNullable<SolvaPayClient['bootstrapMcpProduct']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['bootstrapMcpProduct']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('cancelPurchase presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['cancelPurchase']>().toEqualTypeOf<
SolvaPayClientGenerated['cancelPurchase']
>()
type P = Parameters<NonNullable<SolvaPayClient['cancelPurchase']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['cancelPurchase']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('checkLimits presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['checkLimits']>().toEqualTypeOf<
SolvaPayClientGenerated['checkLimits']
>()
type P = Parameters<NonNullable<SolvaPayClient['checkLimits']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['checkLimits']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('cloneProduct presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['cloneProduct']>().toEqualTypeOf<
SolvaPayClientGenerated['cloneProduct']
>()
type P = Parameters<NonNullable<SolvaPayClient['cloneProduct']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 2
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['cloneProduct']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('configureMcpPlans presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['configureMcpPlans']>().toEqualTypeOf<
SolvaPayClientGenerated['configureMcpPlans']
>()
type P = Parameters<NonNullable<SolvaPayClient['configureMcpPlans']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 2
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 2
      type R = ReturnType<NonNullable<SolvaPayClient['configureMcpPlans']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createCheckoutSession presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createCheckoutSession']>().toEqualTypeOf<
SolvaPayClientGenerated['createCheckoutSession']
>()
type P = Parameters<NonNullable<SolvaPayClient['createCheckoutSession']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createCheckoutSession']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createCustomer presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createCustomer']>().toEqualTypeOf<
SolvaPayClientGenerated['createCustomer']
>()
type P = Parameters<NonNullable<SolvaPayClient['createCustomer']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createCustomer']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createCustomerSession presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createCustomerSession']>().toEqualTypeOf<
SolvaPayClientGenerated['createCustomerSession']
>()
type P = Parameters<NonNullable<SolvaPayClient['createCustomerSession']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createCustomerSession']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createPaymentIntent presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createPaymentIntent']>().toEqualTypeOf<
SolvaPayClientGenerated['createPaymentIntent']
>()
type P = Parameters<NonNullable<SolvaPayClient['createPaymentIntent']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createPaymentIntent']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createPlan presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createPlan']>().toEqualTypeOf<
SolvaPayClientGenerated['createPlan']
>()
type P = Parameters<NonNullable<SolvaPayClient['createPlan']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createPlan']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createProduct presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createProduct']>().toEqualTypeOf<
SolvaPayClientGenerated['createProduct']
>()
type P = Parameters<NonNullable<SolvaPayClient['createProduct']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createProduct']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('createTopupPaymentIntent presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['createTopupPaymentIntent']>().toEqualTypeOf<
SolvaPayClientGenerated['createTopupPaymentIntent']
>()
type P = Parameters<NonNullable<SolvaPayClient['createTopupPaymentIntent']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['createTopupPaymentIntent']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('deletePlan presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['deletePlan']>().toEqualTypeOf<
SolvaPayClientGenerated['deletePlan']
>()
type P = Parameters<NonNullable<SolvaPayClient['deletePlan']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 2
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 2
      type R = ReturnType<NonNullable<SolvaPayClient['deletePlan']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('deleteProduct presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['deleteProduct']>().toEqualTypeOf<
SolvaPayClientGenerated['deleteProduct']
>()
type P = Parameters<NonNullable<SolvaPayClient['deleteProduct']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['deleteProduct']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('disableAutoRecharge presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['disableAutoRecharge']>().toEqualTypeOf<
SolvaPayClientGenerated['disableAutoRecharge']
>()
type P = Parameters<NonNullable<SolvaPayClient['disableAutoRecharge']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['disableAutoRecharge']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('fetchJwks presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['fetchJwks']>().toEqualTypeOf<
SolvaPayClientGenerated['fetchJwks']
>()
type P = Parameters<NonNullable<SolvaPayClient['fetchJwks']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['fetchJwks']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getAutoRecharge presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getAutoRecharge']>().toEqualTypeOf<
SolvaPayClientGenerated['getAutoRecharge']
>()
type P = Parameters<NonNullable<SolvaPayClient['getAutoRecharge']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['getAutoRecharge']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getCustomer presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getCustomer']>().toEqualTypeOf<
SolvaPayClientGenerated['getCustomer']
>()
type P = Parameters<NonNullable<SolvaPayClient['getCustomer']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['getCustomer']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getCustomerBalance presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getCustomerBalance']>().toEqualTypeOf<
SolvaPayClientGenerated['getCustomerBalance']
>()
type P = Parameters<NonNullable<SolvaPayClient['getCustomerBalance']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['getCustomerBalance']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getMerchant presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getMerchant']>().toEqualTypeOf<
SolvaPayClientGenerated['getMerchant']
>()
type P = Parameters<NonNullable<SolvaPayClient['getMerchant']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 0
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 0
      type R = ReturnType<NonNullable<SolvaPayClient['getMerchant']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getPaymentMethod presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getPaymentMethod']>().toEqualTypeOf<
SolvaPayClientGenerated['getPaymentMethod']
>()
type P = Parameters<NonNullable<SolvaPayClient['getPaymentMethod']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['getPaymentMethod']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getPlatformConfig presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getPlatformConfig']>().toEqualTypeOf<
SolvaPayClientGenerated['getPlatformConfig']
>()
type P = Parameters<NonNullable<SolvaPayClient['getPlatformConfig']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 0
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 0
      type R = ReturnType<NonNullable<SolvaPayClient['getPlatformConfig']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getProduct presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getProduct']>().toEqualTypeOf<
SolvaPayClientGenerated['getProduct']
>()
type P = Parameters<NonNullable<SolvaPayClient['getProduct']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['getProduct']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('getUserInfo presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['getUserInfo']>().toEqualTypeOf<
SolvaPayClientGenerated['getUserInfo']
>()
type P = Parameters<NonNullable<SolvaPayClient['getUserInfo']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['getUserInfo']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('listPlans presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['listPlans']>().toEqualTypeOf<
SolvaPayClientGenerated['listPlans']
>()
type P = Parameters<NonNullable<SolvaPayClient['listPlans']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['listPlans']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('listProducts presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['listProducts']>().toEqualTypeOf<
SolvaPayClientGenerated['listProducts']
>()
type P = Parameters<NonNullable<SolvaPayClient['listProducts']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 0
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 0
      type R = ReturnType<NonNullable<SolvaPayClient['listProducts']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('mcpBootstrap presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['mcpBootstrap']>().toEqualTypeOf<
SolvaPayClientGenerated['mcpBootstrap']
>()
type P = Parameters<NonNullable<SolvaPayClient['mcpBootstrap']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['mcpBootstrap']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('mcpCallBuiltinTool presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['mcpCallBuiltinTool']>().toEqualTypeOf<
SolvaPayClientGenerated['mcpCallBuiltinTool']
>()
type P = Parameters<NonNullable<SolvaPayClient['mcpCallBuiltinTool']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['mcpCallBuiltinTool']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('mcpDispatch presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['mcpDispatch']>().toEqualTypeOf<
SolvaPayClientGenerated['mcpDispatch']
>()
type P = Parameters<NonNullable<SolvaPayClient['mcpDispatch']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['mcpDispatch']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('mcpOauthRequest presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['mcpOauthRequest']>().toEqualTypeOf<
SolvaPayClientGenerated['mcpOauthRequest']
>()
type P = Parameters<NonNullable<SolvaPayClient['mcpOauthRequest']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['mcpOauthRequest']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('mcpReadResource presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['mcpReadResource']>().toEqualTypeOf<
SolvaPayClientGenerated['mcpReadResource']
>()
type P = Parameters<NonNullable<SolvaPayClient['mcpReadResource']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['mcpReadResource']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('mcpResolveAuth presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['mcpResolveAuth']>().toEqualTypeOf<
SolvaPayClientGenerated['mcpResolveAuth']
>()
type P = Parameters<NonNullable<SolvaPayClient['mcpResolveAuth']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['mcpResolveAuth']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('processPaymentIntent presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['processPaymentIntent']>().toEqualTypeOf<
SolvaPayClientGenerated['processPaymentIntent']
>()
type P = Parameters<NonNullable<SolvaPayClient['processPaymentIntent']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['processPaymentIntent']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('reactivatePurchase presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['reactivatePurchase']>().toEqualTypeOf<
SolvaPayClientGenerated['reactivatePurchase']
>()
type P = Parameters<NonNullable<SolvaPayClient['reactivatePurchase']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['reactivatePurchase']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('saveAutoRecharge presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['saveAutoRecharge']>().toEqualTypeOf<
SolvaPayClientGenerated['saveAutoRecharge']
>()
type P = Parameters<NonNullable<SolvaPayClient['saveAutoRecharge']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['saveAutoRecharge']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('trackUsage presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['trackUsage']>().toEqualTypeOf<
SolvaPayClientGenerated['trackUsage']
>()
type P = Parameters<NonNullable<SolvaPayClient['trackUsage']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['trackUsage']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('trackUsageBulk presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['trackUsageBulk']>().toEqualTypeOf<
SolvaPayClientGenerated['trackUsageBulk']
>()
type P = Parameters<NonNullable<SolvaPayClient['trackUsageBulk']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 1
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 1
      type R = ReturnType<NonNullable<SolvaPayClient['trackUsageBulk']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('updateCustomer presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['updateCustomer']>().toEqualTypeOf<
SolvaPayClientGenerated['updateCustomer']
>()
type P = Parameters<NonNullable<SolvaPayClient['updateCustomer']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 2
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 2
      type R = ReturnType<NonNullable<SolvaPayClient['updateCustomer']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('updatePlan presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['updatePlan']>().toEqualTypeOf<
SolvaPayClientGenerated['updatePlan']
>()
type P = Parameters<NonNullable<SolvaPayClient['updatePlan']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 3
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 3
      type R = ReturnType<NonNullable<SolvaPayClient['updatePlan']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
    it('updateProduct presence / arity / sync', () => {
expectTypeOf<SolvaPayClient['updateProduct']>().toEqualTypeOf<
SolvaPayClientGenerated['updateProduct']
>()
type P = Parameters<NonNullable<SolvaPayClient['updateProduct']>>
// IR param count (incl. optional). TS Parameters['length'] is a
// union when trailing params are optional — require IR arity ∈ that union.
type ExpectedArity = 2
type AssertArity = ExpectedArity extends P['length'] ? true : false
expectTypeOf<AssertArity>().toEqualTypeOf<true>()
// required param count (IR): 2
      type R = ReturnType<NonNullable<SolvaPayClient['updateProduct']>>
expectTypeOf<R>().toMatchTypeOf<Promise<unknown>>()
})
  })
})
