/* @generated by dto-gen — do not edit. Regenerate with --c-conformance-out. */

#ifndef SOLVAPAY_CONTRACT_HARNESS_H
#define SOLVAPAY_CONTRACT_HARNESS_H

#include <stddef.h>

/* Runs the golden-fixture census. Returns 0 on success. */
int contract_run_census(size_t want_parsed, size_t want_replayed);

#endif
