// @generated by dto-gen (--sync-dispatch-rs) — do not edit. Regenerate with: pnpm gen

fn dispatch_op(op: &str, args: &Value) -> Result<Value, SdkError> {
    match op {
        "mcpAuthGate" => {
            let input: AuthGateInput = parse_value(args)?;
            serde_json::to_value(mcp_auth_gate(&input))
                .map_err(|err| SdkError::transport(format!("serialize: {err}"), false))
        }
        "mcpConfigLog" => {
            let input: ConfigLogInput = parse_value(args)?;
            Ok(mcp_config_log(&input))
        }
        "mcpDcrDiagnostics" => {
            let input: DcrDiagnosticsInput = parse_value(args)?;
            Ok(mcp_dcr_diagnostics(&input))
        }
        "mcpDefaultGate" => {
            let input: DefaultGateInput = parse_value(args)?;
            serde_json::to_value(mcp_default_gate(&input.product, input.reason.as_deref()))
                .map_err(|err| SdkError::transport(format!("serialize: {err}"), false))
        }
        "mcpDescriptors" => {
            let input: McpDescriptorsInput = parse_value(args)?;
            match mcp_descriptors(&input) {
                Ok(value) => serde_json::to_value(value)
                    .map_err(|err| SdkError::transport(format!("serialize: {err}"), false)),
                Err(message) => Err(SdkError::transport(message, false)),
            }
        }
        "mcpHandleRequest" => {
            #[cfg(feature = "engine")]
            {
                let input: crate::engine::HandleRequestInput = parse_value(args)?;
                crate::engine::mcp_handle_request(&input)
                    .map_err(|message| SdkError::transport(message, false))
            }
            #[cfg(not(feature = "engine"))]
            {
                Err(SdkError::transport(
                    "mcpHandleRequest requires engine feature",
                    false,
                ))
            }
        }
        "mcpHideToolsByAudience" => {
            let input: HideToolsInput = parse_value(args)?;
            Ok(mcp_hide_tools_by_audience(&input))
        }
        "mcpIsFreeMethod" => {
            let method = args.get("mcpMethod").and_then(Value::as_str);
            Ok(Value::Bool(is_free_mcp_method(method)))
        }
        "mcpMergeCsp" => {
            let overrides = args
                .get("overrides")
                .cloned()
                .map(serde_json::from_value::<SolvaPayMcpCsp>)
                .transpose()
                .map_err(|err| SdkError::transport(format!("invalid overrides: {err}"), false))?;
            let api_base_url = args.get("apiBaseUrl").and_then(Value::as_str);
            serde_json::to_value(mcp_merge_csp(overrides.as_ref(), api_base_url))
                .map_err(|err| SdkError::transport(format!("serialize: {err}"), false))
        }
        "mcpNarrate" => {
            let input: NarrateInput = parse_value(args)?;
            Ok(mcp_narrate(&input))
        }
        "mcpNativeCors" => {
            let input: NativeCorsInput = parse_value(args)?;
            serde_json::to_value(mcp_native_cors(&input))
                .map_err(|err| SdkError::transport(format!("serialize: {err}"), false))
        }
        "mcpNormalizeOauthError" => {
            let body = args.get("body").cloned().unwrap_or(Value::Null);
            let text = args.get("text").and_then(Value::as_str).unwrap_or("");
            let status = args.get("status").and_then(Value::as_i64).unwrap_or(400);
            Ok(mcp_normalize_oauth_error(&body, text, status))
        }
        "mcpOauthDiscovery" => {
            let input: OauthDiscoveryInput = parse_value(args)?;
            Ok(mcp_oauth_discovery(&input))
        }
        "mcpOauthErrorInspect" => {
            let input: OauthErrorInspectInput = parse_value(args)?;
            Ok(mcp_oauth_error_inspect(&input))
        }
        "mcpOauthPath" => {
            let input: OauthPathInput = parse_value(args)?;
            Ok(mcp_oauth_path(&input))
        }
        "mcpOverviewResource" => serde_json::to_value(mcp_overview_resource())
            .map_err(|err| SdkError::transport(format!("serialize: {err}"), false)),
        "mcpRequiresBearerAuth" => {
            let method = args.get("mcpMethod").and_then(Value::as_str);
            let mode = args
                .get("authMode")
                .cloned()
                .map(serde_json::from_value::<McpAuthMode>)
                .transpose()
                .map_err(|err| SdkError::transport(format!("invalid authMode: {err}"), false))?
                .unwrap_or(McpAuthMode::All);
            Ok(Value::Bool(requires_bearer_auth(method, mode)))
        }
        "mcpResume" => {
            #[cfg(feature = "engine")]
            {
                let input: crate::engine::ResumeInput = parse_value(args)?;
                crate::engine::mcp_resume(&input)
                    .map_err(|message| SdkError::transport(message, false))
            }
            #[cfg(not(feature = "engine"))]
            {
                Err(SdkError::transport(
                    "mcpResume requires engine feature",
                    false,
                ))
            }
        }
        "mcpVerifyBearer" => {
            let input: VerifyBearerInput = parse_value(args)?;
            serde_json::to_value(mcp_verify_bearer(&input))
                .map_err(|err| SdkError::transport(format!("serialize: {err}"), false))
        }
        "mcpWidgetResource" => {
            #[cfg(feature = "engine")]
            {
                let input: crate::widget_resource::McpWidgetResourceInput = parse_value(args)?;
                crate::widget_resource::mcp_widget_resource(&input)
                    .map(|value| value.unwrap_or(Value::Null))
                    .map_err(|message| SdkError::transport(message, false))
            }
            #[cfg(not(feature = "engine"))]
            {
                Err(SdkError::transport(
                    "mcpWidgetResource requires engine feature",
                    false,
                ))
            }
        }
        "resolveCustomerRef" => {
            let pick = |key: &str| -> Option<String> {
                args.get(key)
                    .and_then(Value::as_str)
                    .map(str::to_owned)
                    .filter(|s| !s.is_empty())
            };
            Ok(Value::String(solvapay_core::resolve_customer_ref(
                pick("hookRef").as_deref(),
                pick("verifiedJwtSub").as_deref(),
                pick("headerUserId").as_deref(),
                pick("headerCustomerRef").as_deref(),
                pick("mcpExtraCustomerRef").as_deref(),
                pick("argsAuthCustomerRef").as_deref(),
                pick("argsCustomerRef").as_deref(),
            )))
        }
        "validateBusinessDetails" => {
            let input: BusinessDetailsInput = parse_value(args)?;
            serde_json::to_value(validate_business_details(&input))
                .map_err(|err| SdkError::transport(format!("serialize: {err}"), false))
        }
        other => Err(SdkError::transport(format!("unknown op: {other}"), false)),
    }
}
