//! @generated by dto-gen (--fixture-runner-out) — do not edit. Regenerate with: pnpm gen
//! Generated fixture-runner registry: wrap invoke bodies plus the registration table.
#![allow(missing_docs, clippy::missing_docs_in_private_items)]

#[allow(unused_imports)]
use serde_json::{Map, Value};
use solvapay_core::{
    attach_business_details_validation_error, billing_cycle, build_create_customer_params,
    build_gate_message, build_nudge_message, build_payable_tool_result, build_paywall_gate,
    charges, classify_cancel_error, classify_create_error, classify_customer_ref,
    classify_lookup_error, classify_paywall_state, classify_reactivate_error,
    coerce_customer_options, counts_usage, credits_per_unit_from_balance, decide_paywall_outcome,
    ensure_customer_next, evaluate_balance_observation, evaluate_cached_limits,
    evaluate_fresh_limits, extract_backend_customer_ref, format_price, format_subtotal_label,
    format_vat_summary_label, gate_next, get_business_country_options,
    get_seller_tax_identifier_display_label, headline_charges, included_units, invoke_payable_next,
    is_cached_customer_ref_valid, is_email_conflict, is_error_result, is_zero_decimal_currency,
    mcp_view_maps, meter_name, normalize_cancel_response, normalize_reactivate_response,
    paywall_client_payload, paywall_tool_result, pegged_credits_per_unit, per_unit_charge,
    project_topup_process_outcome, resolve_check_limits_params, resolve_customer_ref,
    resolve_fallback_gate_limits, resolve_product_ref, resolve_purchase_customer_ref,
    resolve_tax_treatment_note, reverse_charge_note, should_retry_usage_error, should_show_tax_row,
    tax_not_collected_note, tier_bands, tier_meters, to_major_units, topup_process_next,
    trial_days, usage_rate, validate_activate_plan_params, validate_attach_business_details_params,
    validate_checkout_session_params, validate_create_payment_intent_params,
    validate_get_product_params, validate_list_plans_params,
    validate_process_payment_intent_params, validate_purchase_ref,
    validate_topup_payment_intent_params, GateContent, PaywallGate, PaywallGateLimits,
    PaywallLimits, PaywallState, ResponseEnvelope,
};

#[allow(unused_imports)]
use crate::extract::*;
use crate::model::FixtureInput;
use crate::runner::{Binding, BindingError, BindingRegistry};

fn invoke_reverse_charge_note(input: &FixtureInput) -> Result<Value, BindingError> {
    let _args = args_map(input);
    Ok(Value::String(reverse_charge_note()))
}

fn invoke_tax_not_collected_note(input: &FixtureInput) -> Result<Value, BindingError> {
    let _args = args_map(input);
    Ok(Value::String(tax_not_collected_note()))
}

fn invoke_attach_business_details_validation_error(
    input: &FixtureInput,
) -> Result<Value, BindingError> {
    let args = args_map(input);
    let first_issue_message = optional_string(&args, "firstIssueMessage")?;
    to_value(&attach_business_details_validation_error(
        first_issue_message.as_deref(),
    ))
}

fn invoke_billing_cycle(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    to_value(&billing_cycle(priced.as_ref()))
}

fn invoke_build_create_customer_params(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let customer_ref = require_string(&args, "customerRef")?;
    let external_ref = optional_string(&args, "externalRef")?;
    let email = optional_string(&args, "email")?;
    let name = optional_string(&args, "name")?;
    let now_ms = require_clock_ms(input)?;
    to_value(&build_create_customer_params(
        &customer_ref,
        external_ref.as_deref(),
        email.as_deref(),
        name.as_deref(),
        now_ms,
    ))
}

fn invoke_build_gate_message(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let state = require_typed::<PaywallState>(&args, "state")?;
    let gate = require_typed::<GateContent>(&args, "gate")?;
    Ok(Value::String(build_gate_message(&state, &gate)))
}

fn invoke_build_nudge_message(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let state = require_typed::<PaywallState>(&args, "state")?;
    let limits = optional_typed::<PaywallLimits>(&args, "limits")?;
    Ok(Value::String(build_nudge_message(&state, limits.as_ref())))
}

fn invoke_build_payable_tool_result(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let envelope: ResponseEnvelope = require_typed(&args, "envelope")?;
    to_value(&build_payable_tool_result(&envelope))
}

fn invoke_build_paywall_gate(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let product_ref = require_string(&args, "productRef")?;
    let limits = require_typed::<PaywallGateLimits>(&args, "limits")?;
    to_value(&build_paywall_gate(&product_ref, &limits))
}

fn invoke_charges(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    to_value(&charges(priced.as_ref()))
}

fn invoke_classify_cancel_error(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    to_value(&classify_cancel_error(&message))
}

fn invoke_classify_create_error(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    to_value(&classify_create_error(&message))
}

fn invoke_classify_customer_ref(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let customer_ref = require_string(&args, "customerRef")?;
    to_value(&classify_customer_ref(&customer_ref))
}

fn invoke_classify_lookup_error(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    to_value(&classify_lookup_error(&message))
}

fn invoke_classify_paywall_state(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let limits = optional_typed::<PaywallLimits>(&args, "limits")?;
    to_value(&classify_paywall_state(limits.as_ref()))
}

fn invoke_classify_reactivate_error(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    to_value(&classify_reactivate_error(&message))
}

fn invoke_coerce_customer_options(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let email = optional_string(&args, "email")?;
    let name = optional_string(&args, "name")?;
    to_value(&coerce_customer_options(email.as_deref(), name.as_deref()))
}

fn invoke_counts_usage(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    Ok(Value::Bool(counts_usage(priced.as_ref())))
}

fn invoke_credits_per_unit_from_balance(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    let balance = optional_value(&args, "balance");
    let meter = optional_string(&args, "meter")?;
    to_value(&credits_per_unit_from_balance(
        priced.as_ref(),
        balance.as_ref(),
        meter.as_deref(),
    ))
}

fn invoke_decide_paywall_outcome(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let within_limits = require_bool(&args, "withinLimits")?;
    let product = require_string(&args, "product")?;
    let checkout_url = optional_string(&args, "checkoutUrl")?;
    let limits = optional_value(&args, "limits");
    to_value(&decide_paywall_outcome(
        within_limits,
        &product,
        limits.as_ref(),
        checkout_url.as_deref(),
    ))
}

fn invoke_ensure_customer_next(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let state = optional_value(&args, "state");
    let event = optional_value(&args, "event");
    result_as_value(ensure_customer_next(state.as_ref(), event.as_ref()))
}

fn invoke_evaluate_balance_observation(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let baseline = require_f64(&args, "baseline")?;
    let credits = require_f64(&args, "credits")?;
    to_value(&evaluate_balance_observation(baseline, credits))
}

fn invoke_evaluate_cached_limits(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let remaining = require_f64(&args, "remaining")?;
    to_value(&evaluate_cached_limits(remaining))
}

fn invoke_evaluate_fresh_limits(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let within_limits = require_bool(&args, "withinLimits")?;
    let remaining = require_f64(&args, "remaining")?;
    to_value(&evaluate_fresh_limits(within_limits, remaining))
}

fn invoke_extract_backend_customer_ref(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let response = require_object(&args, "response")?;
    let fallback = require_string(&args, "fallback")?;
    Ok(Value::String(extract_backend_customer_ref(
        response, &fallback,
    )))
}

fn invoke_format_price(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let amount_minor = require_f64(&args, "amountMinor")?;
    let currency = require_string(&args, "currency")?;
    let interval = optional_string(&args, "interval")?;
    let interval_count = optional_f64(&args, "intervalCount")?;
    let free = optional_string(&args, "free")?;
    let currency_display = optional_string(&args, "currencyDisplay")?;
    Ok(Value::String(format_price(
        amount_minor,
        &currency,
        interval.as_deref(),
        interval_count,
        free.as_deref(),
        currency_display.as_deref(),
    )))
}

fn invoke_format_subtotal_label(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let treatment = optional_string(&args, "treatment")?;
    Ok(Value::String(format_subtotal_label(treatment.as_deref())))
}

fn invoke_format_vat_summary_label(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let treatment = optional_string(&args, "treatment")?;
    let tax_rate = require_f64(&args, "taxRate")?;
    Ok(Value::String(format_vat_summary_label(
        treatment.as_deref(),
        tax_rate,
    )))
}

fn invoke_gate_next(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let state = optional_value(&args, "state");
    let event = optional_value(&args, "event");
    result_as_value(gate_next(state.as_ref(), event.as_ref()))
}

fn invoke_get_business_country_options(input: &FixtureInput) -> Result<Value, BindingError> {
    let _args = args_map(input);
    to_value(&get_business_country_options())
}

fn invoke_get_seller_tax_identifier_display_label(
    input: &FixtureInput,
) -> Result<Value, BindingError> {
    let args = args_map(input);
    let country = optional_string(&args, "country")?;
    Ok(Value::String(get_seller_tax_identifier_display_label(
        country.as_deref(),
    )))
}

fn invoke_headline_charges(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    to_value(&headline_charges(priced.as_ref()))
}

fn invoke_included_units(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    let meter = optional_string(&args, "meter")?;
    to_value(&included_units(priced.as_ref(), meter.as_deref()))
}

fn invoke_invoke_payable_next(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let state = optional_value(&args, "state");
    let event = optional_value(&args, "event");
    result_as_value(invoke_payable_next(state.as_ref(), event.as_ref()))
}

fn invoke_is_cached_customer_ref_valid(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let external_ref = optional_string(&args, "externalRef")?;
    let user_id = require_string(&args, "userId")?;
    let customer_ref = optional_string(&args, "customerRef")?;
    Ok(Value::Bool(is_cached_customer_ref_valid(
        external_ref.as_deref(),
        &user_id,
        customer_ref.as_deref(),
    )))
}

fn invoke_is_email_conflict(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    Ok(Value::Bool(is_email_conflict(&message)))
}

fn invoke_is_error_result(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let value = args.get("result").cloned().unwrap_or(Value::Null);
    Ok(Value::Bool(is_error_result(&value)))
}

fn invoke_is_zero_decimal_currency(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let currency = require_string(&args, "currency")?;
    Ok(Value::Bool(is_zero_decimal_currency(&currency)))
}

fn invoke_mcp_view_maps(input: &FixtureInput) -> Result<Value, BindingError> {
    let _args = args_map(input);
    to_value(&mcp_view_maps())
}

fn invoke_meter_name(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    to_value(&meter_name(priced.as_ref()))
}

fn invoke_normalize_cancel_response(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let response = args.get("response").cloned().unwrap_or(Value::Null);
    result_as_value(normalize_cancel_response(&response))
}

fn invoke_normalize_reactivate_response(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let response = args.get("response").cloned().unwrap_or(Value::Null);
    result_as_value(normalize_reactivate_response(&response))
}

fn invoke_paywall_error_to_client_payload(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let _message = require_string(&args, "message")?;
    let gate = require_typed::<PaywallGate>(&args, "structuredContent")?;
    to_value(&paywall_client_payload(&gate))
}

fn invoke_paywall_tool_result(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    let gate: PaywallGate = require_typed(&args, "structuredContent")?;
    to_value(&paywall_tool_result(&message, &gate))
}

fn invoke_pegged_credits_per_unit(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let charge_minor = require_f64(&args, "chargeMinor")?;
    let credits_per_minor_unit = require_f64(&args, "creditsPerMinorUnit")?;
    let usd_to_charge_rate = optional_f64(&args, "usdToChargeRate")?;
    to_value(&pegged_credits_per_unit(
        charge_minor,
        credits_per_minor_unit,
        usd_to_charge_rate,
    ))
}

fn invoke_per_unit_charge(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    let meter = optional_string(&args, "meter")?;
    to_value(&per_unit_charge(priced.as_ref(), meter.as_deref()))
}

fn invoke_project_topup_process_outcome(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let status = optional_string(&args, "status")?;
    let message = optional_string(&args, "message")?;
    to_value(&project_topup_process_outcome(
        status.as_deref(),
        message.as_deref(),
    ))
}

fn invoke_resolve_check_limits_params(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let product_ref = optional_string(&args, "productRef")?;
    let meter_name = optional_string(&args, "meterName")?;
    let usage_type = optional_string(&args, "usageType")?;
    result_as_value(resolve_check_limits_params(
        product_ref.as_deref(),
        meter_name.as_deref(),
        usage_type.as_deref(),
    ))
}

fn invoke_resolve_customer_ref(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let hook_ref = optional_string(&args, "hookRef")?;
    let verified_jwt_sub = optional_string(&args, "verifiedJwtSub")?;
    let header_user_id = optional_string(&args, "headerUserId")?;
    let header_customer_ref = optional_string(&args, "headerCustomerRef")?;
    let mcp_extra_customer_ref = optional_string(&args, "mcpExtraCustomerRef")?;
    let args_auth_customer_ref = optional_string(&args, "argsAuthCustomerRef")?;
    let args_customer_ref = optional_string(&args, "argsCustomerRef")?;
    Ok(Value::String(resolve_customer_ref(
        hook_ref.as_deref(),
        verified_jwt_sub.as_deref(),
        header_user_id.as_deref(),
        header_customer_ref.as_deref(),
        mcp_extra_customer_ref.as_deref(),
        args_auth_customer_ref.as_deref(),
        args_customer_ref.as_deref(),
    )))
}

fn invoke_resolve_fallback_gate_limits(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let checkout_url = optional_string(&args, "checkoutUrl")?;
    to_value(&resolve_fallback_gate_limits(checkout_url.as_deref()))
}

fn invoke_resolve_product_ref(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let metadata_product = optional_string(&args, "metadataProduct")?;
    let env_product = optional_string(&args, "envProduct")?;
    to_value(&resolve_product_ref(
        metadata_product.as_deref(),
        env_product.as_deref(),
    ))
}

fn invoke_resolve_purchase_customer_ref(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let customer_ref = optional_string(&args, "customerRef")?;
    let user_id = require_string(&args, "userId")?;
    Ok(Value::String(resolve_purchase_customer_ref(
        customer_ref.as_deref(),
        &user_id,
    )))
}

fn invoke_resolve_tax_treatment_note(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let treatment = optional_string(&args, "treatment")?;
    to_value(&resolve_tax_treatment_note(treatment.as_deref()))
}

fn invoke_should_retry_usage_error(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let message = require_string(&args, "message")?;
    Ok(Value::Bool(should_retry_usage_error(&message)))
}

fn invoke_should_show_tax_row(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let treatment = optional_string(&args, "treatment")?;
    Ok(Value::Bool(should_show_tax_row(treatment.as_deref())))
}

fn invoke_tier_bands(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    let meter = optional_string(&args, "meter")?;
    to_value(&tier_bands(priced.as_ref(), meter.as_deref()))
}

fn invoke_tier_meters(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    to_value(&tier_meters(priced.as_ref()))
}

fn invoke_to_major_units(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let amount_minor = require_f64(&args, "amountMinor")?;
    let currency = require_string(&args, "currency")?;
    to_value(&to_major_units(amount_minor, &currency))
}

fn invoke_topup_process_next(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let state = optional_value(&args, "state");
    let event = optional_value(&args, "event");
    result_as_value(topup_process_next(state.as_ref(), event.as_ref()))
}

fn invoke_trial_days(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    to_value(&trial_days(priced.as_ref()))
}

fn invoke_usage_rate(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let priced = optional_value(&args, "priced");
    let meter = optional_string(&args, "meter")?;
    to_value(&usage_rate(priced.as_ref(), meter.as_deref()))
}

fn invoke_validate_activate_plan_params(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let product_ref = optional_string(&args, "productRef")?;
    let plan_ref = optional_string(&args, "planRef")?;
    option_helper_err(validate_activate_plan_params(
        product_ref.as_deref(),
        plan_ref.as_deref(),
    ))
}

fn invoke_validate_attach_business_details_params(
    input: &FixtureInput,
) -> Result<Value, BindingError> {
    let args = args_map(input);
    let payment_intent_id = optional_string(&args, "paymentIntentId")?;
    option_helper_err(validate_attach_business_details_params(
        payment_intent_id.as_deref(),
    ))
}

fn invoke_validate_checkout_session_params(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let product_ref = optional_string(&args, "productRef")?;
    option_helper_err(validate_checkout_session_params(product_ref.as_deref()))
}

fn invoke_validate_create_payment_intent_params(
    input: &FixtureInput,
) -> Result<Value, BindingError> {
    let args = args_map(input);
    let plan_ref = optional_string(&args, "planRef")?;
    let product_ref = optional_string(&args, "productRef")?;
    option_helper_err(validate_create_payment_intent_params(
        plan_ref.as_deref(),
        product_ref.as_deref(),
    ))
}

fn invoke_validate_get_product_params(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let product_ref = optional_string(&args, "productRef")?;
    option_helper_err(validate_get_product_params(product_ref.as_deref()))
}

fn invoke_validate_list_plans_params(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let product_ref = optional_string(&args, "productRef")?;
    option_helper_err(validate_list_plans_params(product_ref.as_deref()))
}

fn invoke_validate_process_payment_intent_params(
    input: &FixtureInput,
) -> Result<Value, BindingError> {
    let args = args_map(input);
    let payment_intent_id = optional_string(&args, "paymentIntentId")?;
    let product_ref = optional_string(&args, "productRef")?;
    option_helper_err(validate_process_payment_intent_params(
        payment_intent_id.as_deref(),
        product_ref.as_deref(),
    ))
}

fn invoke_validate_purchase_ref(input: &FixtureInput) -> Result<Value, BindingError> {
    let args = args_map(input);
    let purchase_ref = optional_string(&args, "purchaseRef")?;
    option_helper_err(validate_purchase_ref(purchase_ref.as_deref()))
}

fn invoke_validate_topup_payment_intent_params(
    input: &FixtureInput,
) -> Result<Value, BindingError> {
    let args = args_map(input);
    let amount = optional_f64(&args, "amount")?;
    let currency = optional_string(&args, "currency")?;
    option_helper_err(validate_topup_payment_intent_params(
        amount,
        currency.as_deref(),
    ))
}

/// Builds the default [`BindingRegistry`] from generated wrap bodies plus chrome-routed hand-written helpers.
pub fn create_default_registry() -> BindingRegistry {
    let mut registry = BindingRegistry::new();

    registry.register(
        "validateBusinessDetails",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_validate_business_details),
        },
    );
    registry.register(
        "deriveTaxIdType",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_derive_tax_id_type),
        },
    );
    registry.register(
        "resolveTaxBehavior",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_resolve_tax_behavior),
        },
    );
    registry.register(
        "getTaxIdExample",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_get_tax_id_example),
        },
    );
    registry.register(
        "getTaxIdFieldLabel",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_get_tax_id_field_label),
        },
    );
    registry.register(
        "getTaxIdHelperText",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_get_tax_id_helper_text),
        },
    );
    registry.register(
        "getBusinessCountryOptions",
        Binding {
            id: "core",
            invoke: Box::new(invoke_get_business_country_options),
        },
    );
    registry.register(
        "minorUnitsPerMajor",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_minor_units_per_major),
        },
    );
    registry.register(
        "isZeroDecimalCurrency",
        Binding {
            id: "core",
            invoke: Box::new(invoke_is_zero_decimal_currency),
        },
    );
    registry.register(
        "creditsToDisplayMinorUnits",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_credits_to_display_minor_units),
        },
    );
    registry.register(
        "SELLER_TAX_IDENTIFIER_DISPLAY_LABEL_BY_TYPE",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_seller_tax_identifier_display_label_by_type),
        },
    );
    registry.register(
        "getSellerTaxIdentifierDisplayLabel",
        Binding {
            id: "core",
            invoke: Box::new(invoke_get_seller_tax_identifier_display_label),
        },
    );
    registry.register(
        "resolveSellerIdentityDisplay",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::invoke_resolve_seller_identity_display),
        },
    );
    registry.register(
        "withRetry",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::retry::invoke_with_retry),
        },
    );
    registry.register(
        "pollBalanceUntilIncreased",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::balance_poll::invoke_poll_balance_until_increased),
        },
    );
    registry.register(
        "TOPUP_BALANCE_POLL_DELAYS_MS",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::balance_poll::invoke_topup_delays),
        },
    );
    registry.register(
        "BALANCE_RECONCILE_DELAYS_MS",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::balance_poll::invoke_reconcile_delays),
        },
    );
    registry.register(
        "verifyWebhook",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::webhook::invoke_verify_webhook),
        },
    );
    registry.register(
        "constructSdkError",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::error_model::invoke_construct_sdk_error),
        },
    );
    registry.register(
        "classifyPaywallState",
        Binding {
            id: "core",
            invoke: Box::new(invoke_classify_paywall_state),
        },
    );
    registry.register(
        "buildGateMessage",
        Binding {
            id: "core",
            invoke: Box::new(invoke_build_gate_message),
        },
    );
    registry.register(
        "buildNudgeMessage",
        Binding {
            id: "core",
            invoke: Box::new(invoke_build_nudge_message),
        },
    );
    registry.register(
        "buildPaywallGate",
        Binding {
            id: "core",
            invoke: Box::new(invoke_build_paywall_gate),
        },
    );
    registry.register(
        "paywallErrorToClientPayload",
        Binding {
            id: "core",
            invoke: Box::new(invoke_paywall_error_to_client_payload),
        },
    );
    registry.register(
        "paywallToolResult",
        Binding {
            id: "core",
            invoke: Box::new(invoke_paywall_tool_result),
        },
    );
    registry.register(
        "makeResponseResult",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::mcp_payload::invoke_make_response_result),
        },
    );
    registry.register(
        "assertResponseResult",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::mcp_payload::invoke_assert_response_result),
        },
    );
    registry.register(
        "MCP_TOOL_NAMES",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::mcp_descriptors::invoke_mcp_tool_names),
        },
    );
    registry.register(
        "mcpViewMaps",
        Binding {
            id: "core",
            invoke: Box::new(invoke_mcp_view_maps),
        },
    );
    registry.register(
        "deriveIcons",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::mcp_descriptors::invoke_derive_icons),
        },
    );
    registry.register(
        "buildToolDescriptorMetadata",
        Binding {
            id: "core",
            invoke: Box::new(
                crate::bindings::mcp_descriptors::invoke_build_tool_descriptor_metadata,
            ),
        },
    );
    registry.register(
        "buildPromptDescriptorMetadata",
        Binding {
            id: "core",
            invoke: Box::new(
                crate::bindings::mcp_descriptors::invoke_build_prompt_descriptor_metadata,
            ),
        },
    );
    registry.register(
        "buildPromptUserMessage",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::mcp_descriptors::invoke_build_prompt_user_message),
        },
    );
    registry.register(
        "validatePublicBaseUrl",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::mcp_descriptors::invoke_validate_public_base_url),
        },
    );
    registry.register(
        "resolveAuthenticatedUser",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_resolve_authenticated_user),
        },
    );
    registry.register(
        "classifyCustomerRef",
        Binding {
            id: "core",
            invoke: Box::new(invoke_classify_customer_ref),
        },
    );
    registry.register(
        "coerceCustomerOptions",
        Binding {
            id: "core",
            invoke: Box::new(invoke_coerce_customer_options),
        },
    );
    registry.register(
        "buildCreateCustomerParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_build_create_customer_params),
        },
    );
    registry.register(
        "extractBackendCustomerRef",
        Binding {
            id: "core",
            invoke: Box::new(invoke_extract_backend_customer_ref),
        },
    );
    registry.register(
        "classifyLookupError",
        Binding {
            id: "core",
            invoke: Box::new(invoke_classify_lookup_error),
        },
    );
    registry.register(
        "classifyCreateError",
        Binding {
            id: "core",
            invoke: Box::new(invoke_classify_create_error),
        },
    );
    registry.register(
        "isEmailConflict",
        Binding {
            id: "core",
            invoke: Box::new(invoke_is_email_conflict),
        },
    );
    registry.register(
        "validateActivatePlanParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_activate_plan_params),
        },
    );
    registry.register(
        "validateCreatePaymentIntentParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_create_payment_intent_params),
        },
    );
    registry.register(
        "validateTopupPaymentIntentParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_topup_payment_intent_params),
        },
    );
    registry.register(
        "validateProcessPaymentIntentParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_process_payment_intent_params),
        },
    );
    registry.register(
        "validateAttachBusinessDetailsParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_attach_business_details_params),
        },
    );
    registry.register(
        "attachBusinessDetailsValidationError",
        Binding {
            id: "core",
            invoke: Box::new(invoke_attach_business_details_validation_error),
        },
    );
    registry.register(
        "projectPaymentIntentResult",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_project_payment_intent_result),
        },
    );
    registry.register(
        "projectTopupProcessOutcome",
        Binding {
            id: "core",
            invoke: Box::new(invoke_project_topup_process_outcome),
        },
    );
    registry.register(
        "validateCheckoutSessionParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_checkout_session_params),
        },
    );
    registry.register(
        "resolveReturnUrl",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_resolve_return_url),
        },
    );
    registry.register(
        "selectActivePurchases",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_select_active_purchases),
        },
    );
    registry.register(
        "isCachedCustomerRefValid",
        Binding {
            id: "core",
            invoke: Box::new(invoke_is_cached_customer_ref_valid),
        },
    );
    registry.register(
        "resolveCustomerRef",
        Binding {
            id: "core",
            invoke: Box::new(invoke_resolve_customer_ref),
        },
    );
    registry.register(
        "resolvePurchaseCustomerRef",
        Binding {
            id: "core",
            invoke: Box::new(invoke_resolve_purchase_customer_ref),
        },
    );
    registry.register(
        "validatePurchaseRef",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_purchase_ref),
        },
    );
    registry.register(
        "normalizeCancelResponse",
        Binding {
            id: "core",
            invoke: Box::new(invoke_normalize_cancel_response),
        },
    );
    registry.register(
        "normalizeReactivateResponse",
        Binding {
            id: "core",
            invoke: Box::new(invoke_normalize_reactivate_response),
        },
    );
    registry.register(
        "classifyCancelError",
        Binding {
            id: "core",
            invoke: Box::new(invoke_classify_cancel_error),
        },
    );
    registry.register(
        "classifyReactivateError",
        Binding {
            id: "core",
            invoke: Box::new(invoke_classify_reactivate_error),
        },
    );
    registry.register(
        "projectUsageSnapshot",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_project_usage_snapshot),
        },
    );
    registry.register(
        "resolveCheckLimitsParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_resolve_check_limits_params),
        },
    );
    registry.register(
        "validateListPlansParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_list_plans_params),
        },
    );
    registry.register(
        "charges",
        Binding {
            id: "core",
            invoke: Box::new(invoke_charges),
        },
    );
    registry.register(
        "headlineCharges",
        Binding {
            id: "core",
            invoke: Box::new(invoke_headline_charges),
        },
    );
    registry.register(
        "perUnitCharge",
        Binding {
            id: "core",
            invoke: Box::new(invoke_per_unit_charge),
        },
    );
    registry.register(
        "tierBands",
        Binding {
            id: "core",
            invoke: Box::new(invoke_tier_bands),
        },
    );
    registry.register(
        "tierMeters",
        Binding {
            id: "core",
            invoke: Box::new(invoke_tier_meters),
        },
    );
    registry.register(
        "usageRate",
        Binding {
            id: "core",
            invoke: Box::new(invoke_usage_rate),
        },
    );
    registry.register(
        "billingCycle",
        Binding {
            id: "core",
            invoke: Box::new(invoke_billing_cycle),
        },
    );
    registry.register(
        "trialDays",
        Binding {
            id: "core",
            invoke: Box::new(invoke_trial_days),
        },
    );
    registry.register(
        "includedUnits",
        Binding {
            id: "core",
            invoke: Box::new(invoke_included_units),
        },
    );
    registry.register(
        "meterName",
        Binding {
            id: "core",
            invoke: Box::new(invoke_meter_name),
        },
    );
    registry.register(
        "countsUsage",
        Binding {
            id: "core",
            invoke: Box::new(invoke_counts_usage),
        },
    );
    registry.register(
        "peggedCreditsPerUnit",
        Binding {
            id: "core",
            invoke: Box::new(invoke_pegged_credits_per_unit),
        },
    );
    registry.register(
        "creditsPerUnitFromBalance",
        Binding {
            id: "core",
            invoke: Box::new(invoke_credits_per_unit_from_balance),
        },
    );
    registry.register(
        "mapRouteError",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_map_route_error),
        },
    );
    registry.register(
        "isErrorResult",
        Binding {
            id: "core",
            invoke: Box::new(invoke_is_error_result),
        },
    );
    registry.register(
        "validateGetProductParams",
        Binding {
            id: "core",
            invoke: Box::new(invoke_validate_get_product_params),
        },
    );
    registry.register(
        "resolveProductRef",
        Binding {
            id: "core",
            invoke: Box::new(invoke_resolve_product_ref),
        },
    );
    registry.register(
        "requireProductRef",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_require_product_ref),
        },
    );
    registry.register(
        "evaluateProductReadiness",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_evaluate_product_readiness),
        },
    );
    registry.register(
        "assertValidProductRef",
        Binding {
            id: "core",
            invoke: Box::new(crate::bindings::helpers::invoke_assert_valid_product_ref),
        },
    );
    registry.register(
        "evaluateCachedLimits",
        Binding {
            id: "core",
            invoke: Box::new(invoke_evaluate_cached_limits),
        },
    );
    registry.register(
        "evaluateFreshLimits",
        Binding {
            id: "core",
            invoke: Box::new(invoke_evaluate_fresh_limits),
        },
    );
    registry.register(
        "decidePaywallOutcome",
        Binding {
            id: "core",
            invoke: Box::new(invoke_decide_paywall_outcome),
        },
    );
    registry.register(
        "REVERSE_CHARGE_NOTE",
        Binding {
            id: "core",
            invoke: Box::new(invoke_reverse_charge_note),
        },
    );
    registry.register(
        "TAX_NOT_COLLECTED_NOTE",
        Binding {
            id: "core",
            invoke: Box::new(invoke_tax_not_collected_note),
        },
    );
    registry.register(
        "buildPayableToolResult",
        Binding {
            id: "core",
            invoke: Box::new(invoke_build_payable_tool_result),
        },
    );
    registry.register(
        "ensureCustomerNext",
        Binding {
            id: "core",
            invoke: Box::new(invoke_ensure_customer_next),
        },
    );
    registry.register(
        "evaluateBalanceObservation",
        Binding {
            id: "core",
            invoke: Box::new(invoke_evaluate_balance_observation),
        },
    );
    registry.register(
        "formatPrice",
        Binding {
            id: "core",
            invoke: Box::new(invoke_format_price),
        },
    );
    registry.register(
        "formatSubtotalLabel",
        Binding {
            id: "core",
            invoke: Box::new(invoke_format_subtotal_label),
        },
    );
    registry.register(
        "formatVatSummaryLabel",
        Binding {
            id: "core",
            invoke: Box::new(invoke_format_vat_summary_label),
        },
    );
    registry.register(
        "gateNext",
        Binding {
            id: "core",
            invoke: Box::new(invoke_gate_next),
        },
    );
    registry.register(
        "invokePayableNext",
        Binding {
            id: "core",
            invoke: Box::new(invoke_invoke_payable_next),
        },
    );
    registry.register(
        "resolveFallbackGateLimits",
        Binding {
            id: "core",
            invoke: Box::new(invoke_resolve_fallback_gate_limits),
        },
    );
    registry.register(
        "resolveTaxTreatmentNote",
        Binding {
            id: "core",
            invoke: Box::new(invoke_resolve_tax_treatment_note),
        },
    );
    registry.register(
        "shouldRetryUsageError",
        Binding {
            id: "core",
            invoke: Box::new(invoke_should_retry_usage_error),
        },
    );
    registry.register(
        "shouldShowTaxRow",
        Binding {
            id: "core",
            invoke: Box::new(invoke_should_show_tax_row),
        },
    );
    registry.register(
        "toMajorUnits",
        Binding {
            id: "core",
            invoke: Box::new(invoke_to_major_units),
        },
    );
    registry.register(
        "topupProcessNext",
        Binding {
            id: "core",
            invoke: Box::new(invoke_topup_process_next),
        },
    );

    registry
}
