#!/usr/bin/env node
/**
 * Build edge + browser wasm-bindgen artifacts, run pinned wasm-opt -Oz,
 * and copy into pkg/ atomically. The browser-js profile is the same
 * `--features browser` crate compiled to MVP WASM and converted with
 * wasm2js for hosts that forbid WebAssembly. With --check-drift, fail
 * if committed artifacts differ from a fresh rebuild.
 */
import { spawnSync } from 'node:child_process'
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const rustRoot = resolve(pkgRoot, '../..')
const checkDrift = process.argv.includes('--check-drift')

const require = createRequire(import.meta.url)
const binaryenPkg = dirname(require.resolve('binaryen/package.json'))
const wasmOpt = join(binaryenPkg, 'bin', 'wasm-opt')
const wasm2js = join(binaryenPkg, 'bin', 'wasm2js')

// rustc 1.96 + wasm-bindgen 0.2.126 still emit reference-types / a second
// table unless std is rebuilt (`-Zbuild-std`) against these flags. RUSTFLAGS
// alone is not enough; disabling reference-types without rebuilding std
// makes wasm-bindgen fail looking for clone_ref intrinsics.
const MVP_RUSTFLAGS =
  '-Ctarget-cpu=mvp -Ctarget-feature=-reference-types,-multivalue,-bulk-memory,-bulk-memory-opt,-sign-ext,-nontrapping-fptoint,-call-indirect-overlong'
const MVP_PRE_BINDGEN_OPT = [
  '--enable-bulk-memory',
  '--enable-bulk-memory-opt',
  '--enable-sign-ext',
  '--enable-nontrapping-float-to-int',
  '--llvm-memory-copy-fill-lowering',
  '--signext-lowering',
  '--strip-target-features',
]
const WASM2JS_SHIM = `/* @generated by wasm-bindgen 0.2.126 + wasm2js -Oz (Binaryen 131.0.0) — do not edit */
import * as glue from './solvapay_wasm_bg.js'
import * as core from './solvapay_wasm2js.js'
glue.__wbg_set_wasm(core)
core.__wbindgen_start?.()
export * from './solvapay_wasm_bg.js'
`

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    stdio: 'inherit',
    cwd: opts.cwd ?? rustRoot,
    env: opts.env ?? process.env,
  })
  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

function which(bin) {
  const result = spawnSync(process.platform === 'win32' ? 'where' : 'which', [bin], {
    encoding: 'utf8',
  })
  return result.status === 0 ? result.stdout.trim().split('\n')[0] : null
}

function cargoTargetDir() {
  if (process.env.CARGO_TARGET_DIR) {
    return resolve(process.env.CARGO_TARGET_DIR)
  }
  const meta = spawnSync(
    'cargo',
    ['metadata', '--format-version', '1', '--no-deps'],
    { cwd: rustRoot, encoding: 'utf8' },
  )
  if (meta.status === 0) {
    const parsed = JSON.parse(meta.stdout)
    if (typeof parsed.target_directory === 'string') {
      return parsed.target_directory
    }
  }
  return join(rustRoot, 'target')
}

const wasmBindgen = which('wasm-bindgen')
if (!wasmBindgen) {
  console.error('wasm-bindgen CLI not found; install wasm-bindgen-cli 0.2.126')
  process.exit(1)
}

if (!existsSync(wasmOpt)) {
  console.error(`wasm-opt not found at ${wasmOpt}; run pnpm install in bindings/wasm`)
  process.exit(1)
}

if (!existsSync(wasm2js)) {
  console.error(`wasm2js not found at ${wasm2js}; run pnpm install in bindings/wasm`)
  process.exit(1)
}

const profiles = [
  { feature: 'edge', outName: 'edge', bindgenTarget: 'web' },
  { feature: 'browser', outName: 'browser', bindgenTarget: 'web' },
  {
    feature: 'browser',
    outName: 'browser-js',
    bindgenTarget: 'bundler',
    rustflags: MVP_RUSTFLAGS,
    buildStd: true,
    preBindgenOpt: MVP_PRE_BINDGEN_OPT,
    emitWasm2js: true,
  },
]

const staging = mkdtempSync(join(tmpdir(), 'solvapay-wasm-'))
try {
  for (const profile of profiles) {
    const {
      feature,
      outName,
      bindgenTarget,
      rustflags,
      wasmOptExtra,
      emitWasm2js,
      buildStd,
      preBindgenOpt,
    } = profile
    console.log(`\n=== building profile ${outName} (${feature}) ===`)
    const env = {
      ...process.env,
      ...(rustflags ? { RUSTFLAGS: rustflags } : {}),
      ...(buildStd ? { RUSTC_BOOTSTRAP: '1' } : {}),
    }
    run(
      'cargo',
      [
        'build',
        '-p',
        'solvapay-wasm',
        '--target',
        'wasm32-unknown-unknown',
        '--profile',
        'wasm-release',
        '--no-default-features',
        '--features',
        feature,
        ...(buildStd ? ['-Zbuild-std=std,panic_abort'] : []),
      ],
      { env },
    )

    const cargoWasm = join(
      cargoTargetDir(),
      'wasm32-unknown-unknown/wasm-release/solvapay_wasm.wasm',
    )
    const bindgenOut = join(staging, `${outName}-bindgen`)
    mkdirSync(bindgenOut, { recursive: true })
    let wasmIn = cargoWasm
    if (preBindgenOpt) {
      const lowered = join(bindgenOut, 'solvapay_wasm.mvp.wasm')
      run(wasmOpt, [...preBindgenOpt, cargoWasm, '-o', lowered])
      wasmIn = lowered
    }
    run(wasmBindgen, [
      wasmIn,
      '--target',
      bindgenTarget,
      '--out-dir',
      bindgenOut,
      '--out-name',
      'solvapay_wasm',
    ])
    if (preBindgenOpt) {
      rmSync(wasmIn, { force: true })
    }

    const bgWasm = join(bindgenOut, 'solvapay_wasm_bg.wasm')
    const optimized = join(bindgenOut, 'solvapay_wasm_bg.opt.wasm')
    run(wasmOpt, [bgWasm, '-Oz', ...(wasmOptExtra ?? []), '-o', optimized])
    // Atomic replace within the staging dir.
    copyFileSync(optimized, bgWasm)
    rmSync(optimized, { force: true })

    if (emitWasm2js) {
      const jsOut = join(bindgenOut, 'solvapay_wasm2js.js')
      run(wasm2js, [bgWasm, '-Oz', '-o', jsOut])
      writeFileSync(join(bindgenOut, 'solvapay_wasm.js'), WASM2JS_SHIM)
      rmSync(bgWasm, { force: true })
    }

    // Mark generated glue (web target writes solvapay_wasm.js; bundler
    // writes solvapay_wasm_bg.js as the function surface).
    for (const glueName of ['solvapay_wasm.js', 'solvapay_wasm_bg.js', 'solvapay_wasm2js.js']) {
      const glue = join(bindgenOut, glueName)
      if (!existsSync(glue)) continue
      const glueSrc = readFileSync(glue, 'utf8')
      if (!glueSrc.startsWith('/* @generated')) {
        writeFileSync(
          glue,
          `/* @generated by wasm-bindgen 0.2.126 + wasm-opt -Oz (Binaryen 131.0.0) — do not edit */\n${glueSrc}`,
        )
      }
    }

    const dest = join(staging, outName)
    mkdirSync(dest, { recursive: true })
    for (const name of readdirSync(bindgenOut)) {
      copyFileSync(join(bindgenOut, name), join(dest, name))
    }
  }

  const pkgDir = join(pkgRoot, 'pkg')
  if (checkDrift) {
    for (const { outName } of profiles) {
      const expectedDir = join(pkgDir, outName)
      const actualDir = join(staging, outName)
      if (!existsSync(expectedDir)) {
        console.error(`missing committed artifacts: ${expectedDir}`)
        process.exit(1)
      }
      const names = new Set([
        ...readdirSync(expectedDir),
        ...readdirSync(actualDir),
      ])
      for (const name of names) {
        const a = join(expectedDir, name)
        const b = join(actualDir, name)
        if (!existsSync(a) || !existsSync(b)) {
          console.error(`artifact drift: ${outName}/${name} presence mismatch`)
          process.exit(1)
        }
        const left = readFileSync(a)
        const right = readFileSync(b)
        if (!left.equals(right)) {
          console.error(`artifact drift: ${outName}/${name} content differs`)
          process.exit(1)
        }
      }
    }
    console.log('OK: wasm artifacts match committed pkg/')
  } else {
    rmSync(pkgDir, { recursive: true, force: true })
    mkdirSync(pkgDir, { recursive: true })
    for (const { outName } of profiles) {
      cpSync(join(staging, outName), join(pkgDir, outName), { recursive: true })
    }
    console.log(`Wrote ${pkgDir}/{edge,browser,browser-js}`)
  }
} finally {
  rmSync(staging, { recursive: true, force: true })
}
