#!/usr/bin/env node
/**
 * Build edge + browser wasm-bindgen artifacts, run pinned wasm-opt -Oz,
 * and copy into pkg/ atomically. With --check-drift, fail if committed
 * artifacts differ from a fresh rebuild.
 */
import { spawnSync } from 'node:child_process'
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const rustRoot = resolve(pkgRoot, '../..')
const checkDrift = process.argv.includes('--check-drift')

const require = createRequire(import.meta.url)
const binaryenPkg = dirname(require.resolve('binaryen/package.json'))
const wasmOpt = join(binaryenPkg, 'bin', 'wasm-opt')

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    stdio: 'inherit',
    cwd: opts.cwd ?? rustRoot,
    env: process.env,
  })
  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

function which(bin) {
  const result = spawnSync(process.platform === 'win32' ? 'where' : 'which', [bin], {
    encoding: 'utf8',
  })
  return result.status === 0 ? result.stdout.trim().split('\n')[0] : null
}

function cargoTargetDir() {
  if (process.env.CARGO_TARGET_DIR) {
    return resolve(process.env.CARGO_TARGET_DIR)
  }
  const meta = spawnSync(
    'cargo',
    ['metadata', '--format-version', '1', '--no-deps'],
    { cwd: rustRoot, encoding: 'utf8' },
  )
  if (meta.status === 0) {
    const parsed = JSON.parse(meta.stdout)
    if (typeof parsed.target_directory === 'string') {
      return parsed.target_directory
    }
  }
  return join(rustRoot, 'target')
}

const wasmBindgen = which('wasm-bindgen')
if (!wasmBindgen) {
  console.error('wasm-bindgen CLI not found; install wasm-bindgen-cli 0.2.126')
  process.exit(1)
}

if (!existsSync(wasmOpt)) {
  console.error(`wasm-opt not found at ${wasmOpt}; run pnpm install in bindings/wasm`)
  process.exit(1)
}

const profiles = [
  { feature: 'edge', outName: 'edge' },
  { feature: 'browser', outName: 'browser' },
]

const staging = mkdtempSync(join(tmpdir(), 'solvapay-wasm-'))
try {
  for (const { feature, outName } of profiles) {
    console.log(`\n=== building profile ${feature} ===`)
    run('cargo', [
      'build',
      '-p',
      'solvapay-wasm',
      '--target',
      'wasm32-unknown-unknown',
      '--profile',
      'wasm-release',
      '--no-default-features',
      '--features',
      feature,
    ])

    const wasmIn = join(
      cargoTargetDir(),
      'wasm32-unknown-unknown/wasm-release/solvapay_wasm.wasm',
    )
    const bindgenOut = join(staging, `${outName}-bindgen`)
    mkdirSync(bindgenOut, { recursive: true })
    run(wasmBindgen, [
      wasmIn,
      '--target',
      'web',
      '--out-dir',
      bindgenOut,
      '--out-name',
      'solvapay_wasm',
    ])

    const bgWasm = join(bindgenOut, 'solvapay_wasm_bg.wasm')
    const optimized = join(bindgenOut, 'solvapay_wasm_bg.opt.wasm')
    run(wasmOpt, [bgWasm, '-Oz', '-o', optimized])
    // Atomic replace within the staging dir.
    copyFileSync(optimized, bgWasm)
    rmSync(optimized, { force: true })

    // Mark generated glue.
    const glue = join(bindgenOut, 'solvapay_wasm.js')
    const glueSrc = readFileSync(glue, 'utf8')
    if (!glueSrc.startsWith('/* @generated')) {
      writeFileSync(
        glue,
        `/* @generated by wasm-bindgen 0.2.126 + wasm-opt -Oz (Binaryen 131.0.0) — do not edit */\n${glueSrc}`,
      )
    }

    const dest = join(staging, outName)
    mkdirSync(dest, { recursive: true })
    for (const name of readdirSync(bindgenOut)) {
      copyFileSync(join(bindgenOut, name), join(dest, name))
    }
  }

  const pkgDir = join(pkgRoot, 'pkg')
  if (checkDrift) {
    for (const { outName } of profiles) {
      const expectedDir = join(pkgDir, outName)
      const actualDir = join(staging, outName)
      if (!existsSync(expectedDir)) {
        console.error(`missing committed artifacts: ${expectedDir}`)
        process.exit(1)
      }
      const names = new Set([
        ...readdirSync(expectedDir),
        ...readdirSync(actualDir),
      ])
      for (const name of names) {
        const a = join(expectedDir, name)
        const b = join(actualDir, name)
        if (!existsSync(a) || !existsSync(b)) {
          console.error(`artifact drift: ${outName}/${name} presence mismatch`)
          process.exit(1)
        }
        const left = readFileSync(a)
        const right = readFileSync(b)
        if (!left.equals(right)) {
          console.error(`artifact drift: ${outName}/${name} content differs`)
          process.exit(1)
        }
      }
    }
    console.log('OK: wasm artifacts match committed pkg/')
  } else {
    rmSync(pkgDir, { recursive: true, force: true })
    mkdirSync(pkgDir, { recursive: true })
    for (const { outName } of profiles) {
      cpSync(join(staging, outName), join(pkgDir, outName), { recursive: true })
    }
    console.log(`Wrote ${pkgDir}/{edge,browser}`)
  }
} finally {
  rmSync(staging, { recursive: true, force: true })
}
