/**
 * Mirrored from platform/packages/domain/src/financial/tax-jurisdictions.ts.
 * Stripe Tax buyer universe and calculation-affecting tax ID types.
 *
 * Hand-maintained. Keep aligned with:
 * https://docs.stripe.com/tax/supported-countries
 * https://docs.stripe.com/billing/customer/tax-ids
 *
 * This is a *buyer* list. Do not derive it from STRIPE_CONNECT_SUPPORTED_COUNTRIES
 * (the seller allowlist).
 */

export const EU_MEMBER_COUNTRIES = [
  'AT',
  'BE',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GR',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE',
] as const

export type EuMemberCountry = (typeof EU_MEMBER_COUNTRIES)[number]

const BUYER_COUNTRY_ROWS = [
  ['AE', 'United Arab Emirates'],
  ['AL', 'Albania'],
  ['AM', 'Armenia'],
  ['AO', 'Angola'],
  ['AT', 'Austria'],
  ['AU', 'Australia'],
  ['AW', 'Aruba'],
  ['AZ', 'Azerbaijan'],
  ['BA', 'Bosnia and Herzegovina'],
  ['BB', 'Barbados'],
  ['BD', 'Bangladesh'],
  ['BE', 'Belgium'],
  ['BF', 'Burkina Faso'],
  ['BG', 'Bulgaria'],
  ['BH', 'Bahrain'],
  ['BJ', 'Benin'],
  ['BS', 'Bahamas'],
  ['BY', 'Belarus'],
  ['CA', 'Canada'],
  ['CD', 'Democratic Republic of the Congo'],
  ['CH', 'Switzerland'],
  ['CL', 'Chile'],
  ['CM', 'Cameroon'],
  ['CO', 'Colombia'],
  ['CR', 'Costa Rica'],
  ['CV', 'Cape Verde'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czechia'],
  ['DE', 'Germany'],
  ['DK', 'Denmark'],
  ['EC', 'Ecuador'],
  ['EE', 'Estonia'],
  ['EG', 'Egypt'],
  ['ES', 'Spain'],
  ['ET', 'Ethiopia'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GB', 'United Kingdom'],
  ['GE', 'Georgia'],
  ['GN', 'Guinea'],
  ['GR', 'Greece'],
  ['HK', 'Hong Kong'],
  ['HR', 'Croatia'],
  ['HU', 'Hungary'],
  ['ID', 'Indonesia'],
  ['IE', 'Ireland'],
  ['IN', 'India'],
  ['IS', 'Iceland'],
  ['IT', 'Italy'],
  ['JP', 'Japan'],
  ['KE', 'Kenya'],
  ['KG', 'Kyrgyzstan'],
  ['KH', 'Cambodia'],
  ['KR', 'South Korea'],
  ['KZ', 'Kazakhstan'],
  ['LA', 'Laos'],
  ['LI', 'Liechtenstein'],
  ['LK', 'Sri Lanka'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['LV', 'Latvia'],
  ['MA', 'Morocco'],
  ['MD', 'Moldova'],
  ['ME', 'Montenegro'],
  ['MK', 'North Macedonia'],
  ['MR', 'Mauritania'],
  ['MT', 'Malta'],
  ['MX', 'Mexico'],
  ['MY', 'Malaysia'],
  ['NG', 'Nigeria'],
  ['NL', 'Netherlands'],
  ['NO', 'Norway'],
  ['NP', 'Nepal'],
  ['NZ', 'New Zealand'],
  ['OM', 'Oman'],
  ['PE', 'Peru'],
  ['PH', 'Philippines'],
  ['PL', 'Poland'],
  ['PR', 'Puerto Rico'],
  ['PT', 'Portugal'],
  ['RO', 'Romania'],
  ['RS', 'Serbia'],
  ['RU', 'Russia'],
  ['SA', 'Saudi Arabia'],
  ['SE', 'Sweden'],
  ['SG', 'Singapore'],
  ['SI', 'Slovenia'],
  ['SK', 'Slovakia'],
  ['SN', 'Senegal'],
  ['SR', 'Suriname'],
  ['TH', 'Thailand'],
  ['TJ', 'Tajikistan'],
  ['TR', 'Türkiye'],
  ['TW', 'Taiwan'],
  ['TZ', 'Tanzania'],
  ['UA', 'Ukraine'],
  ['UG', 'Uganda'],
  ['US', 'United States of America'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VN', 'Vietnam'],
  ['ZA', 'South Africa'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe'],
] as const

export type StripeTaxBuyerCountry = (typeof BUYER_COUNTRY_ROWS)[number][0]

export const STRIPE_TAX_BUYER_COUNTRIES: ReadonlyArray<{
  code: StripeTaxBuyerCountry
  name: string
}> = BUYER_COUNTRY_ROWS.map(([code, name]) => ({ code, name }))

export const SUPPORTED_BUSINESS_COUNTRIES: readonly StripeTaxBuyerCountry[] =
  STRIPE_TAX_BUYER_COUNTRIES.map(country => country.code)

export type SupportedBusinessCountry = StripeTaxBuyerCountry

export const BUSINESS_COUNTRY_DISPLAY_NAMES: Record<StripeTaxBuyerCountry, string> =
  Object.fromEntries(STRIPE_TAX_BUYER_COUNTRIES.map(country => [country.code, country.name])) as Record<
    StripeTaxBuyerCountry,
    string
  >

const BUYER_COUNTRY_SET: ReadonlySet<string> = new Set(SUPPORTED_BUSINESS_COUNTRIES)

export function isStripeTaxBuyerCountry(value: string): value is StripeTaxBuyerCountry {
  return BUYER_COUNTRY_SET.has(value.trim().toUpperCase())
}

export const TAX_ID_TYPES = [
  'ae_trn',
  'al_tin',
  'am_tin',
  'ao_tin',
  'au_abn',
  'aw_tin',
  'az_tin',
  'ba_tin',
  'bb_tin',
  'bd_bin',
  'bf_ifu',
  'bh_vat',
  'bj_ifu',
  'bs_tin',
  'by_tin',
  'ca_gst_hst',
  'cd_nif',
  'ch_vat',
  'cl_tin',
  'cm_niu',
  'co_nit',
  'cr_tin',
  'cv_nif',
  'ec_ruc',
  'eg_tin',
  'et_tin',
  'eu_vat',
  'gb_vat',
  'ge_vat',
  'gn_nif',
  'hk_br',
  'id_npwp',
  'in_gst',
  'is_vat',
  'jp_trn',
  'ke_pin',
  'kg_tin',
  'kh_tin',
  'kr_brn',
  'kz_bin',
  'la_tin',
  'li_vat',
  'lk_vat',
  'ma_vat',
  'md_vat',
  'me_pib',
  'mk_vat',
  'mr_nif',
  'mx_rfc',
  'my_sst',
  'ng_tin',
  'no_vat',
  'np_pan',
  'nz_gst',
  'om_vat',
  'pe_ruc',
  'ph_tin',
  'rs_pib',
  'ru_inn',
  'sa_vat',
  'sg_gst',
  'sn_ninea',
  'sr_fin',
  'th_vat',
  'tj_tin',
  'tr_tin',
  'tw_vat',
  'tz_vat',
  'ua_vat',
  'ug_tin',
  'us_ein',
  'uy_ruc',
  'uz_vat',
  'vn_tin',
  'za_vat',
  'zm_tin',
  'zw_tin',
] as const

export type TaxIdType = (typeof TAX_ID_TYPES)[number]

const TAX_ID_TYPE_SET: ReadonlySet<string> = new Set(TAX_ID_TYPES)

export function isTaxIdType(value: unknown): value is TaxIdType {
  return typeof value === 'string' && TAX_ID_TYPE_SET.has(value)
}

/**
 * Calculation-affecting Stripe tax ID type per buyer country.
 * When a country has several types, the one that affects tax calculation wins
 * (jp_trn not jp_cn, ca_gst_hst not ca_bn, au_abn not au_arn, ch_vat not ch_uid,
 * sg_gst not sg_uen, no_vat not no_voec, eu_vat never de_stn / es_cif / …).
 */
export const COUNTRY_TO_TAX_ID_TYPE = {
  AE: 'ae_trn',
  AL: 'al_tin',
  AM: 'am_tin',
  AO: 'ao_tin',
  AT: 'eu_vat',
  AU: 'au_abn',
  AW: 'aw_tin',
  AZ: 'az_tin',
  BA: 'ba_tin',
  BB: 'bb_tin',
  BD: 'bd_bin',
  BE: 'eu_vat',
  BF: 'bf_ifu',
  BG: 'eu_vat',
  BH: 'bh_vat',
  BJ: 'bj_ifu',
  BS: 'bs_tin',
  BY: 'by_tin',
  CA: 'ca_gst_hst',
  CD: 'cd_nif',
  CH: 'ch_vat',
  CL: 'cl_tin',
  CM: 'cm_niu',
  CO: 'co_nit',
  CR: 'cr_tin',
  CV: 'cv_nif',
  CY: 'eu_vat',
  CZ: 'eu_vat',
  DE: 'eu_vat',
  DK: 'eu_vat',
  EC: 'ec_ruc',
  EE: 'eu_vat',
  EG: 'eg_tin',
  ES: 'eu_vat',
  ET: 'et_tin',
  FI: 'eu_vat',
  FR: 'eu_vat',
  GB: 'gb_vat',
  GE: 'ge_vat',
  GN: 'gn_nif',
  GR: 'eu_vat',
  HK: 'hk_br',
  HR: 'eu_vat',
  HU: 'eu_vat',
  ID: 'id_npwp',
  IE: 'eu_vat',
  IN: 'in_gst',
  IS: 'is_vat',
  IT: 'eu_vat',
  JP: 'jp_trn',
  KE: 'ke_pin',
  KG: 'kg_tin',
  KH: 'kh_tin',
  KR: 'kr_brn',
  KZ: 'kz_bin',
  LA: 'la_tin',
  LI: 'li_vat',
  LK: 'lk_vat',
  LT: 'eu_vat',
  LU: 'eu_vat',
  LV: 'eu_vat',
  MA: 'ma_vat',
  MD: 'md_vat',
  ME: 'me_pib',
  MK: 'mk_vat',
  MR: 'mr_nif',
  MT: 'eu_vat',
  MX: 'mx_rfc',
  MY: 'my_sst',
  NG: 'ng_tin',
  NL: 'eu_vat',
  NO: 'no_vat',
  NP: 'np_pan',
  NZ: 'nz_gst',
  OM: 'om_vat',
  PE: 'pe_ruc',
  PH: 'ph_tin',
  PL: 'eu_vat',
  PR: 'us_ein',
  PT: 'eu_vat',
  RO: 'eu_vat',
  RS: 'rs_pib',
  RU: 'ru_inn',
  SA: 'sa_vat',
  SE: 'eu_vat',
  SG: 'sg_gst',
  SI: 'eu_vat',
  SK: 'eu_vat',
  SN: 'sn_ninea',
  SR: 'sr_fin',
  TH: 'th_vat',
  TJ: 'tj_tin',
  TR: 'tr_tin',
  TW: 'tw_vat',
  TZ: 'tz_vat',
  UA: 'ua_vat',
  UG: 'ug_tin',
  US: 'us_ein',
  UY: 'uy_ruc',
  UZ: 'uz_vat',
  VN: 'vn_tin',
  ZA: 'za_vat',
  ZM: 'zm_tin',
  ZW: 'zw_tin',
} as const satisfies Record<StripeTaxBuyerCountry, TaxIdType>

export type MappedTaxIdCountry = keyof typeof COUNTRY_TO_TAX_ID_TYPE

export const TAX_ID_FORMAT_BY_TYPE: Record<TaxIdType, RegExp> = {
  ae_trn: /^\d{15}$/,
  al_tin: /^[A-Z]\d{8}[A-Z]$/,
  am_tin: /^\d{8}$/,
  ao_tin: /^\d{10}$/,
  au_abn: /^\d{11}$/,
  aw_tin: /^\d{8}$/,
  az_tin: /^\d{10}$/,
  ba_tin: /^\d{12}$/,
  bb_tin: /^\d{13}$/,
  bd_bin: /^\d{9}-?\d{4}$/,
  bf_ifu: /^\d{8}[A-Z]$/,
  bh_vat: /^\d{15}$/,
  bj_ifu: /^\d{13}$/,
  bs_tin: /^\d{3}\.?\d{3}\.?\d{3}$/,
  by_tin: /^\d{9}$/,
  ca_gst_hst: /^\d{9}RT\d{4}$/,
  cd_nif: /^[A-Z]\d{7}[A-Z]$/,
  ch_vat: /^CHE-?\d{3}\.?\d{3}\.?\d{3}(MWST|TVA|IVA)?$/,
  cl_tin: /^\d{1,2}\.?\d{3}\.?\d{3}-?[0-9K]$/,
  cm_niu: /^[A-Z]\d{12}[A-Z]$/,
  co_nit: /^\d{3}\.?\d{3}\.?\d{3}-?\d$/,
  cr_tin: /^\d-\d{3}-\d{6}$/,
  cv_nif: /^\d{9}$/,
  ec_ruc: /^\d{13}$/,
  eg_tin: /^\d{9}$/,
  et_tin: /^\d{10}$/,
  eu_vat:
    /^(ATU\d{8}|BE[01]\d{9}|BG\d{9,10}|HR\d{11}|CY\d{8}[A-Z]|CZ\d{8,10}|DK\d{8}|EE\d{9}|FI\d{8}|FR[A-HJ-NP-Z0-9]{2}\d{9}|DE\d{9}|EL\d{9}|HU\d{8}|IE\d{7}[A-W][A-I]?|IT\d{11}|LV\d{11}|LT(\d{9}|\d{12})|LU\d{8}|MT\d{8}|NL\d{9}B\d{2}|PL\d{10}|PT\d{9}|RO\d{2,10}|SK\d{10}|SI\d{8}|ES[A-Z0-9]\d{7}[A-Z0-9]|SE\d{12})$/,
  gb_vat: /^GB(\d{9}|\d{12}|GD\d{3}|HA\d{3})$/,
  ge_vat: /^\d{9}$/,
  gn_nif: /^\d{9}$/,
  hk_br: /^\d{8}$/,
  id_npwp: /^\d{2,3}\.?\d{3}\.?\d{3}\.?\d-?\d{3}\.?\d{3}$/,
  in_gst: /^\d{2}[A-Z]{5}\d{4}[A-Z]{4}$/,
  is_vat: /^\d{6}$/,
  jp_trn: /^T\d{13}$/,
  ke_pin: /^[A-Z]\d{9}[A-Z]$/,
  kg_tin: /^\d{14}$/,
  kh_tin: /^\d{4}-\d{9}$/,
  kr_brn: /^\d{3}-?\d{2}-?\d{5}$/,
  kz_bin: /^\d{12}$/,
  la_tin: /^\d{9}-\d{3}$/,
  li_vat: /^\d{5}$/,
  lk_vat: /^\d{9}-\d{4}$/,
  ma_vat: /^\d{8}$/,
  md_vat: /^\d{7}$/,
  me_pib: /^\d{8}$/,
  mk_vat: /^MK\d{13}$/,
  mr_nif: /^\d{8}$/,
  mx_rfc: /^[A-Z]{3,4}\d{6}[A-Z0-9]{3}$/,
  my_sst: /^[A-Z]\d{2}-?\d{4}-?\d{8}$/,
  ng_tin: /^\d{13}$/,
  no_vat: /^\d{9}MVA$/,
  np_pan: /^\d{9}$/,
  nz_gst: /^\d{8,9}$/,
  om_vat: /^OM\d{10}$/,
  pe_ruc: /^\d{11}$/,
  ph_tin: /^\d{12}$/,
  rs_pib: /^\d{9}$/,
  ru_inn: /^\d{10}$/,
  sa_vat: /^\d{15}$/,
  sg_gst: /^[A-Z]\d{8}[A-Z]$/,
  sn_ninea: /^\d{8}[A-Z]\d$/,
  sr_fin: /^\d{10}$/,
  th_vat: /^\d{13}$/,
  tj_tin: /^\d{9}$/,
  tr_tin: /^\d{10}$/,
  tw_vat: /^\d{8}$/,
  tz_vat: /^\d{8}[A-Z]$/,
  ua_vat: /^\d{9}$/,
  ug_tin: /^\d{10}$/,
  us_ein: /^\d{2}-?\d{7}$/,
  uy_ruc: /^\d{12}$/,
  uz_vat: /^\d{12}$/,
  vn_tin: /^\d{10}$/,
  za_vat: /^\d{10}$/,
  zm_tin: /^\d{10}$/,
  zw_tin: /^\d{10}$/,
}

/** Per-country EU VAT formats (stricter than the combined eu_vat regex). */
const EU_VAT_FORMAT_BY_COUNTRY: Record<EuMemberCountry, RegExp> = {
  AT: /^ATU\d{8}$/,
  BE: /^BE[01]\d{9}$/,
  BG: /^BG\d{9,10}$/,
  HR: /^HR\d{11}$/,
  CY: /^CY\d{8}[A-Z]$/,
  CZ: /^CZ\d{8,10}$/,
  DK: /^DK\d{8}$/,
  EE: /^EE\d{9}$/,
  FI: /^FI\d{8}$/,
  FR: /^FR[A-HJ-NP-Z0-9]{2}\d{9}$/,
  DE: /^DE\d{9}$/,
  GR: /^EL\d{9}$/,
  HU: /^HU\d{8}$/,
  IE: /^IE\d{7}[A-W][A-I]?$/,
  IT: /^IT\d{11}$/,
  LV: /^LV\d{11}$/,
  LT: /^LT(\d{9}|\d{12})$/,
  LU: /^LU\d{8}$/,
  MT: /^MT\d{8}$/,
  NL: /^NL\d{9}B\d{2}$/,
  PL: /^PL\d{10}$/,
  PT: /^PT\d{9}$/,
  RO: /^RO\d{2,10}$/,
  SK: /^SK\d{10}$/,
  SI: /^SI\d{8}$/,
  ES: /^ES[A-Z0-9]\d{7}[A-Z0-9]$/,
  SE: /^SE\d{12}$/,
}

export function normalizeTaxId(taxId: string): string {
  return taxId.trim().toUpperCase().replace(/\s+/g, '')
}

export function deriveTaxIdType(country: StripeTaxBuyerCountry): TaxIdType | undefined {
  return COUNTRY_TO_TAX_ID_TYPE[country as MappedTaxIdCountry]
}

export function isValidTaxIdForType(type: TaxIdType, taxId: string): boolean {
  return TAX_ID_FORMAT_BY_TYPE[type].test(normalizeTaxId(taxId))
}

export function isValidTaxIdForCountry(country: StripeTaxBuyerCountry, taxId: string): boolean {
  const type = deriveTaxIdType(country)
  if (!type) {
    return false
  }
  const normalized = normalizeTaxId(taxId)
  if (type === 'eu_vat' && (EU_MEMBER_COUNTRIES as readonly string[]).includes(country)) {
    return EU_VAT_FORMAT_BY_COUNTRY[country as EuMemberCountry].test(normalized)
  }
  return TAX_ID_FORMAT_BY_TYPE[type].test(normalized)
}

export const TAX_ID_EXAMPLE_BY_COUNTRY: Partial<Record<StripeTaxBuyerCountry, string>> = {
  AE: '123456789012345',
  AL: 'J12345678N',
  AM: '02538904',
  AO: '5123456789',
  AT: 'ATU12345678',
  AU: '12345678912',
  AW: '12345678',
  AZ: '0123456789',
  BA: '123456789012',
  BB: '1123456789012',
  BD: '123456789-0123',
  BE: 'BE0123456789',
  BF: '12345678A',
  BG: 'BG0123456789',
  BH: '123456789012345',
  BJ: '1234567890123',
  BS: '123.456.789',
  BY: '123456789',
  CA: '123456789RT0002',
  CD: 'A0123456M',
  CH: 'CHE-123.456.789MWST',
  CL: '12.345.678-K',
  CM: 'M123456789000L',
  CO: '123.456.789-0',
  CR: '1-234-567890',
  CV: '213456789',
  CY: 'CY12345678Z',
  CZ: 'CZ1234567890',
  DE: 'DE123456789',
  DK: 'DK12345678',
  EC: '1234567890001',
  EE: 'EE123456789',
  EG: '123456789',
  ES: 'ESA1234567Z',
  ET: '1234567890',
  FI: 'FI12345678',
  FR: 'FRAB123456789',
  GB: 'GB123456789',
  GE: '123456789',
  GN: '123456789',
  GR: 'EL123456789',
  HK: '12345678',
  HR: 'HR12345678912',
  HU: 'HU12345678',
  ID: '012.345.678.9-012.345',
  IE: 'IE1234567AB',
  IN: '12ABCDE3456FGZH',
  IS: '123456',
  IT: 'IT12345678912',
  JP: 'T1234567891234',
  KE: 'P000111111A',
  KG: '12345678901234',
  KH: '1001-123456789',
  KR: '123-45-67890',
  KZ: '123456789012',
  LA: '123456789-000',
  LI: '12345',
  LK: '123456789-1234',
  LT: 'LT123456789',
  LU: 'LU12345678',
  LV: 'LV12345678912',
  MA: '12345678',
  MD: '1234567',
  ME: '12345678',
  MK: 'MK1234567890123',
  MR: '12345678',
  MT: 'MT12345678',
  MX: 'ABC010203AB9',
  MY: 'A12-3456-78912345',
  NG: '1234567890123',
  NL: 'NL123456789B12',
  NO: '123456789MVA',
  NP: '123456789',
  NZ: '123456789',
  OM: 'OM1234567890',
  PE: '12345678901',
  PH: '123456789012',
  PL: 'PL1234567890',
  PR: '12-3456789',
  PT: 'PT123456789',
  RO: 'RO1234567891',
  RS: '123456789',
  RU: '1234567891',
  SA: '123456789012345',
  SE: 'SE123456789123',
  SG: 'M12345678X',
  SI: 'SI12345678',
  SK: 'SK1234567891',
  SN: '12345672A2',
  SR: '1234567890',
  TH: '1234567891234',
  TJ: '123456789',
  TR: '0123456789',
  TW: '12345678',
  TZ: '12345678A',
  UA: '123456789',
  UG: '1014751879',
  US: '12-3456789',
  UY: '123456789012',
  UZ: '123456789012',
  VN: '1234567890',
  ZA: '4123456789',
  ZM: '1004751879',
  ZW: '1234567890',
}

export const TAX_ID_FIELD_LABEL_BY_TYPE: Partial<Record<TaxIdType, string>> = {
  eu_vat: 'VAT ID',
  gb_vat: 'VAT Number',
  us_ein: 'EIN (Employer Identification Number)',
  au_abn: 'ABN',
  jp_trn: 'Registration number (Tōroku Bangō)',
  ca_gst_hst: 'GST/HST number',
  ch_vat: 'VAT number',
  no_vat: 'VAT number',
  sg_gst: 'GST number',
  in_gst: 'GSTIN',
  nz_gst: 'GST number',
  ae_trn: 'TRN',
  za_vat: 'VAT number',
}

export const SELLER_TAX_IDENTIFIER_DISPLAY_LABEL_BY_TYPE: Partial<Record<TaxIdType, string>> = {
  eu_vat: 'VAT number',
  gb_vat: 'VAT number',
  us_ein: 'EIN',
  au_abn: 'ABN',
  jp_trn: 'Registration number',
  ca_gst_hst: 'GST/HST number',
  ch_vat: 'VAT number',
  no_vat: 'VAT number',
  sg_gst: 'GST number',
  in_gst: 'GSTIN',
}

export const DEFAULT_TAX_IDENTIFIER_DISPLAY_LABEL = 'Tax ID'

export function getTaxIdFieldLabel(country: StripeTaxBuyerCountry): string {
  const type = deriveTaxIdType(country)
  if (!type) {
    return DEFAULT_TAX_IDENTIFIER_DISPLAY_LABEL
  }
  return TAX_ID_FIELD_LABEL_BY_TYPE[type] ?? DEFAULT_TAX_IDENTIFIER_DISPLAY_LABEL
}

export function getTaxIdExample(country: StripeTaxBuyerCountry): string {
  return TAX_ID_EXAMPLE_BY_COUNTRY[country] ?? 'Enter tax ID'
}

export function getTaxIdHelperText(country: StripeTaxBuyerCountry): string {
  const example = getTaxIdExample(country)
  const type = deriveTaxIdType(country)
  if (type === 'us_ein') {
    return `Enter your EIN, e.g. ${example}`
  }
  if (type === 'gb_vat' || type === 'eu_vat') {
    return `Enter your full VAT number including the country code, e.g. ${example}`
  }
  return `Enter your tax ID, e.g. ${example}`
}

export type StripeTaxDomesticScheme = 'standard' | 'simplified'

/**
 * Stripe accepts exactly one of standard / simplified per country.
 * Remote-seller digital VAT jurisdictions are simplified-only.
 */
export const STRIPE_TAX_DOMESTIC_SCHEME_BY_COUNTRY: Record<string, StripeTaxDomesticScheme> = {
  AE: 'standard',
  AT: 'standard',
  AU: 'standard',
  BE: 'standard',
  BG: 'standard',
  CA: 'standard',
  CH: 'standard',
  CY: 'standard',
  CZ: 'standard',
  DE: 'standard',
  DK: 'standard',
  EE: 'standard',
  ES: 'standard',
  FI: 'standard',
  FR: 'standard',
  GB: 'standard',
  GR: 'standard',
  HK: 'standard',
  HR: 'standard',
  HU: 'standard',
  IE: 'standard',
  IT: 'standard',
  JP: 'standard',
  LI: 'standard',
  LT: 'standard',
  LU: 'standard',
  LV: 'standard',
  MT: 'standard',
  MX: 'standard',
  NL: 'standard',
  NO: 'standard',
  NZ: 'standard',
  PL: 'standard',
  PR: 'standard',
  PT: 'standard',
  RO: 'standard',
  SE: 'standard',
  SG: 'standard',
  SI: 'standard',
  SK: 'standard',
  AL: 'simplified',
  AM: 'simplified',
  AO: 'simplified',
  AW: 'simplified',
  AZ: 'simplified',
  BA: 'simplified',
  BB: 'simplified',
  BD: 'simplified',
  BF: 'simplified',
  BH: 'simplified',
  BJ: 'simplified',
  BS: 'simplified',
  BY: 'simplified',
  CD: 'simplified',
  CL: 'simplified',
  CM: 'simplified',
  CO: 'simplified',
  CR: 'simplified',
  CV: 'simplified',
  EC: 'simplified',
  EG: 'simplified',
  ET: 'simplified',
  GE: 'simplified',
  GN: 'simplified',
  ID: 'simplified',
  IN: 'simplified',
  IS: 'simplified',
  KE: 'simplified',
  KG: 'simplified',
  KH: 'simplified',
  KR: 'simplified',
  KZ: 'simplified',
  LA: 'simplified',
  LK: 'simplified',
  MA: 'simplified',
  MD: 'simplified',
  ME: 'simplified',
  MK: 'simplified',
  MR: 'simplified',
  MY: 'simplified',
  NG: 'simplified',
  NP: 'simplified',
  OM: 'simplified',
  PE: 'simplified',
  PH: 'simplified',
  RS: 'simplified',
  RU: 'simplified',
  SA: 'simplified',
  SN: 'simplified',
  SR: 'simplified',
  TH: 'simplified',
  TJ: 'simplified',
  TR: 'simplified',
  TW: 'simplified',
  TZ: 'simplified',
  UA: 'simplified',
  UG: 'simplified',
  UY: 'simplified',
  UZ: 'simplified',
  VN: 'simplified',
  ZA: 'simplified',
  ZM: 'simplified',
  ZW: 'simplified',
}

export function stripeTaxDomesticSchemeForCountry(country: string): StripeTaxDomesticScheme {
  const scheme = STRIPE_TAX_DOMESTIC_SCHEME_BY_COUNTRY[country.toUpperCase()]
  if (!scheme) {
    throw new Error(`No Stripe Tax domestic registration scheme mapped for ${country}`)
  }
  return scheme
}
