// @generated by dto-gen (--rs-defaults-out) — do not edit. Regenerate with: pnpm gen

//! Frozen contract defaults (`defaults:` in sdk-contract.yaml).

/// Retry attempts after the initial call.
pub const DEFAULT_MAX_RETRIES: u32 = 2;
/// Initial retry delay in milliseconds.
pub const DEFAULT_INITIAL_DELAY_MS: u64 = 500;
/// Retry backoff name.
pub const RETRY_BACKOFF: &str = "fixed";
/// Webhook timestamp tolerance in seconds.
pub const WEBHOOK_TOLERANCE_SEC: i64 = 300;
/// Default limits-cache TTL in milliseconds.
pub const DEFAULT_LIMITS_CACHE_TTL_MS: u64 = 10_000;
/// Frozen customer-dedup TTL (`defaults.customerDedupTTLMs`).
pub const CUSTOMER_DEDUP_TTL_MS: u64 = 60_000;
/// Frozen customer-dedup max cache size (`defaults.customerDedupMaxCacheSize`).
pub const CUSTOMER_DEDUP_MAX_CACHE_SIZE: usize = 1000;
/// Frozen anonymous customer ref (`defaults.anonymousCustomerRef`).
pub const ANONYMOUS_CUSTOMER_REF: &str = "anonymous";
/// Frozen `trackUsage` request-id template (`defaults.requestIdFormat`).
pub const REQUEST_ID_FORMAT: &str = "solvapay_{epochMs}_{random9}";
/// Frozen `trackUsage.actionType` (`defaults.usageActionType`).
pub const USAGE_ACTION_TYPE: &str = "api_call";
/// Payment idempotency-key template (`defaults.idempotencyKeyFormats.payment`).
pub const PAYMENT_IDEMPOTENCY_KEY_FORMAT: &str = "payment-{planRef}-{epochMs}-{random9}";
/// Top-up idempotency-key template (`defaults.idempotencyKeyFormats.topup`).
pub const TOPUP_IDEMPOTENCY_KEY_FORMAT: &str = "topup-{epochMs}-{random9}";
/// Go methods take `context.Context` as the first parameter.
pub const GO_CONTEXT_FIRST_PARAM: bool = true;
