// @generated by dto-gen (--rs-helpers-out) — do not edit. Regenerate with: pnpm gen

//! Generated portable helper re-exports.

#[allow(unused_imports)]
pub use solvapay_core::{
    BillingCycle, BusinessDetailsInput, Charge, CreditSignals, CreditsToDisplayInput,
    CustomerSnapshot, FreeLimit, FreeLimitInput, GateContent, PaywallClientPayload, PaywallGate,
    PaywallGateLimits, PaywallLimits, PaywallNextAction, PaywallState, PlanPricingShape,
    ProductReadinessInput, ProductReadinessResult, SellerIdentityDisplay, SellerIdentityInput,
    TaxIdType, UsageRate, ValidateBusinessDetailsResult,
};

/// Client-side balance reconciliation backoff after async credit top-ups, in milliseconds.
///
/// # Returns
///
/// Frozen delay table.
pub use solvapay_core::balance_poll::balance_reconcile_delays_ms as BALANCE_RECONCILE_DELAYS_MS;

/// Map of supported business country codes to display names.
pub use solvapay_core::business_details::business_country_display_names as BUSINESS_COUNTRY_DISPLAY_NAMES;

/// Ordered list of business country options for seller identity forms.
pub use solvapay_core::business_details::business_country_options_table as BUSINESS_COUNTRY_OPTIONS;

/// Map of business country codes to default tax ID types.
pub use solvapay_core::business_details::country_to_tax_id_type as COUNTRY_TO_TAX_ID_TYPE;

/// Countries that require a postal or ZIP code for Stripe Tax.
///
/// # Returns
///
/// Country code list.
pub use solvapay_core::business_details::postal_code_required_countries;

/// Buyer-facing note when VAT reverse charge applies.
pub use solvapay_core::tax_summary::reverse_charge_note as REVERSE_CHARGE_NOTE;

/// Map of seller tax identifier types to display labels.
pub use solvapay_core::seller_identity::seller_tax_identifier_display_label_by_type as SELLER_TAX_IDENTIFIER_DISPLAY_LABEL_BY_TYPE;

/// Countries that require a state or province for Stripe Tax.
///
/// # Returns
///
/// Country code list.
pub use solvapay_core::business_details::state_required_countries;

/// Frozen list of country codes supported for seller business details.
pub use solvapay_core::business_details::supported_business_countries as SUPPORTED_BUSINESS_COUNTRIES;

/// Frozen set of supported tax behavior values.
pub use solvapay_core::business_details::tax_behaviors as TAX_BEHAVIORS;

/// Currencies that default to tax-exclusive pricing behavior.
pub use solvapay_core::business_details::tax_exclusive_currencies as TAX_EXCLUSIVE_CURRENCIES;

/// Map of country codes to example tax ID strings.
pub use solvapay_core::business_details::tax_id_example_by_country as TAX_ID_EXAMPLE_BY_COUNTRY;

/// Frozen set of supported tax ID type values.
///
/// # Returns
///
/// Tax ID type list.
pub use solvapay_core::business_details::tax_id_types as TAX_ID_TYPES;

/// Buyer-facing note when tax is not collected on the purchase.
pub use solvapay_core::tax_summary::tax_not_collected_note as TAX_NOT_COLLECTED_NOTE;

/// Top-up payment-intent balance poll backoff, in milliseconds.
///
/// # Returns
///
/// Frozen delay table.
pub use solvapay_core::balance_poll::topup_balance_poll_delays_ms as TOPUP_BALANCE_POLL_DELAYS_MS;

/// Append the paid-tool account hint to a merchant tool description.
///
/// # Arguments
///
/// * `description` — Optional merchant-authored description; trailing whitespace is stripped.
///
/// # Returns
///
/// Description plus hint, or the hint alone when no description is present.
pub use solvapay_core::mcp::append_paid_tool_description;

/// Reject empty, placeholder, or non-prd_ product refs at construction time.
///
/// # Returns
///
/// Throws when the ref is not a real prd_ identifier.
pub use solvapay_core::product_readiness::assert_valid_product_ref;

/// Read the billing-cycle option from a plan.
///
/// # Returns
///
/// Interval (and count when greater than 1), or null.
pub use solvapay_core::pricing_options::billing_cycle;

/// Build the merchant-facing customer snapshot from a limits body.
///
/// # Returns
///
/// Customer snapshot with defaults applied, including throttled and overage.
pub use solvapay_core::gate_driver::build_customer_snapshot;

/// Build the human-readable paywall gate message from state and gate content.
///
/// # Returns
///
/// Gate message string.
pub use solvapay_core::paywall_state::build_gate_message;

/// Build a soft nudge message when usage approaches plan limits.
///
/// # Returns
///
/// Nudge message string.
pub use solvapay_core::paywall_state::build_nudge_message;

/// Build the structured paywall gate payload for a product and limits snapshot.
///
/// # Returns
///
/// Structured gate content for paywall responses.
pub use solvapay_core::paywall_gate::build_paywall_gate;

/// Return every charge option on a plan, in wire order.
///
/// # Returns
///
/// Charge objects (flat, unit, or seat).
pub use solvapay_core::pricing_options::charges;

/// Classify paywall state from limits and product context.
///
/// # Returns
///
/// Canonical paywall state label.
pub use solvapay_core::paywall_state::classify_paywall_state;

/// True when the plan counts usage via a per-unit charge, limit, or tier.
///
/// # Returns
///
/// Whether the plan has a usage counter even without a per-unit rate.
pub use solvapay_core::pricing_options::counts_usage;

/// Coalesce credit-balance channels and derive shortfall and remaining-call counts.
///
/// # Arguments
///
/// * `limits` — Limits response, or null/absent when no check has run.
///
/// # Returns
///
/// Credit signals including isCreditBased and optional shortfall fields.
pub use solvapay_core::paywall_state::credit_signals;

/// Credits per metered call when the charge currency matches the balance peg.
///
/// # Returns
///
/// Credits per unit, or null when the rate cannot be established honestly.
pub use solvapay_core::pricing_options::credits_per_unit_from_balance;

/// Convert credit units into display minor units for a currency.
///
/// # Returns
///
/// Display amount in minor units.
pub use solvapay_core::credit_display::credits_to_display_minor_units;

/// Derive the tax ID type for a business country.
///
/// # Returns
///
/// Tax ID type string when known.
pub use solvapay_core::business_details::derive_tax_id_type;

/// Evaluate whether a product can be sold (active status plus an active plan).
///
/// # Returns
///
/// Readiness result with issues and plan counts.
pub use solvapay_core::product_readiness::evaluate_product_readiness;

/// Format a minor-unit amount as buyer-facing money.
///
/// # Returns
///
/// Formatted price string.
pub use solvapay_core::money_format::format_price;

/// Return the checkout subtotal label for a tax treatment.
///
/// # Returns
///
/// Subtotal or Subtotal (excl. VAT).
pub use solvapay_core::tax_summary::format_subtotal_label;

/// Return the VAT row label for a treatment and rate.
///
/// # Returns
///
/// VAT label string.
pub use solvapay_core::tax_summary::format_vat_summary_label;

/// Return whether two normalized free limits share the same cap.
///
/// # Arguments
///
/// * `left` — First normalized free limit.
/// * `right` — Second normalized free limit.
///
/// # Returns
///
/// True when meter, cap, scope, and window days all match.
pub use solvapay_core::free_limit::free_limits_agree;

/// Return the frozen regex source for free-allowance meter names.
///
/// # Returns
///
/// The `^free-[a-z0-9-]+$` pattern string.
pub use solvapay_core::free_limit::free_meter_name_pattern;

/// Build the free-tool description suffix, including shared-meter names.
///
/// # Returns
///
/// The `Free tool — …` sentence, plus a share tail when names are present.
pub use solvapay_core::free_limit::free_tool_description_suffix;

/// Return the postal or ZIP code field label for a country.
///
/// # Returns
///
/// Field label string.
pub use solvapay_core::business_details::get_postal_code_field_label;

/// Return the postal or ZIP code field placeholder for a country.
///
/// # Returns
///
/// Placeholder string.
pub use solvapay_core::business_details::get_postal_code_placeholder;

/// Return the display label for a seller tax identifier type.
///
/// # Returns
///
/// Display label string.
pub use solvapay_core::seller_identity::get_seller_tax_identifier_display_label;

/// Return the state or province field label for a country.
///
/// # Returns
///
/// Field label string.
pub use solvapay_core::business_details::get_state_field_label;

/// Return an example tax ID string for a country.
///
/// # Returns
///
/// Example tax ID string.
pub use solvapay_core::business_details::get_tax_id_example;

/// Return the localized field label for a country tax ID.
///
/// # Returns
///
/// Field label string.
pub use solvapay_core::business_details::get_tax_id_field_label;

/// Return helper text describing the tax ID format for a country.
///
/// # Returns
///
/// Helper text string.
pub use solvapay_core::business_details::get_tax_id_helper_text;

/// Return the headline flat charge in each currency, excluding setup fees.
///
/// # Returns
///
/// One flat charge per currency, in first-seen order.
pub use solvapay_core::pricing_options::headline_charges;

/// Read the included-unit cap for a meter from the limit option.
///
/// # Returns
///
/// Cap (0 means unlimited), or null when no limit is configured.
pub use solvapay_core::pricing_options::included_units;

/// Whether Stripe Tax requires a postal or ZIP code for a country.
///
/// # Returns
///
/// True when a postal or ZIP code is required.
pub use solvapay_core::business_details::is_postal_code_required;

/// Whether Stripe Tax requires a state or province for a country.
///
/// # Returns
///
/// True when a state or province is required.
pub use solvapay_core::business_details::is_state_required;

/// Whether a string is a supported tax ID type.
///
/// # Arguments
///
/// * `value` — Candidate tax ID type wire value.
///
/// # Returns
///
/// True when the value is one of TAX_ID_TYPES.
pub use solvapay_core::business_details::is_tax_id_type;

/// Return whether remaining is the backend unlimited sentinel (-1).
///
/// # Returns
///
/// True only when remaining is exactly -1.
pub use solvapay_core::limits::is_unlimited_remaining;

/// Return whether a currency uses zero decimal places.
///
/// # Returns
///
/// True when the currency has zero decimal places.
pub use solvapay_core::credit_display::is_zero_decimal_currency;

/// Escape markdown link-label delimiters in a provider-authored plan name.
///
/// # Arguments
///
/// * `name` — Plan display name or reference.
///
/// # Returns
///
/// Label safe to embed in a markdown link.
pub use solvapay_core::paywall_state::link_label;

/// Read the meter a plan counts against from a per-unit charge, tier, or limit option.
///
/// # Returns
///
/// Meter name, or null when no charge, tier, or limit names one.
pub use solvapay_core::pricing_options::meter_name;

/// Return how many minor units make one major unit for a currency.
///
/// # Returns
///
/// Minor units per major unit.
pub use solvapay_core::credit_display::minor_units_per_major;

/// Map a classified paywall state to its single primary recovery action.
///
/// # Arguments
///
/// * `state` — Classified paywall state.
///
/// # Returns
///
/// Primary recovery action (topup, checkout, activate, or account).
pub use solvapay_core::paywall_state::next_action_for;

/// Normalize a free-tool allowance, defaulting and validating the meter.
///
/// # Returns
///
/// Normalized `{ meter, cap, scope, windowDays? }` or a 400 helper error.
pub use solvapay_core::free_limit::normalize_free_limit;

/// Project a PaywallError into the client-facing payload shape.
///
/// # Returns
///
/// Client payload object for paywall responses.
pub use solvapay_core::paywall_payload::paywall_client_payload as paywall_error_to_client_payload;

/// JSON Schema for paywall structuredContent (payment_required | activation_required).
///
/// # Returns
///
/// A oneOf schema covering both gate branches.
pub use solvapay_core::paywall_gate::paywall_structured_content_schema;

/// Convert a per-unit charge in minor units to credits via the USD peg.
///
/// # Returns
///
/// Credits per metered unit (0 for a free meter).
pub use solvapay_core::pricing_options::pegged_credits_per_unit;

/// Return the first per-unit charge, optionally scoped to one meter.
///
/// # Returns
///
/// The metered charge, or null when the plan does not meter usage.
pub use solvapay_core::pricing_options::per_unit_charge;

/// Build a cheapest-first markdown checkout ladder from gate plans.
///
/// # Arguments
///
/// * `gate` — Gate content carrying plans and the active planRef.
///
/// # Returns
///
/// Joined markdown links, or null when no plan has a checkoutUrl.
pub use solvapay_core::paywall_state::plan_ladder;

/// Derive the pricing shape a plan-row or narration surface should branch on.
///
/// # Returns
///
/// Shape, headline, currency, cycle, and usage rate.
pub use solvapay_core::pricing_options::plan_pricing_shape;

/// Resolve a product ref from metadata or env, or throw a named missing-ref error.
///
/// # Returns
///
/// A product ref string, or throws when neither is set.
pub use solvapay_core::paywall_decision::require_product_ref;

/// Resolve seller identity fields into a display projection.
///
/// # Returns
///
/// Display projection for seller identity.
pub use solvapay_core::seller_identity::resolve_seller_identity_display;

/// Resolve inclusive vs exclusive tax behavior for a currency/country pair.
///
/// # Returns
///
/// Resolved tax behavior.
pub use solvapay_core::business_details::resolve_tax_behavior;

/// Return the buyer-facing note for a non-standard tax treatment.
///
/// # Returns
///
/// Note string, or null when no note applies.
pub use solvapay_core::tax_summary::resolve_tax_treatment_note;

/// Return whether a VAT amount row should render for a tax treatment.
///
/// # Returns
///
/// True when a VAT row should be shown.
pub use solvapay_core::tax_summary::should_show_tax_row;

/// Return the tier bands a plan prices a meter with, ordered by floor.
///
/// # Returns
///
/// One meter's band stack; empty when the plan has no bands for that meter.
pub use solvapay_core::pricing_options::tier_bands;

/// List every meter the plan prices with tier bands, in first-seen order.
///
/// # Returns
///
/// Meter names; empty when the plan has no tier bands.
pub use solvapay_core::pricing_options::tier_meters;

/// Convert a minor-unit amount to its major-unit equivalent.
///
/// # Returns
///
/// Major-unit amount.
pub use solvapay_core::money_format::to_major_units;

/// Read the free-trial length in days from a plan.
///
/// # Returns
///
/// Trial length in days, or null when the plan has no trial.
pub use solvapay_core::pricing_options::trial_days;

/// Return what one metered unit costs, from a per-unit charge or the first priced band.
///
/// # Returns
///
/// The entry rate, with tiered true when that rate is the floor of a stack.
pub use solvapay_core::pricing_options::usage_rate;

/// Validate seller business-details fields before submission.
///
/// # Returns
///
/// Validation issues when present.
pub use solvapay_core::business_details::validate_business_details;

// Internal cores (`catalog: none`) re-exported for facade parity.

/// Binding for `MCP_TOOL_NAMES`.
pub use solvapay_core::mcp::mcp_tool_names_json as MCP_TOOL_NAMES;

/// Binding for `assertResponseResult` — brand failures are Transport errors
/// (TS wrapper rethrows as plain `Error` for fixture name parity).
pub use solvapay_core::mcp::assert_response_result;

/// Binding for `attachBusinessDetailsValidationError`.
pub use solvapay_core::payment::attach_business_details_validation_error;

/// Binding for `buildCreateCustomerParams` (`nowMs` is required; no clock string).
pub use solvapay_core::customer_sync::build_create_customer_params;

/// Binding for `buildPayableToolResult`.
pub use solvapay_core::mcp::build_payable_tool_result;

/// Binding for `buildPromptDescriptorMetadata`.
pub use solvapay_core::mcp::build_prompt_descriptor_metadata;

/// Binding for `buildPromptUserMessage`.
pub use solvapay_core::mcp::build_prompt_user_message;

/// Binding for `buildToolDescriptorMetadata`.
pub use solvapay_core::mcp::build_tool_descriptor_metadata;

/// Binding for `classifyCancelError`.
pub use solvapay_core::renewal::classify_cancel_error;

/// Binding for `classifyCreateError`.
pub use solvapay_core::customer_sync::classify_create_error;

/// Binding for `classifyCustomerRef`.
pub use solvapay_core::customer_sync::classify_customer_ref;

/// Binding for `classifyLookupError`.
pub use solvapay_core::customer_sync::classify_lookup_error;

/// Binding for `classifyReactivateError`.
pub use solvapay_core::renewal::classify_reactivate_error;

/// Binding for `coerceCustomerOptions`.
pub use solvapay_core::customer_sync::coerce_customer_options;

/// Binding for `compileStringFieldInputSchemaJson`.
pub use solvapay_core::mcp::compile_string_field_input_schema_json;

/// Binding for `customerRefFromClaims`.
pub use solvapay_core::jwt_util::customer_ref_from_claims;

/// Binding for `decidePaywallOutcome`.
pub use solvapay_core::paywall_decision::decide_paywall_outcome;

/// Binding for `decodeJwtPayloadUnverified`.
pub use solvapay_core::jwt_util::decode_jwt_payload_unverified;

/// Binding for `defaultMcpBearerExpectations`.
pub use solvapay_core::jwt_util::default_mcp_bearer_expectations;

/// Binding for `deriveActiveProducts`.
pub use solvapay_core::purchase::derive_active_products;

/// Binding for `deriveDefaultView`.
pub use solvapay_core::mcp::derive_default_view;

/// Binding for `deriveIcons` — absent/empty branding → JSON `null`.
pub use solvapay_core::mcp::derive_icons;

/// Binding for `ensureOutputSchemaObjectType`.
pub use solvapay_core::mcp::ensure_output_schema_object_type;

/// Binding for `evaluateBalanceObservation`.
pub use solvapay_core::balance_poll::evaluate_balance_observation;

/// Binding for `evaluateCachedLimits`.
pub use solvapay_core::paywall_decision::evaluate_cached_limits;

/// Binding for `evaluateClaimedLimits`.
pub use solvapay_core::paywall_decision::evaluate_claimed_limits;

/// Binding for `evaluateFreshLimits`.
pub use solvapay_core::paywall_decision::evaluate_fresh_limits;

/// Binding for `extractBackendCustomerRef`.
pub use solvapay_core::customer_sync::extract_backend_customer_ref;

/// Binding for `extractBearerToken`.
pub use solvapay_core::jwt_util::extract_bearer_token;

/// Binding for `formatCompactCredits`.
pub use solvapay_core::money_format::format_compact_credits;

/// Binding for `getBusinessCountryOptions`.
pub use solvapay_core::business_details::get_business_country_options;

/// Binding for `getCustomerAddressFieldErrors`.
pub use solvapay_core::business_details::get_customer_address_field_errors;

/// Binding for `historyRows`.
pub use solvapay_core::history::history_rows;

/// Binding for `isCachedCustomerRefValid`.
pub use solvapay_core::purchase::is_cached_customer_ref_valid;

/// Binding for `isCustomerAddressComplete`.
pub use solvapay_core::business_details::is_customer_address_complete;

/// Binding for `isEmailConflict`.
pub use solvapay_core::customer_sync::is_email_conflict;

/// Binding for `isErrorResult`.
pub use solvapay_core::route_error::is_error_result;

/// Binding for `makeResponseResult`.
pub use solvapay_core::mcp::make_response_result;

/// Binding for `mapRouteError` (`kind`: `"solvapay"` | `"paywall"` | `"error"` | `"unknown"`).
pub use solvapay_core::route_error::map_route_error;

/// Binding for `mcpViewMaps`.
pub use solvapay_core::mcp::mcp_view_maps;

/// Binding for `normalizeCancelResponse`.
pub use solvapay_core::renewal::normalize_cancel_response;

/// Binding for `normalizeReactivateResponse`.
pub use solvapay_core::renewal::normalize_reactivate_response;

/// Binding for `overlayClaimedLimits`.
pub use solvapay_core::paywall_decision::overlay_claimed_limits;

/// Binding for `paywallToolResult`.
pub use solvapay_core::mcp::paywall_tool_result;

/// Binding for `planConsequence`.
pub use solvapay_core::mcp::plan_consequence;

/// Binding for `projectPaymentIntentResult`.
pub use solvapay_core::payment::project_payment_intent_result;

/// Binding for `projectTopupProcessOutcome`.
pub use solvapay_core::payment::project_topup_process_outcome;

/// Binding for `projectUsageSnapshot`.
pub use solvapay_core::usage::project_usage_snapshot;

/// Binding for `purchaseUsageIsMetered`.
pub use solvapay_core::usage::purchase_usage_is_metered;

/// Binding for `resolveAccountState`.
pub use solvapay_core::mcp::resolve_account_state;

/// Binding for `resolveAuthenticatedUser`.
pub use solvapay_core::auth_resolution::resolve_authenticated_user;

/// Binding for `resolveBuyerCountry`.
pub use solvapay_core::business_details::resolve_buyer_country;

/// Binding for `resolveCheckLimitsParams`.
///
/// Ok and Err ([`HelperErrorResult`]) both serialize as the envelope **value**. Precedence is freeLimit.meter, then meterName, then usageType, then `requests`.
pub use solvapay_core::limits::resolve_check_limits_params;

/// Binding for `resolveCustomerRef`.
pub use solvapay_core::customer_ref::resolve_customer_ref;

/// Binding for `resolveDisplayMode`.
pub use solvapay_core::mcp::resolve_display_mode;

/// Binding for `resolveFallbackGateLimits`.
pub use solvapay_core::paywall_decision::resolve_fallback_gate_limits;

/// Binding for `resolvePlanShape`.
pub use solvapay_core::mcp::resolve_narrator_plan_shape as resolve_plan_shape;

/// Binding for `resolveProductRef`.
pub use solvapay_core::paywall_decision::resolve_product_ref;

/// Binding for `resolvePurchaseCustomerRef`.
pub use solvapay_core::purchase::resolve_purchase_customer_ref;

/// Binding for `resolveReturnUrl`.
pub use solvapay_core::checkout::resolve_return_url;

/// Binding for `resolveUsageExtra`.
pub use solvapay_core::usage_request::resolve_usage_extra;

/// Binding for `retryNextDelayMs`.
///
/// Args: `{ maxRetries?, initialDelay?, backoffStrategy?, attempt }`.
/// Envelope value is delay milliseconds, or `null` when retries are exhausted.
#[inline]
pub fn retry_next_delay_ms(
    policy: &solvapay_core::RetryPolicy,
    attempt: u32,
) -> Option<std::time::Duration> {
    policy.next_delay(attempt)
}

/// Binding for `selectActivePlanPurchase`.
pub use solvapay_core::purchase::select_active_plan_purchase;

/// Binding for `selectActivePurchases`.
pub use solvapay_core::purchase::select_active_purchases;

/// Binding for `shouldRetryUsageError`.
pub use solvapay_core::usage::should_retry_usage_error;

/// Binding for `validateActivatePlanParams`.
pub use solvapay_core::activation::validate_activate_plan_params;

/// Binding for `validateAttachBusinessDetailsParams`.
pub use solvapay_core::payment::validate_attach_business_details_params;

/// Binding for `validateCheckoutSessionParams`.
pub use solvapay_core::checkout::validate_checkout_session_params;

/// Binding for `validateCreatePaymentIntentParams`.
pub use solvapay_core::payment::validate_create_payment_intent_params;

/// Binding for `validateGetProductParams`.
pub use solvapay_core::product::validate_get_product_params;

/// Binding for `validateListPlansParams`.
pub use solvapay_core::plans::validate_list_plans_params;

/// Binding for `validateProcessPaymentIntentParams`.
pub use solvapay_core::payment::validate_process_payment_intent_params;

/// Binding for `validatePublicBaseUrl` — invalid → error message string; valid → `null`.
pub use solvapay_core::mcp::validate_public_base_url;

/// Binding for `validatePurchaseRef`.
pub use solvapay_core::renewal::validate_purchase_ref;

/// Binding for `validateTopupPaymentIntentParams`.
pub use solvapay_core::payment::validate_topup_payment_intent_params;

/// Driver steppers. Host loops call these; they are not integrator API.
#[doc(hidden)]
pub mod internal {
    /// Binding for `ensureCustomerNext`.
    pub use solvapay_core::ensure_customer::ensure_customer_next;

    /// Binding for `gateNext`.
    pub use solvapay_core::gate_driver::gate_next;

    /// Binding for `getHistoryNext`.
    pub use solvapay_core::history::get_history_next;

    /// Binding for `invokePayableNext`.
    pub use solvapay_core::invoke_payable::invoke_payable_next;

    /// Binding for `topupProcessNext`.
    pub use solvapay_core::topup_process::topup_process_next;
}
