/**
 * Generate `.changeset/core-surface.md` from the core-contract snapshots.
 * No file is written when the diff is empty or no unified `v*` tag exists.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { parse as parseYaml } from 'yaml'
import { REPO_PATHS, REPO_ROOT, joinRel } from '../shared/paths.js'
import { generatedEntry } from '../shared/repo-paths.js'
import { classifyCoreSurface, maxBump, type SurfaceArtifacts } from './lib/core-surface-diff.js'

const RELEASE_TRAIN_PACKAGE = '@solvapay/release-train'

const ARTIFACT_RELS = {
  bindingSymbols: generatedEntry('bindingSymbols').path,
  boundaryTypes: generatedEntry('boundaryTypes').path,
  sdkContract: REPO_PATHS.contractInputs.sdkManifest.path,
  facadeCoverage: generatedEntry('facadeCoverage').path,
} as const

export type GitShow = (ref: string, rel: string) => string | null

export function latestUnifiedTag(
  repoRoot: string,
  runner: (args: string[]) => string = args =>
    execFileSync('git', args, { cwd: repoRoot, encoding: 'utf8' }),
): string | null {
  let out: string
  try {
    out = runner(['tag', '-l', 'v*', '--sort=-v:refname'])
  } catch {
    return null
  }
  const tags = out
    .split('\n')
    .map(line => line.trim())
    .filter(name => /^v\d+\.\d+\.\d+$/.test(name))
  return tags[0] ?? null
}

export function gitShowAt(repoRoot: string, ref: string, rel: string): string | null {
  try {
    return execFileSync('git', ['show', `${ref}:${rel}`], {
      cwd: repoRoot,
      encoding: 'utf8',
    })
  } catch {
    return null
  }
}

function parseArtifact(rel: string, text: string | null): unknown {
  if (text === null || text.trim() === '') return {}
  if (rel.endsWith('.yaml') || rel.endsWith('.yml')) {
    return parseYaml(text)
  }
  return JSON.parse(text) as unknown
}

function loadCurrent(repoRoot: string): SurfaceArtifacts {
  return {
    bindingSymbols: parseArtifact(
      ARTIFACT_RELS.bindingSymbols,
      readFileSync(joinRel(repoRoot, ARTIFACT_RELS.bindingSymbols), 'utf8'),
    ),
    boundaryTypes: parseArtifact(
      ARTIFACT_RELS.boundaryTypes,
      readFileSync(joinRel(repoRoot, ARTIFACT_RELS.boundaryTypes), 'utf8'),
    ),
    sdkContract: parseArtifact(
      ARTIFACT_RELS.sdkContract,
      readFileSync(joinRel(repoRoot, ARTIFACT_RELS.sdkContract), 'utf8'),
    ),
    facadeCoverage: parseArtifact(
      ARTIFACT_RELS.facadeCoverage,
      readFileSync(joinRel(repoRoot, ARTIFACT_RELS.facadeCoverage), 'utf8'),
    ),
  }
}

function loadBaseline(repoRoot: string, ref: string, show: GitShow): SurfaceArtifacts {
  return {
    bindingSymbols: parseArtifact(
      ARTIFACT_RELS.bindingSymbols,
      show(ref, ARTIFACT_RELS.bindingSymbols),
    ),
    boundaryTypes: parseArtifact(
      ARTIFACT_RELS.boundaryTypes,
      show(ref, ARTIFACT_RELS.boundaryTypes),
    ),
    sdkContract: parseArtifact(ARTIFACT_RELS.sdkContract, show(ref, ARTIFACT_RELS.sdkContract)),
    facadeCoverage: parseArtifact(
      ARTIFACT_RELS.facadeCoverage,
      show(ref, ARTIFACT_RELS.facadeCoverage),
    ),
  }
}

export function formatCoreSurfaceChangeset(
  bump: 'major' | 'minor' | 'patch',
  findings: readonly { bump: string; summary: string }[],
): string {
  const notable = findings.filter(item => item.bump !== 'patch')
  const lead =
    notable.length > 0
      ? `Core surface: ${notable
          .map(item => item.summary)
          .slice(0, 3)
          .join(', ')}.`
      : 'Core surface: documentation or ordering updates.'
  const bullets = (notable.length > 0 ? notable : findings)
    .map(item => `- ${item.summary}`)
    .join('\n')
  return `---\n'${RELEASE_TRAIN_PACKAGE}': ${bump}\n---\n\n<!-- @generated by pnpm gen — do not edit -->\n\n${lead}\n\n${bullets}\n`
}

export function emitCoreSurfaceChangeset(
  repoRoot = REPO_ROOT,
  options: { show?: GitShow; tag?: string | null } = {},
): string | null {
  const outRel = generatedEntry('coreSurfaceChangeset').path
  const outAbs = joinRel(repoRoot, outRel)
  const tag = options.tag !== undefined ? options.tag : latestUnifiedTag(repoRoot)
  if (tag === null) {
    if (existsSync(outAbs)) unlinkSync(outAbs)
    return null
  }
  const show = options.show ?? ((ref, rel) => gitShowAt(repoRoot, ref, rel))
  const findings = classifyCoreSurface(loadBaseline(repoRoot, tag, show), loadCurrent(repoRoot))
  const bump = maxBump(findings)
  if (bump === null) {
    if (existsSync(outAbs)) unlinkSync(outAbs)
    return null
  }
  const body = formatCoreSurfaceChangeset(bump, findings)
  writeFileSync(outAbs, body)
  return body
}
