//! @generated by dto-gen (--c-bindings-out) — do not edit. Regenerate with: pnpm gen
//! Generic `op`-name dispatch for the native C ABI.
//!
//! Full Groups A–C client surface. Op → method mapping mirrors
//! `tools/conformance/live-contract/src/invoke.rs`.
#![allow(clippy::needless_borrow)]
use serde_json::{Map, Value};
use solvapay_core::SdkError;
use solvapay_dto::{
    ActivatePlanDto, AssignCreditsRequest, AttachBusinessDetailsParams, CancelPurchaseParams,
    CheckLimitsRequest, CloneProductOverrides, ConfigureMcpPlansDto, CreateCheckoutSessionRequest,
    CreateCustomerRequest, CreateCustomerSessionRequest, CreatePaymentIntentParams,
    CreatePlanParams, CreateProductRequest, CreateTopupPaymentIntentParams,
    DisableAutoRechargeParams, GetAutoRechargeParams, GetCustomerBalanceParams, GetCustomerParams,
    GetPaymentMethodParams, GetUserInfoParams, McpBootstrapDto, ProcessPaymentIntentParams,
    ReactivatePurchaseParams, SaveAutoRechargeParams, TrackUsageBulkRequest, TrackUsageRequest,
    UpdateCustomerParams, UpdatePlanRequest, UpdateProductRequest,
};
use solvapay_transport::SolvaPayClient;

use crate::error::{err_envelope, parse_args_json, run_envelope};
use crate::runtime;

/// Extracts path refs from a combined args object, leaving the remaining body.
///
/// Keys are removed in order; missing/non-string keys map to Transport errors.
fn split_path_refs(args_json: &str, keys: &[&str]) -> Result<(Vec<String>, Value), SdkError> {
    let mut map: Map<String, Value> = parse_args_json(args_json)?;
    let mut refs = Vec::with_capacity(keys.len());
    for key in keys {
        let value = map
            .remove(*key)
            .and_then(|v| v.as_str().map(str::to_owned))
            .ok_or_else(|| SdkError::transport(format!("missing {key}"), false))?;
        refs.push(value);
    }
    Ok((refs, Value::Object(map)))
}

/// Dispatches `op` against `client` with JSON `args_json`, returning an envelope string.
///
/// Unknown ops become a non-retryable Transport error envelope.
pub fn dispatch(client: &SolvaPayClient, op: &str, args_json: &str) -> String {
    match op {
        "createCustomer" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreateCustomerRequest = parse_args_json(&args_json)?;
            client.create_customer(params).await
        })),
        "updateCustomer" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, body) = split_path_refs(&args_json, &["customerRef"])?;
            let params: UpdateCustomerParams = serde_json::from_value(body).map_err(|err| {
                SdkError::transport(format!("invalid updateCustomer body: {err}"), false)
            })?;
            client.update_customer(&refs[0], params).await
        })),
        "getCustomer" => runtime::runtime().block_on(run_envelope(async move {
            let params: GetCustomerParams = parse_args_json(&args_json)?;
            client.get_customer(params).await
        })),
        "assignCredits" => runtime::runtime().block_on(run_envelope(async move {
            let params: AssignCreditsRequest = parse_args_json(&args_json)?;
            client.assign_credits(params).await
        })),
        "getCustomerBalance" => runtime::runtime().block_on(run_envelope(async move {
            let params: GetCustomerBalanceParams = parse_args_json(&args_json)?;
            client.get_customer_balance(params).await
        })),
        "getUserInfo" => runtime::runtime().block_on(run_envelope(async move {
            let params: GetUserInfoParams = parse_args_json(&args_json)?;
            client.get_user_info(params).await
        })),
        "createCheckoutSession" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreateCheckoutSessionRequest = parse_args_json(&args_json)?;
            client.create_checkout_session(params).await
        })),
        "createCustomerSession" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreateCustomerSessionRequest = parse_args_json(&args_json)?;
            client.create_customer_session(params).await
        })),
        "getMerchant" => {
            runtime::runtime().block_on(run_envelope(async move { client.get_merchant().await }))
        }
        "getPlatformConfig" => {
            runtime::runtime().block_on(run_envelope(
                async move { client.get_platform_config().await },
            ))
        }
        "createPaymentIntent" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreatePaymentIntentParams = parse_args_json(&args_json)?;
            client.create_payment_intent(params).await
        })),
        "createTopupPaymentIntent" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreateTopupPaymentIntentParams = parse_args_json(&args_json)?;
            client.create_topup_payment_intent(params).await
        })),
        "processPaymentIntent" => runtime::runtime().block_on(run_envelope(async move {
            let params: ProcessPaymentIntentParams = parse_args_json(&args_json)?;
            client.process_payment_intent(params).await
        })),
        "attachBusinessDetails" => runtime::runtime().block_on(run_envelope(async move {
            let params: AttachBusinessDetailsParams = parse_args_json(&args_json)?;
            client.attach_business_details(params).await
        })),
        "activatePlan" => runtime::runtime().block_on(run_envelope(async move {
            let params: ActivatePlanDto = parse_args_json(&args_json)?;
            client.activate_plan(params).await
        })),
        "checkLimits" => runtime::runtime().block_on(run_envelope(async move {
            let params: CheckLimitsRequest = parse_args_json(&args_json)?;
            client.check_limits(params).await
        })),
        "trackUsage" => runtime::runtime().block_on(run_envelope(async move {
            let params: TrackUsageRequest = parse_args_json(&args_json)?;
            client.track_usage(params).await
        })),
        "trackUsageBulk" => runtime::runtime().block_on(run_envelope(async move {
            let params: TrackUsageBulkRequest = parse_args_json(&args_json)?;
            client.track_usage_bulk(params).await
        })),
        "getProduct" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, _) = split_path_refs(&args_json, &["productRef"])?;
            client.get_product(&refs[0]).await
        })),
        "listProducts" => {
            runtime::runtime().block_on(run_envelope(async move { client.list_products().await }))
        }
        "createProduct" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreateProductRequest = parse_args_json(&args_json)?;
            client.create_product(params).await
        })),
        "updateProduct" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, body) = split_path_refs(&args_json, &["productRef"])?;
            let params: UpdateProductRequest = serde_json::from_value(body).map_err(|err| {
                SdkError::transport(format!("invalid updateProduct body: {err}"), false)
            })?;
            client.update_product(&refs[0], params).await
        })),
        "deleteProduct" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, _) = split_path_refs(&args_json, &["productRef"])?;
            client.delete_product(&refs[0]).await
        })),
        "cloneProduct" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, body) = split_path_refs(&args_json, &["productRef"])?;
            let overrides: CloneProductOverrides = serde_json::from_value(body).map_err(|err| {
                SdkError::transport(format!("invalid cloneProduct body: {err}"), false)
            })?;
            client.clone_product(&refs[0], Some(overrides)).await
        })),
        "bootstrapMcpProduct" => runtime::runtime().block_on(run_envelope(async move {
            let params: McpBootstrapDto = parse_args_json(&args_json)?;
            client.bootstrap_mcp_product(params).await
        })),
        "configureMcpPlans" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, body) = split_path_refs(&args_json, &["productRef"])?;
            let params: ConfigureMcpPlansDto = serde_json::from_value(body).map_err(|err| {
                SdkError::transport(format!("invalid configureMcpPlans body: {err}"), false)
            })?;
            client.configure_mcp_plans(&refs[0], params).await
        })),
        "listPlans" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, _) = split_path_refs(&args_json, &["productRef"])?;
            client.list_plans(&refs[0]).await
        })),
        "createPlan" => runtime::runtime().block_on(run_envelope(async move {
            let params: CreatePlanParams = parse_args_json(&args_json)?;
            client.create_plan(params).await
        })),
        "updatePlan" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, body) = split_path_refs(&args_json, &["productRef", "planRef"])?;
            let params: UpdatePlanRequest = serde_json::from_value(body).map_err(|err| {
                SdkError::transport(format!("invalid updatePlan body: {err}"), false)
            })?;
            client.update_plan(&refs[0], &refs[1], params).await
        })),
        "deletePlan" => runtime::runtime().block_on(run_envelope(async move {
            let (refs, _) = split_path_refs(&args_json, &["productRef", "planRef"])?;
            client.delete_plan(&refs[0], &refs[1]).await
        })),
        "cancelPurchase" => runtime::runtime().block_on(run_envelope(async move {
            let params: CancelPurchaseParams = parse_args_json(&args_json)?;
            client.cancel_purchase(params).await
        })),
        "reactivatePurchase" => runtime::runtime().block_on(run_envelope(async move {
            let params: ReactivatePurchaseParams = parse_args_json(&args_json)?;
            client.reactivate_purchase(params).await
        })),
        "getPaymentMethod" => runtime::runtime().block_on(run_envelope(async move {
            let params: GetPaymentMethodParams = parse_args_json(&args_json)?;
            client.get_payment_method(params).await
        })),
        "getAutoRecharge" => runtime::runtime().block_on(run_envelope(async move {
            let params: GetAutoRechargeParams = parse_args_json(&args_json)?;
            client.get_auto_recharge(params).await
        })),
        "saveAutoRecharge" => runtime::runtime().block_on(run_envelope(async move {
            let params: SaveAutoRechargeParams = parse_args_json(&args_json)?;
            client.save_auto_recharge(params).await
        })),
        "disableAutoRecharge" => runtime::runtime().block_on(run_envelope(async move {
            let params: DisableAutoRechargeParams = parse_args_json(&args_json)?;
            client.disable_auto_recharge(params).await
        })),
        "mcpBootstrap" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::McpBootstrapParams = parse_args_json(&args_json)?;
            client.mcp_bootstrap(params).await
        })),
        "mcpCallBuiltinTool" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::McpCallBuiltinToolParams = parse_args_json(&args_json)?;
            client.mcp_call_builtin_tool(params).await
        })),
        "mcpReadResource" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::McpReadResourceParams = parse_args_json(&args_json)?;
            client.mcp_read_resource(params).await
        })),
        "mcpResolveAuth" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::McpResolveAuthParams = parse_args_json(&args_json)?;
            client.mcp_resolve_auth(params).await
        })),
        "mcpOauthRequest" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::McpOauthRequestParams = parse_args_json(&args_json)?;
            client.mcp_oauth_request(params).await
        })),
        "mcpDispatch" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::McpDispatchParams = parse_args_json(&args_json)?;
            client.mcp_dispatch(params).await
        })),
        "fetchJwks" => runtime::runtime().block_on(run_envelope(async move {
            let params: solvapay_transport::FetchJwksParams = parse_args_json(&args_json)?;
            client.fetch_jwks(params).await
        })),
        other => err_envelope(&SdkError::transport(format!("unknown op: {other}"), false)),
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_docs_in_private_items
)]
mod tests {
    use super::*;
    use serde_json::Value;
    use solvapay_transport::{ClientShell, SharedTransport, Transport};
    use std::sync::Arc;

    struct NoopTransport;

    impl Transport for NoopTransport {
        fn send(
            &self,
            _request: solvapay_transport::HttpRequest,
        ) -> solvapay_transport::BoxFuture<'_, Result<solvapay_transport::HttpResponse, SdkError>>
        {
            Box::pin(async { Err(SdkError::transport("noop", false)) })
        }
    }

    fn dummy_client() -> SolvaPayClient {
        let transport: SharedTransport = Arc::new(NoopTransport);
        SolvaPayClient::new(ClientShell::new(transport, "sk_test"))
    }

    #[test]
    fn unknown_op_is_transport_error_envelope() {
        let env: Value =
            serde_json::from_str(&dispatch(&dummy_client(), "notARealOp", "{}")).unwrap();
        assert_eq!(env["ok"], false);
        assert_eq!(env["error"]["kind"], "Transport");
        assert!(env["error"]["message"]
            .as_str()
            .unwrap()
            .contains("unknown op: notARealOp"));
    }
}
