# @generated by dto-gen (--rb-parity-out) — do not edit. Regenerate with: pnpm gen

# frozen_string_literal: true

require "json"
require "minitest/autorun"
require "solvapay"

class SignatureParityGeneratedTest < Minitest::Test
  OPERATION_SIGNATURES = {
    "activate_plan" => [[:keyreq, :params]],
    "assign_credits" => [[:keyreq, :params]],
    "attach_business_details" => [[:keyreq, :params]],
    "bootstrap_mcp_product" => [[:keyreq, :params]],
    "cancel_purchase" => [[:keyreq, :params]],
    "check_limits" => [[:keyreq, :params]],
    "clone_product" => [[:keyreq, :product_ref], [:key, :overrides]],
    "configure_mcp_plans" => [[:keyreq, :product_ref], [:keyreq, :params]],
    "create_checkout_session" => [[:keyreq, :params]],
    "create_customer" => [[:keyreq, :params]],
    "create_customer_session" => [[:keyreq, :params]],
    "create_payment_intent" => [[:keyreq, :params]],
    "create_plan" => [[:keyreq, :params]],
    "create_product" => [[:keyreq, :params]],
    "create_topup_payment_intent" => [[:keyreq, :params]],
    "delete_plan" => [[:keyreq, :product_ref], [:keyreq, :plan_ref]],
    "delete_product" => [[:keyreq, :product_ref]],
    "disable_auto_recharge" => [[:keyreq, :params]],
    "fetch_jwks" => [[:keyreq, :params]],
    "get_auto_recharge" => [[:keyreq, :params]],
    "get_customer" => [[:keyreq, :params]],
    "get_customer_balance" => [[:keyreq, :params]],
    "get_merchant" => [],
    "get_payment_method" => [[:keyreq, :params]],
    "get_platform_config" => [],
    "get_product" => [[:keyreq, :product_ref]],
    "get_user_info" => [[:keyreq, :params]],
    "list_plans" => [[:keyreq, :product_ref]],
    "list_products" => [],
    "mcp_bootstrap" => [[:keyreq, :params]],
    "mcp_call_builtin_tool" => [[:keyreq, :params]],
    "mcp_dispatch" => [[:keyreq, :params]],
    "mcp_oauth_request" => [[:keyreq, :params]],
    "mcp_read_resource" => [[:keyreq, :params]],
    "process_payment_intent" => [[:keyreq, :params]],
    "reactivate_purchase" => [[:keyreq, :params]],
    "save_auto_recharge" => [[:keyreq, :params]],
    "track_usage" => [[:keyreq, :params]],
    "track_usage_bulk" => [[:keyreq, :params]],
    "update_customer" => [[:keyreq, :customer_ref], [:keyreq, :params]],
    "update_plan" => [[:keyreq, :product_ref], [:keyreq, :plan_ref], [:keyreq, :params]],
    "update_product" => [[:keyreq, :product_ref], [:keyreq, :params]],
  }.freeze

  GENERATED_HELPERS = %w[
    assert_valid_product_ref
    billing_cycle
    build_gate_message
    build_nudge_message
    build_paywall_gate
    charges
    classify_paywall_state
    counts_usage
    credits_per_unit_from_balance
    credits_to_display_minor_units
    derive_tax_id_type
    evaluate_product_readiness
    format_price
    format_subtotal_label
    format_vat_summary_label
    get_seller_tax_identifier_display_label
    get_tax_id_example
    get_tax_id_field_label
    get_tax_id_helper_text
    headline_charges
    included_units
    is_zero_decimal_currency
    meter_name
    minor_units_per_major
    paywall_error_to_client_payload
    pegged_credits_per_unit
    per_unit_charge
    require_product_ref
    resolve_seller_identity_display
    resolve_tax_behavior
    resolve_tax_treatment_note
    should_show_tax_row
    tier_bands
    tier_meters
    to_major_units
    trial_days
    usage_rate
    validate_business_details
  ].freeze

  EXPECTED_LIMITS_CACHE_TTL_MS = 10000
  EXPECTED_MAX_RETRIES = 2
  EXPECTED_INITIAL_DELAY_MS = 500
  EXPECTED_CUSTOMER_DEDUP_TTL_MS = 60000
  EXPECTED_CUSTOMER_DEDUP_MAX_CACHE_SIZE = 1000
  EXPECTED_ANONYMOUS_CUSTOMER_REF = "anonymous"
  EXPECTED_REQUEST_ID_FORMAT = "solvapay_{epochMs}_{random9}"
  EXPECTED_USAGE_ACTION_TYPE = "api_call"

  def test_all_42_client_operations_have_exact_keyword_signatures
    assert_equal 42, OPERATION_SIGNATURES.length
    OPERATION_SIGNATURES.each do |name, expected|
      method = SolvaPay::Client.instance_method(name)
      assert_equal expected, method.parameters, name
      refute SolvaPay::Client.method_defined?("#{name}_blocking"), name
      refute SolvaPay::Client.method_defined?("#{name}_async"), name
    end
  end

  def test_catalogued_generated_helpers_are_module_functions
    GENERATED_HELPERS.each { |name| assert_respond_to SolvaPay, name }
    assert_respond_to SolvaPay, :create
    assert_instance_of SolvaPay::Payable, SolvaPay.create(api_client: Object.new).payable(product: "prd_x")
  end

  def test_runtime_defaults_are_exercised_through_host_bridge
    assert_equal EXPECTED_LIMITS_CACHE_TTL_MS, SolvaPay::DEFAULT_LIMITS_CACHE_TTL_MS
    assert_equal EXPECTED_CUSTOMER_DEDUP_TTL_MS, SolvaPay::CUSTOMER_CACHE_TTL_MS
    assert_equal EXPECTED_CUSTOMER_DEDUP_MAX_CACHE_SIZE, SolvaPay::CUSTOMER_DEDUP_MAX_CACHE_SIZE
    assert_equal EXPECTED_ANONYMOUS_CUSTOMER_REF, SolvaPay::ANONYMOUS_CUSTOMER_REF
    assert_equal EXPECTED_REQUEST_ID_FORMAT, SolvaPay::REQUEST_ID_FORMAT
    assert_equal EXPECTED_USAGE_ACTION_TYPE, SolvaPay::USAGE_ACTION_TYPE
    original = SolvaPay::NativeDispatch.method(:call_sync)
    captured = nil
    SolvaPay::NativeDispatch.define_singleton_method(:call_sync) do |_name, args|
      captured = args
      0
    end
    attempts = 0
    value = SolvaPay.with_retry(sleeper: ->(_seconds) {}) do
      attempts += 1
      raise "retry" if attempts == 1
      :ok
    end
    assert_equal :ok, value
    assert_equal EXPECTED_MAX_RETRIES, captured["maxRetries"]
    assert_equal EXPECTED_INITIAL_DELAY_MS, captured["initialDelay"]
  ensure
    SolvaPay::NativeDispatch.define_singleton_method(:call_sync) { |name, args| original.call(name, args) } if original
  end

  def test_public_error_reconstruction_preserves_fields
    error = SolvaPay::NativeDispatch.reconstruct_error(
      "kind" => "Api", "message" => "bad", "status" => 409, "code" => "conflict",
    )
    assert_instance_of SolvaPay::SolvaPayError, error
    assert_equal 409, error.status
    assert_equal "conflict", error.code
    gate = { "kind" => "payment_required", "product" => "prd_x" }
    paywall = SolvaPay::NativeDispatch.reconstruct_error(
      "kind" => "Paywall", "message" => "blocked", "gate" => gate,
    )
    assert_equal gate, paywall.structured_content
  end
end
