"""Minimal stub for the compiled extension module (Step 42T)."""

from __future__ import annotations

class SolvaPayError(Exception):
    code: str | None
    status: int | None
    def __init__(
        self,
        message: str,
        *,
        code: str | None = None,
        status: int | None = None,
    ) -> None: ...

class SolvaPayClient:
    def __init__(self, api_key: str, api_base_url: str | None = None) -> None: ...
    @staticmethod
    def _for_fixtures(
        api_key: str,
        api_base_url: str,
        clock_unix_ms: int | None = None,
        rng_seed: int | None = None,
    ) -> SolvaPayClient: ...
    async def check_limits(self, args_json: str) -> str: ...
    def check_limits_blocking(self, args_json: str) -> str: ...
    async def track_usage(self, args_json: str) -> str: ...
    def track_usage_blocking(self, args_json: str) -> str: ...
    async def get_customer(self, args_json: str) -> str: ...
    def get_customer_blocking(self, args_json: str) -> str: ...
    async def create_customer(self, args_json: str) -> str: ...
    def create_customer_blocking(self, args_json: str) -> str: ...

def version() -> str: ...
def native_build_info() -> str: ...
def verify_webhook(body: str, signature: str, secret: str) -> str: ...
def _verify_webhook_at(
    body: str, signature: str, secret: str, now_unix_secs: int
) -> str: ...
