# @generated by dto-gen (--py-defaults-out) — do not edit. Regenerate with: pnpm gen

"""Frozen contract defaults (`defaults:` in sdk-contract.yaml)."""

from __future__ import annotations

_MAX_RETRIES = 2
_INITIAL_DELAY_MS = 500
_RETRY_BACKOFF = "fixed"
_WEBHOOK_TOLERANCE_SEC = 300
_DEFAULT_LIMITS_CACHE_TTL_MS = 10_000
_CUSTOMER_DEDUP_TTL_MS = 60_000
_CUSTOMER_DEDUP_MAX_CACHE_SIZE = 1000
_ANONYMOUS_CUSTOMER_REF = "anonymous"
_REQUEST_ID_FORMAT = "solvapay_{epochMs}_{random9}"
_USAGE_ACTION_TYPE = "api_call"
_PAYMENT_IDEMPOTENCY_KEY_FORMAT = "payment-{planRef}-{epochMs}-{random9}"
_TOPUP_IDEMPOTENCY_KEY_FORMAT = "topup-{epochMs}-{random9}"
_GO_CONTEXT_FIRST_PARAM = True
_PAYMENT_REQUIRED = "Payment required"

