#!/usr/bin/env node
// Extracts C-dispatch chrome from sdks/capi/src/dispatch.rs into
// assets/c-emit.snapshot.json. `split_path_refs` is taken from the committed
// dispatch when present, otherwise copied from the Go guest args.rs (same
// helper, private in the C file).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..', '..', '..');
const DISPATCH = join(REPO_ROOT, 'sdks', 'capi', 'src', 'dispatch.rs');
const GO_ARGS = join(REPO_ROOT, 'sdks', 'go', 'wasm', 'src', 'args.rs');
const OUT_PATH = join(REPO_ROOT, 'tools', 'codegen', 'dto-gen', 'assets', 'c-emit.snapshot.json');

const CANONICAL_HEADER = `//! Generic \`op\`-name dispatch for the native C ABI.
//!
//! Full Groups A–C client surface. Op → method mapping mirrors
//! \`tools/conformance/live-contract/src/invoke.rs\`.
#![allow(clippy::needless_borrow)]
`;

function extractBlock(src, startNeedle) {
  const start = src.indexOf(startNeedle);
  if (start < 0) return null;
  let depth = 0;
  let saw = false;
  for (let i = start; i < src.length; i += 1) {
    const ch = src[i];
    if (ch === '{') {
      depth += 1;
      saw = true;
    } else if (ch === '}') {
      depth -= 1;
      if (saw && depth === 0) {
        return src.slice(start, i + 1);
      }
    }
  }
  throw new Error(`unclosed block starting at ${startNeedle}`);
}

function stripGenerated(header) {
  return header.replace(/^\/\/! @generated by dto-gen — do not edit.\n/, '');
}

function goSplitPathRefs() {
  const src = readFileSync(GO_ARGS, 'utf8');
  const block = extractBlock(src, 'pub(crate) fn split_path_refs');
  if (block === null) {
    throw new Error('Go args.rs missing split_path_refs');
  }
  const docs = `/// Extracts path refs from a combined args object, leaving the remaining body.
///
/// Keys are removed in order; missing/non-string keys map to Transport errors.
`;
  return docs + block.replace('pub(crate) fn split_path_refs', 'fn split_path_refs');
}

const src = readFileSync(DISPATCH, 'utf8');
const testsIdx = src.indexOf('#[cfg(test)]');
if (testsIdx < 0) {
  throw new Error('dispatch.rs missing #[cfg(test)]');
}
const testsTrailer = src.slice(testsIdx).replace(/\s*$/, '\n');

const otherIdx = src.indexOf('other =>');
if (otherIdx < 0) {
  throw new Error('dispatch.rs missing unknown-op arm');
}
const otherLineStart = src.lastIndexOf('\n', otherIdx) + 1;
const otherEnd = src.indexOf('\n', otherIdx);
const postamble = `${src.slice(otherLineStart, otherEnd).trimEnd()}\n    }\n}\n`;

const dispatchFn = src.indexOf('pub fn dispatch');
if (dispatchFn < 0) {
  throw new Error('dispatch.rs missing pub fn dispatch');
}
const dispatchDoc = src.indexOf('/// Dispatches');
const dispatchStart =
  dispatchDoc >= 0 && dispatchDoc < dispatchFn ? dispatchDoc : dispatchFn;
const matchIdx = src.indexOf('match op {', dispatchFn);
if (matchIdx < 0) {
  throw new Error('dispatch.rs missing match op');
}
const dispatchOpen =
  src
    .slice(dispatchStart, matchIdx + 'match op {'.length)
    .replace('_args_json', 'args_json') + '\n';

const firstUse = src.indexOf('\nuse ');
const headerStart = src.startsWith('//!') ? 0 : src.indexOf('//!');
let header = stripGenerated(
  src.slice(headerStart < 0 ? 0 : headerStart, firstUse).replace(/^\n+/, ''),
);
if (header.includes('Scaffold allowlist') || header.includes('getMerchant` only')) {
  header = CANONICAL_HEADER;
}

let splitPathRefs = extractBlock(src, 'fn split_path_refs');
if (splitPathRefs === null) {
  splitPathRefs = goSplitPathRefs();
}

const usesPrefix = `use serde_json::{Map, Value};
use solvapay_core::SdkError;
`;
const usesSuffix = `use solvapay_transport::SolvaPayClient;

use crate::error::{err_envelope, parse_args_json, run_envelope};
use crate::runtime;
`;

const snapshot = {
  header: header.trimEnd() + '\n',
  usesPrefix,
  usesSuffix,
  splitPathRefs: splitPathRefs.trimEnd() + '\n',
  dispatchOpen,
  postamble,
  testsTrailer,
};

writeFileSync(OUT_PATH, `${JSON.stringify(snapshot, null, 2)}\n`);
console.log(`wrote ${OUT_PATH}`);
