// Code generated by dto-gen. DO NOT EDIT.
// @generated by dto-gen (--go-conformance-out) — do not edit. Regenerate with: pnpm gen

package contract

import (
	"fmt"
	"time"
)

const clockLayout = "2006-01-02T15:04:05Z"

// UnixSecs parses `YYYY-MM-DDTHH:MM:SSZ` to unix seconds.
func UnixSecs(clock string) (int64, error) {
	if len(clock) != 20 || clock[len(clock)-1] != 'Z' {
		return 0, fmt.Errorf("input.clock must be YYYY-MM-DDTHH:MM:SSZ, got %q", clock)
	}
	t, err := time.Parse(clockLayout, clock)
	if err != nil {
		return 0, fmt.Errorf("input.clock must be YYYY-MM-DDTHH:MM:SSZ, got %q", clock)
	}
	return t.Unix(), nil
}

// UnixMs parses `YYYY-MM-DDTHH:MM:SSZ` to unix milliseconds.
func UnixMs(clock string) (int64, error) {
	secs, err := UnixSecs(clock)
	if err != nil {
		return 0, err
	}
	return secs * 1000, nil
}
