// Code generated by dto-gen. DO NOT EDIT.
// @generated by dto-gen (--go-conformance-out) — do not edit. Regenerate with: pnpm gen

package contract

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
)

// CapturedRequest is one HTTP call recorded by StubBackend.
type CapturedRequest struct {
	Method string
	Path   string
}

// StubRoute is one programmed method+path → response mapping.
type StubRoute struct {
	Method string
	Path   string
	Status int
	Body   any
}

// StubBackend serves programmed responses and records method/path.
type StubBackend struct {
	Status   int
	Body     any
	Routes   []StubRoute
	Captured []CapturedRequest
	server   *httptest.Server
}

// StubFromWire builds a backend from a fixture wire block.
func StubFromWire(wire *Wire) *StubBackend {
	stub := &StubBackend{Status: 200}
	if wire == nil {
		return stub
	}
	if len(wire.Exchanges) > 0 {
		for _, ex := range wire.Exchanges {
			stub.Routes = append(stub.Routes, StubRoute{
				Method: ex.Request.Method,
				Path:   ex.Request.Path,
				Status: ex.Response.Status,
				Body:   ex.Response.Body,
			})
		}
		return stub
	}
	stub.Status = wire.Response.Status
	stub.Body = wire.Response.Body
	return stub
}

// Start launches the stub server.
func (s *StubBackend) Start() {
	backend := s
	s.server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		backend.Captured = append(backend.Captured, CapturedRequest{
			Method: r.Method,
			// EscapedPath keeps encodeURIComponent segments (%2F) so wire
			// fixtures match the bytes the client sent (SEC-003).
			Path: r.URL.EscapedPath(),
		})
		status := backend.Status
		payload := backend.Body
		if len(backend.Routes) > 0 {
			matched := false
			for _, route := range backend.Routes {
				if route.Method == r.Method && route.Path == r.URL.EscapedPath() {
					status = route.Status
					payload = route.Body
					matched = true
					break
				}
			}
			if !matched {
				http.NotFound(w, r)
				return
			}
		}
		var data []byte
		contentType := "application/json"
		switch v := payload.(type) {
		case nil:
			data = []byte{}
			contentType = "application/octet-stream"
		case string:
			data = []byte(v)
			contentType = "text/plain; charset=utf-8"
		default:
			encoded, err := json.Marshal(v)
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			data = encoded
			if len(data) > 0 && data[0] == '"' {
				var str string
				if err := json.Unmarshal(data, &str); err == nil {
					data = []byte(str)
				}
			}
		}
		w.Header().Set("Content-Type", contentType)
		w.WriteHeader(status)
		if r.Method != http.MethodHead && len(data) > 0 {
			_, _ = io.WriteString(w, string(data))
		}
	}))
}

// BaseURL is the stub origin.
func (s *StubBackend) BaseURL() string {
	if s.server == nil {
		panic("stub backend is not running")
	}
	return s.server.URL
}

// Close shuts the stub down.
func (s *StubBackend) Close() {
	if s.server != nil {
		s.server.Close()
		s.server = nil
	}
}

// AssertWireRequest checks method and path only.
//
// Go's ClientConfig cannot inject clockMs / rngSeed, so header and body
// assertions (seeded idempotency keys) are not expressible.
func AssertWireRequest(actual CapturedRequest, expected WireRequest) error {
	if actual.Method != expected.Method {
		return fmt.Errorf("wire.request.method mismatch: %q != %q", actual.Method, expected.Method)
	}
	if actual.Path != expected.Path {
		return fmt.Errorf("wire.request.path mismatch: %q != %q", actual.Path, expected.Path)
	}
	return nil
}
