//! Emit Rust signature-parity tests from canonical catalog IR (§2.8 / Step 47).

use std::fmt::Write as _;

use crate::emit_client_rs::client_operations;
use crate::error::GenResult;
use crate::ir::Ir;

const HEADER: &str = "// @generated by dto-gen — do not edit. Regenerate with --rs-parity-out.\n\n";

/// Emits `tests/signature_parity_generated.rs`.
///
/// # Errors
///
/// Returns formatting failures as [`crate::error::GenError`].
pub fn emit_parity_suite_rs(ir: &Ir) -> GenResult<String> {
    let ops = client_operations(ir);
    let defaults = ops
        .first()
        .map(|(entry, _)| entry.defaults.clone())
        .unwrap_or_default();

    let mut output = String::from(HEADER);
    output.push_str(
        "//! Generated signature-parity suite (§2.8) — presence, arity, sync matrix, defaults.\n\n\
         #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]\n\n\
         use solvapay::{Client, Config, RetryPolicy, DEFAULT_LIMITS_CACHE_TTL_MS};\n\
         #[cfg(feature = \"blocking\")]\n\
         use solvapay::blocking::BlockingClient;\n\n",
    );

    output.push_str(
        "/// Catalogued client operation signatures: name → &[(param_name, required)].\n\
         pub const OPERATION_SIGNATURES: &[(&str, &[(&str, bool)])] = &[\n",
    );
    for (entry, _) in &ops {
        let params = entry
            .params
            .iter()
            .map(|param| {
                format!(
                    "(\"{}\", {})",
                    param.names.rust,
                    if param.required { "true" } else { "false" }
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(output, "    (\"{}\", &[{params}]),", entry.names.rust);
    }
    output.push_str("];\n\n");

    let _ = writeln!(
        output,
        "/// Frozen limits-cache TTL from the contract manifest `defaults:`.\n\
         const EXPECTED_LIMITS_CACHE_TTL_MS: u64 = {};",
        defaults.limits_cache_ttl_ms
    );
    let _ = writeln!(
        output,
        "/// Frozen retry max from the contract manifest `defaults:`.\n\
         const EXPECTED_MAX_RETRIES: u32 = {};",
        defaults.max_retries
    );
    let _ = writeln!(
        output,
        "/// Frozen initial retry delay from the contract manifest `defaults:`.\n\
         const EXPECTED_INITIAL_DELAY_MS: u64 = {};\n",
        defaults.initial_delay_ms
    );

    output.push_str(
        "/// Compile-time surface assertion: each catalogued method is resolvable.\n\
         /// Associated-fn items prove presence + sync/async availability; param\n\
         /// arity/names live in [`OPERATION_SIGNATURES`]. Never executed.\n\
         #[allow(dead_code, unused_variables)]\n\
         fn _assert_surface() {\n",
    );
    for (entry, _) in &ops {
        let name = &entry.names.rust;
        let _ = writeln!(output, "    let _{name} = Client::{name};");
    }
    output.push_str("\n    #[cfg(feature = \"blocking\")]\n    {\n");
    for (entry, _) in &ops {
        let name = &entry.names.rust;
        let _ = writeln!(output, "        let _{name} = BlockingClient::{name};");
    }
    output.push_str("    }\n}\n\n");

    output.push_str(
        "#[test]\n\
         fn operation_signatures_count_is_36() {\n\
         \x20   assert_eq!(OPERATION_SIGNATURES.len(), 36);\n\
         }\n\n\
         #[test]\n\
         fn operation_signatures_are_sorted_unique() {\n\
         \x20   let names: Vec<&str> = OPERATION_SIGNATURES.iter().map(|(n, _)| *n).collect();\n\
         \x20   let mut sorted = names.clone();\n\
         \x20   sorted.sort_unstable();\n\
         \x20   sorted.dedup();\n\
         \x20   assert_eq!(names, sorted);\n\
         }\n\n\
         #[test]\n\
         fn runtime_defaults_match_config_and_retry_policy() {\n\
         \x20   assert_eq!(EXPECTED_LIMITS_CACHE_TTL_MS, DEFAULT_LIMITS_CACHE_TTL_MS);\n\
         \x20   assert_eq!(EXPECTED_LIMITS_CACHE_TTL_MS, Config::default().limits_cache_ttl_ms);\n\
         \x20   let retry = RetryPolicy::default();\n\
         \x20   assert_eq!(EXPECTED_MAX_RETRIES, retry.max_retries);\n\
         \x20   assert_eq!(EXPECTED_INITIAL_DELAY_MS, retry.initial_delay_ms);\n\
         }\n",
    );

    Ok(output)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn emits_count_assert_defaults_and_no_tautologies() {
        let ir = Ir {
            types: BTreeMap::new(),
            overlay_helpers: BTreeMap::new(),
            overlays: BTreeMap::new(),
            routes: vec![],
            error_templates: crate::ir::IrErrorTemplates::default(),
            entry_points: BTreeMap::new(),
            binding_symbols: BTreeMap::new(),
        };
        let output = emit_parity_suite_rs(&ir).unwrap();
        assert!(output.contains("assert_eq!(OPERATION_SIGNATURES.len(), 36)"));
        assert!(output.contains("EXPECTED_LIMITS_CACHE_TTL_MS"));
        assert!(output.contains("EXPECTED_MAX_RETRIES"));
        assert!(output.contains("EXPECTED_INITIAL_DELAY_MS"));
        assert!(output.contains("_assert_surface"));
        assert!(output.contains("#[cfg(feature = \"blocking\")]"));
        assert!(!output.contains("2 == 2"));
        assert!(!output.contains("or true"));
    }
}
