//! Emit Ruby native marshalling and the single envelope reconstruction path.

use serde_json::Value;

use crate::chrome::{chrome_str, load_snapshot, symbols_for};
use crate::error::{GenError, GenResult};
use crate::header::{generated_header, CommentStyle};
use crate::ir::{Ir, IrBindingArtifact, IrBindingSymbol};

const SNAPSHOT: &str = include_str!("../assets/native-rb-emit.snapshot.json");

/// Emits `lib/solvapay/_native.rb` from binding IR.
///
/// # Errors
///
/// Returns [`GenError::Parse`] when the embedded chrome snapshot is malformed.
pub fn emit_native_rb(ir: &Ir) -> GenResult<String> {
    let chrome: Value = load_snapshot(SNAPSHOT, "native-rb snapshot")?;
    let file = chrome
        .pointer("/files/native")
        .ok_or_else(|| GenError::Parse("native-rb snapshot missing files.native".into()))?;
    let preamble = chrome_str(file, &["preamble"], "native-rb")?;
    let bridge = chrome_str(file, &["clientToSyncBridge"], "native-rb")?;
    let postamble = chrome_str(file, &["postamble"], "native-rb")?;

    let clients = render_names(symbols_for(ir, IrBindingArtifact::Client));
    let mut sync = symbols_for(ir, IrBindingArtifact::Decisions);
    sync.extend(symbols_for(ir, IrBindingArtifact::PayloadBuilders));
    sync.sort_by(|left, right| {
        left.emit_order
            .cmp(&right.emit_order)
            .then(left.id.cmp(&right.id))
    });

    let header = format!(
        "{}# frozen_string_literal: true\n\n",
        generated_header(CommentStyle::Hash, "native-rb-out")
    );
    Ok(format!(
        "{header}{preamble}{clients}{bridge}{}{postamble}",
        render_names(sync)
    ))
}

fn render_names(symbols: Vec<&IrBindingSymbol>) -> String {
    symbols
        .iter()
        .map(|symbol| format!("      {}", symbol.names.rb))
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::ir::{
        IrBindingCall, IrBindingCatalogLink, IrEnvelopeMode, IrLangNames, IrSerializeKind,
        IrSyncKind,
    };
    use std::collections::BTreeMap;

    fn empty_ir() -> Ir {
        Ir {
            types: BTreeMap::new(),
            overlay_helpers: BTreeMap::new(),
            overlays: BTreeMap::new(),
            routes: vec![],
            error_templates: crate::ir::IrErrorTemplates::default(),
            entry_points: BTreeMap::new(),
            binding_symbols: BTreeMap::new(),
            core_types: BTreeMap::new(),
            core_types_ts: Default::default(),
            core_fns: Default::default(),
            transport_fns: Default::default(),
        }
    }

    fn symbol(id: &str, artifact: IrBindingArtifact, order: u32) -> IrBindingSymbol {
        IrBindingSymbol {
            id: id.into(),
            core: String::new(),
            names: IrLangNames {
                ts: id.into(),
                py: id.into(),
                rb: id.into(),
                go: id.into(),
                rust: id.into(),
                c: id.into(),
            },
            catalog: IrBindingCatalogLink::None,
            args: vec![],
            split_path_refs: vec![],
            return_shape: "value".into(),
            sync: IrSyncKind::Sync,
            envelope: IrEnvelopeMode::Sync,
            artifact,
            emit_order: order,
            section: None,
            doc: String::new(),
            doc_wasm: None,
            rust_fn_name: id.into(),
            call: IrBindingCall::Wrap {
                serialize: IrSerializeKind::ToValue,
                args: vec![],
            },
            verbatim_body: None,
            verbatim_body_wasm: None,
            dto_type: None,
            core_call: None,
            client_call_args: vec![],
            ts_wrapper: None,
        }
    }

    #[test]
    fn emits_deterministic_client_and_sync_sets() {
        let mut ir = empty_ir();
        ir.binding_symbols.insert(
            "b".into(),
            symbol("get_merchant", IrBindingArtifact::Client, 2),
        );
        ir.binding_symbols.insert(
            "a".into(),
            symbol("check_limits", IrBindingArtifact::Client, 1),
        );
        ir.binding_symbols.insert(
            "c".into(),
            symbol("classify_customer_ref", IrBindingArtifact::Decisions, 1),
        );
        let output = emit_native_rb(&ir).unwrap();
        assert!(output.starts_with("# @generated by dto-gen"));
        assert!(output.find("check_limits").unwrap() < output.find("get_merchant").unwrap());
        assert!(output.contains("classify_customer_ref"));
        assert!(output.contains("def reconstruct_error"));
    }
}
