//! Canonical `@generated` banners for every dto-gen emitter.

/// Comment syntax for a generated-file banner.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CommentStyle {
    /// `// …`
    LineSlash,
    /// `//! …`
    ModuleDoc,
    /// `/** … */` block
    Block,
    /// `# …`
    Hash,
    /// `/* … */` (C)
    CBlock,
    /// Go: `// Code generated … DO NOT EDIT.` prologue plus `// @generated …`
    Go,
}

/// `@generated by dto-gen (--<flag>) — do not edit. Regenerate with: pnpm gen`
pub(crate) fn generated_header(style: CommentStyle, flag: &str) -> String {
    let body = format!("@generated by dto-gen (--{flag}) — do not edit. Regenerate with: pnpm gen");
    match style {
        CommentStyle::LineSlash => format!("// {body}\n"),
        CommentStyle::ModuleDoc => format!("//! {body}\n"),
        CommentStyle::Block => format!("/**\n * {body}\n */\n"),
        CommentStyle::Hash => format!("# {body}\n"),
        CommentStyle::CBlock => format!("/* {body} */\n"),
        CommentStyle::Go => {
            format!("// Code generated by dto-gen. DO NOT EDIT.\n// {body}\n")
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn banners_pin_comment_styles_and_invariants() {
        let cases = [
            (
                CommentStyle::LineSlash,
                "out",
                "// @generated by dto-gen (--out) — do not edit. Regenerate with: pnpm gen\n",
            ),
            (
                CommentStyle::ModuleDoc,
                "fixture-runner-out",
                "//! @generated by dto-gen (--fixture-runner-out) — do not edit. Regenerate with: pnpm gen\n",
            ),
            (
                CommentStyle::Block,
                "ts-out",
                "/**\n * @generated by dto-gen (--ts-out) — do not edit. Regenerate with: pnpm gen\n */\n",
            ),
            (
                CommentStyle::Hash,
                "py-parity-out",
                "# @generated by dto-gen (--py-parity-out) — do not edit. Regenerate with: pnpm gen\n",
            ),
            (
                CommentStyle::CBlock,
                "c-parity-out",
                "/* @generated by dto-gen (--c-parity-out) — do not edit. Regenerate with: pnpm gen */\n",
            ),
            (
                CommentStyle::Go,
                "go-client-out",
                "// Code generated by dto-gen. DO NOT EDIT.\n// @generated by dto-gen (--go-client-out) — do not edit. Regenerate with: pnpm gen\n",
            ),
        ];
        for (style, flag, expected) in cases {
            let header = generated_header(style, flag);
            assert_eq!(header, expected);
            assert!(
                header.contains("@generated"),
                "@generated token must survive verbatim"
            );
            assert!(
                header.contains("pnpm gen"),
                "actionable command must be pnpm gen"
            );
            assert!(header.contains(&format!("(--{flag})")));
        }
        let go = generated_header(CommentStyle::Go, "go-parity-out");
        assert!(
            go.starts_with("// Code generated by dto-gen. DO NOT EDIT.\n"),
            "Go tooling matches ^// Code generated .* DO NOT EDIT\\.$"
        );
        assert_eq!(go.lines().next().unwrap().chars().last(), Some('.'));
    }
}
