//! Emit generated napi / wasm-bindgen / PyO3 / Magnus shim files
//! (steps 39G-b / 40 / 41 / 43).
//!
//! Node + Wasm each get four files: `args.rs`, `decisions.rs`,
//! `payload_builders.rs`, and the async client (`native_client.rs` /
//! `wasm_client.rs`). Python (Step 41) emits the same four plus a
//! `register.rs` that wires every `#[pyfunction]` into the `_solvapay`
//! module; the client surface is async `future_into_py` + blocking twins.
//! Ruby (Step 43 scaffold) emits only an allowlisted hello-world `client.rs`
//! (`getMerchant`); full surface lands in Step 44.
//! Per-symbol bodies come from [`crate::ir`]; the surrounding "chrome"
//! (module headers, `args.rs`, test trailers, client preamble/postamble, and
//! the wasm MCP module scaffold) is loaded from the committed
//! `assets/binding-emit.snapshot.json`.
//!
//! Output is not final: callers run `rustfmt` over each file (see
//! [`crate::write_file`] / `rustfmt_files`), which normalizes indentation and
//! blank lines. This emitter is responsible only for correct tokens, comment
//! text, ordering, and one-blank-line separation between items.

use serde_json::Value;

use crate::error::{GenError, GenResult};
use crate::ir::{
    Ir, IrBindingArg, IrBindingArtifact, IrBindingCall, IrBindingSymbol, IrExtractKind,
    IrSerializeKind, IrTypedStyle,
};

/// Target binding toolchain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Toolchain {
    /// napi-rs Node addon (`rust/bindings/node/src`).
    Node,
    /// wasm-bindgen edge/browser bundle (`rust/bindings/wasm/src`).
    Wasm,
    /// PyO3 Python extension (`rust/bindings/python/src`).
    Python,
    /// Magnus Ruby extension (`rust/bindings/ruby/ext/solvapay/src`).
    Ruby,
}

/// The generated shim files for one toolchain.
#[derive(Debug, Clone, PartialEq)]
pub struct EmittedBindings {
    /// `args.rs`.
    pub args_rs: String,
    /// `decisions.rs`.
    pub decisions_rs: String,
    /// `payload_builders.rs`.
    pub payload_builders_rs: String,
    /// `native_client.rs` (Node), `wasm_client.rs` (Wasm), or `client.rs` (Python/Ruby).
    pub client_rs: String,
    /// Python-only `register.rs` (`#[pymodule]` wiring). Empty for Node/Wasm/Ruby.
    pub register_rs: String,
}

const GENERATED_HEADER: &str = "//! @generated by dto-gen — do not edit.\n";

const SNAPSHOT: &str = include_str!("../assets/binding-emit.snapshot.json");

/// Section id whose payload symbols live in the wasm `mcp_payload` module.
const MCP_SECTION: &str = "MCP payload / descriptors";

/// Emits the four shim files for `toolchain` from the lowered IR.
///
/// # Errors
///
/// Returns [`GenError::Parse`] when the embedded chrome snapshot is missing an
/// expected field, or a symbol references chrome that is not present.
pub fn emit_bindings(ir: &Ir, toolchain: Toolchain) -> GenResult<EmittedBindings> {
    let chrome: Value = serde_json::from_str(SNAPSHOT)
        .map_err(|e| GenError::Parse(format!("invalid binding-emit snapshot: {e}")))?;
    let lang = match toolchain {
        Toolchain::Node => "node",
        Toolchain::Wasm => "wasm",
        Toolchain::Python => "python",
        Toolchain::Ruby => "ruby",
    };
    let art = chrome
        .get("artifacts")
        .and_then(|a| a.get(lang))
        .ok_or_else(|| GenError::Parse(format!("snapshot missing artifacts.{lang}")))?;

    match toolchain {
        Toolchain::Ruby => {
            let python_art = chrome
                .get("artifacts")
                .and_then(|a| a.get("python"))
                .ok_or_else(|| GenError::Parse("snapshot missing artifacts.python".into()))?;
            Ok(EmittedBindings {
                args_rs: with_generated_header(chrome_str(python_art, &["argsRs"])?),
                decisions_rs: emit_ruby_sync_artifact(ir, python_art, "decisions")?,
                payload_builders_rs: emit_ruby_payload_builders(ir, python_art)?,
                client_rs: emit_ruby_client(ir, art)?,
                register_rs: emit_ruby_register(ir),
            })
        }
        Toolchain::Python => Ok(EmittedBindings {
            args_rs: with_generated_header(chrome_str(art, &["argsRs"])?),
            decisions_rs: emit_decisions(ir, toolchain, art)?,
            payload_builders_rs: emit_payload_builders(ir, toolchain, art, &chrome)?,
            client_rs: emit_python_client(ir, art)?,
            register_rs: emit_python_register(ir)?,
        }),
        Toolchain::Node | Toolchain::Wasm => Ok(EmittedBindings {
            args_rs: with_generated_header(chrome_str(art, &["argsRs"])?),
            decisions_rs: emit_decisions(ir, toolchain, art)?,
            payload_builders_rs: emit_payload_builders(ir, toolchain, art, &chrome)?,
            client_rs: emit_client(ir, toolchain, art)?,
            register_rs: String::new(),
        }),
    }
}

// --- decisions.rs ------------------------------------------------------------

fn emit_decisions(ir: &Ir, toolchain: Toolchain, art: &Value) -> GenResult<String> {
    let header = chrome_str(art, &["decisions", "header"])?;
    let trailer = chrome_str(art, &["decisions", "testsTrailer"])?;
    let symbols = symbols_for(ir, IrBindingArtifact::Decisions);

    let mut chunks: Vec<String> = Vec::new();
    let mut prev_section: Option<&str> = None;
    for sym in &symbols {
        maybe_push_section(&mut chunks, &mut prev_section, sym, plain_section);
        chunks.push(emit_sync_fn(sym, toolchain));
    }

    Ok(format!(
        "{}{}\n\n{}",
        with_generated_header(header),
        chunks.join("\n\n"),
        trailer
    ))
}

// --- payload_builders.rs -----------------------------------------------------

fn emit_payload_builders(
    ir: &Ir,
    toolchain: Toolchain,
    art: &Value,
    chrome: &Value,
) -> GenResult<String> {
    let header = chrome_str(art, &["payloadBuilders", "header"])?;
    let trailer = chrome_str(art, &["payloadBuilders", "testsTrailer"])?;
    let symbols = symbols_for(ir, IrBindingArtifact::PayloadBuilders);

    match toolchain {
        Toolchain::Node => {
            let helpers = chrome_str(art, &["payloadBuilders", "payloadHelpers"])?;
            let mut chunks: Vec<String> = Vec::new();
            let mut prev_section: Option<&str> = None;
            for sym in &symbols {
                maybe_push_section(&mut chunks, &mut prev_section, sym, plain_section);
                chunks.push(emit_sync_fn(sym, toolchain));
            }
            Ok(format!(
                "{}{}\n\n{}\n\n{}",
                with_generated_header(header),
                chunks.join("\n\n"),
                helpers,
                trailer
            ))
        }
        Toolchain::Wasm => {
            let mcp_ids = mcp_symbol_ids(chrome)?;
            let module_header = chrome_str(art, &["payloadBuilders", "mcpPayloadModuleHeader"])?;
            let mcp_helpers = chrome_str(art, &["payloadBuilders", "mcpPayloadHelpers"])?;

            let mut public_chunks: Vec<String> = Vec::new();
            let mut mcp_chunks: Vec<String> = Vec::new();
            let mut prev_section: Option<&str> = None;
            for sym in &symbols {
                if mcp_ids.iter().any(|id| id == &sym.id) {
                    mcp_chunks.push(emit_sync_fn(sym, toolchain));
                } else {
                    maybe_push_section(&mut public_chunks, &mut prev_section, sym, |s| {
                        payload_wasm_section(s)
                    });
                    public_chunks.push(emit_sync_fn(sym, toolchain));
                }
            }

            let mcp_section = payload_wasm_section(MCP_SECTION);
            Ok(format!(
                "{}{}\n\n{}\n\n{}{}\n\n{}\n}}\n\n{}",
                with_generated_header(header),
                public_chunks.join("\n\n"),
                mcp_section,
                module_header,
                mcp_chunks.join("\n\n"),
                mcp_helpers,
                trailer
            ))
        }
        Toolchain::Python => {
            let helpers = chrome_str(art, &["payloadBuilders", "payloadHelpers"])?;
            let mut chunks: Vec<String> = Vec::new();
            let mut prev_section: Option<&str> = None;
            for sym in &symbols {
                maybe_push_section(&mut chunks, &mut prev_section, sym, plain_section);
                chunks.push(emit_sync_fn(sym, toolchain));
            }
            Ok(format!(
                "{}{}\n\n{}\n\n{}",
                with_generated_header(header),
                chunks.join("\n\n"),
                helpers,
                trailer
            ))
        }
        Toolchain::Ruby => unreachable!("Ruby uses emit_ruby_payload_builders"),
    }
}

fn ruby_header(header: &str) -> String {
    header
        .replace("PyO3", "Magnus")
        .replace("Step 41-b", "Step 44")
        .replace("use pyo3::prelude::*;\n", "")
}

fn emit_ruby_sync_artifact(ir: &Ir, art: &Value, key: &str) -> GenResult<String> {
    let header = ruby_header(chrome_str(art, &[key, "header"])?);
    let trailer = chrome_str(art, &[key, "testsTrailer"])?;
    let artifact = if key == "decisions" {
        IrBindingArtifact::Decisions
    } else {
        IrBindingArtifact::PayloadBuilders
    };
    let mut chunks = Vec::new();
    let mut previous = None;
    for symbol in symbols_for(ir, artifact) {
        maybe_push_section(&mut chunks, &mut previous, symbol, plain_section);
        chunks.push(emit_sync_fn(symbol, Toolchain::Ruby));
    }
    Ok(format!(
        "{}{}\n\n{}",
        with_generated_header(&header),
        chunks.join("\n\n"),
        trailer
    ))
}

fn emit_ruby_payload_builders(ir: &Ir, art: &Value) -> GenResult<String> {
    let mut output = emit_ruby_sync_artifact(ir, art, "payloadBuilders")?;
    let helpers = chrome_str(art, &["payloadBuilders", "payloadHelpers"])?;
    let trailer = chrome_str(art, &["payloadBuilders", "testsTrailer"])?;
    output = output.replace(trailer, &format!("{helpers}\n\n{trailer}"));
    Ok(output)
}

// --- native_client.rs / wasm_client.rs ---------------------------------------

fn emit_client(ir: &Ir, toolchain: Toolchain, art: &Value) -> GenResult<String> {
    let header = chrome_str(art, &["client", "header"])?;
    let preamble = chrome_str(art, &["client", "preamble"])?;
    let postamble = chrome_str(art, &["client", "postamble"])?;
    let symbols = symbols_for(ir, IrBindingArtifact::Client);

    let mut chunks: Vec<String> = Vec::new();
    let mut prev_section: Option<&str> = None;
    for sym in &symbols {
        let is_first = prev_section.is_none();
        if sym.section.as_deref() != prev_section {
            prev_section = sym.section.as_deref();
            // Node suppresses the leading group comment; wasm emits all groups.
            if let Some(section) = sym.section.as_deref() {
                if !(is_first && toolchain == Toolchain::Node) {
                    chunks.push(client_section(section));
                }
            }
        }
        chunks.push(emit_client_method(sym, toolchain)?);
    }

    Ok(format!(
        "{}{}\n{}\n}}\n\n{}",
        with_generated_header(header),
        preamble,
        chunks.join("\n\n"),
        postamble
    ))
}

/// Emits the full PyO3 `client.rs` (Groups A–C, async + blocking twins).
///
/// Every client symbol becomes an async `#[pymethods]` fn via
/// `pyo3_async_runtimes::tokio::future_into_py` **plus** a blocking `_blocking`
/// twin (`py.detach` + `runtime::get_runtime().block_on`), reusing the same
/// `run_envelope` plumbing / `client_call_body` as the Node/Wasm emitters.
fn emit_python_client(ir: &Ir, art: &Value) -> GenResult<String> {
    let header = chrome_str(art, &["client", "header"])?;
    let preamble = chrome_str(art, &["client", "preamble"])?;
    let postamble = chrome_str(art, &["client", "postamble"])?;
    let symbols = symbols_for(ir, IrBindingArtifact::Client);

    let mut chunks: Vec<String> = Vec::new();
    let mut prev_section: Option<&str> = None;
    for sym in &symbols {
        maybe_push_section(&mut chunks, &mut prev_section, sym, python_client_section);
        chunks.push(emit_python_client_method(sym)?);
    }

    Ok(format!(
        "{}{}\n{}\n}}\n\n{}",
        with_generated_header(header),
        preamble,
        chunks.join("\n\n"),
        postamble
    ))
}

/// Group-boundary comment inside the `#[pymethods]` impl block.
fn python_client_section(section: &str) -> String {
    format!("// --- {section} ---")
}

/// Emits the full sync-first Magnus `client.rs`.
///
/// Sync-only surface: each method releases the GVL via `without_gvl` while
/// `block_on`-ing the shared tokio runtime. Bodies reuse [`client_call_body`].
fn emit_ruby_client(ir: &Ir, art: &Value) -> GenResult<String> {
    let header = ruby_client_header(chrome_str(art, &["client", "header"])?);
    let preamble = ruby_client_preamble(
        &chrome_str(art, &["client", "preamble"])?
            .replace("SolvaPay::Client", "SolvaPay::Native::Client"),
    );
    let postamble = chrome_str(art, &["client", "postamble"])?;
    let symbols = symbols_for(ir, IrBindingArtifact::Client);

    let mut chunks: Vec<String> = Vec::new();
    let mut prev_section: Option<&str> = None;
    for sym in &symbols {
        maybe_push_section(&mut chunks, &mut prev_section, sym, ruby_client_section);
        chunks.push(emit_ruby_client_method(sym)?);
    }

    Ok(format!(
        "{}{}\n{}\n}}\n\n{}",
        with_generated_header(&header),
        preamble,
        chunks.join("\n\n"),
        postamble
    ))
}

fn ruby_client_header(header: &str) -> String {
    let dto_imports = "use solvapay_dto::{\n    ActivatePlanDto, AssignCreditsRequest, AttachBusinessDetailsParams, CancelPurchaseParams,\n    CheckLimitsRequest, CloneProductOverrides, ConfigureMcpPlansDto, CreateCheckoutSessionRequest,\n    CreateCustomerRequest, CreateCustomerSessionRequest, CreatePaymentIntentParams,\n    CreatePlanParams, CreateProductRequest, CreateTopupPaymentIntentParams,\n    DisableAutoRechargeParams, GetAutoRechargeParams, GetCustomerBalanceParams, GetCustomerParams,\n    GetPaymentMethodParams, GetUserInfoParams, McpBootstrapDto, ProcessPaymentIntentParams,\n    ReactivatePurchaseParams, SaveAutoRechargeParams, TrackUsageBulkRequest, TrackUsageRequest,\n    UpdateCustomerParams, UpdatePlanRequest, UpdateProductRequest,\n};\n";
    header
        .replace(
            "Magnus [`SolvaPayClient`] — Step 43 hello-world scaffold (`getMerchant`).",
            "Magnus private [`SolvaPayClient`] — full Groups A–C surface (Step 44).",
        )
        .replace("SolvaPay::Client", "SolvaPay::Native::Client")
        .replace(
            "use solvapay_core::SdkError;\n",
            &format!("use solvapay_core::SdkError;\n{dto_imports}"),
        )
        .replace(
            "ClientShell, ReqwestTransport, SharedTransport, SolvaPayClient as CoreClient,",
            "mulberry32, ClientShell, ReqwestTransport, SharedTransport, SolvaPayClient as CoreClient,",
        )
}

fn ruby_client_preamble(preamble: &str) -> String {
    let old_builder = "    let transport = ReqwestTransport::new()?;\n    let transport: SharedTransport = Arc::new(transport);\n    let mut shell = ClientShell::new(transport, api_key);\n    if let Some(base) = api_base_url {\n        shell = shell.with_base_url(base);\n    }\n    Ok(Arc::new(CoreClient::new(shell)))";
    let new_builder = "    build_solvapay_client_with_hooks(api_key, api_base_url, None, None)";
    let hook_builder = "}\n\n/// Builds a client with deterministic fixture clock and RNG hooks.\npub(crate) fn build_solvapay_client_with_hooks(\n    api_key: String,\n    api_base_url: Option<String>,\n    clock_unix_ms: Option<u64>,\n    rng_seed: Option<u32>,\n) -> std::result::Result<Arc<CoreClient>, SdkError> {\n    let transport = ReqwestTransport::new()?;\n    let transport: SharedTransport = Arc::new(transport);\n    let mut shell = ClientShell::new(transport, api_key);\n    if let Some(base) = api_base_url {\n        shell = shell.with_base_url(base);\n    }\n    if let Some(ms) = clock_unix_ms {\n        shell = shell.with_clock(Arc::new(move || ms));\n    }\n    if let Some(seed) = rng_seed {\n        shell = shell.with_rng(Arc::new(mulberry32(seed)));\n    }\n    Ok(Arc::new(CoreClient::new(shell)))\n}\n\n/// Magnus client";
    let fixture_constructor = "\n    /// Test-only constructor for shared golden fixture replay.\n    pub(crate) fn for_fixtures(ruby: &Ruby, args: &[Value]) -> Result<Self, Error> {\n        let _ = ruby;\n        let args = scan_args::<(String, String), (Option<u64>, Option<u32>), (), (), (), ()>(args)?;\n        let (api_key, api_base_url) = args.required;\n        let (clock_unix_ms, rng_seed) = args.optional;\n        build_solvapay_client_with_hooks(\n            api_key,\n            Some(api_base_url),\n            clock_unix_ms,\n            rng_seed,\n        )\n        .map(|client| Self { client })\n        .map_err(sdk_error_to_magnus)\n    }\n\n";
    preamble
        .replace(old_builder, new_builder)
        .replace("}\n\n/// Magnus client", hook_builder)
        + fixture_constructor
}

/// Group-boundary comment inside the Magnus `impl` block.
fn ruby_client_section(section: &str) -> String {
    format!("// --- {section} ---")
}

/// Emits a sync GVL-releasing Magnus client method for one symbol.
fn emit_ruby_client_method(sym: &IrBindingSymbol) -> GenResult<String> {
    let doc = render_doc(&sym.doc);
    let fn_name = &sym.names.rb;
    let (param, inner) = client_call_body(sym)?;
    let discard = if param == "_args_json" {
        "\n    let _ = args_json;"
    } else {
        ""
    };

    Ok(format!(
        "{doc}\npub(crate) fn {fn_name}(&self, args_json: String) -> String {{{discard}\n    let client = Arc::clone(&self.client);\n    without_gvl(|| {{\n        runtime::get_runtime().block_on(async move {{ {inner} }})\n    }})\n}}"
    ))
}

/// Emits async `future_into_py` + blocking interpreter-detached twin for one
/// client symbol, reusing the shared [`client_call_body`] expression.
fn emit_python_client_method(sym: &IrBindingSymbol) -> GenResult<String> {
    let doc = render_doc(&sym.doc);
    let fn_name = &sym.rust_fn_name;
    let py_name = &sym.names.py;
    let blocking_name = format!("{py_name}_blocking");
    let (param, inner) = client_call_body(sym)?;
    let discard = if param == "_args_json" {
        "\n    let _ = args_json;"
    } else {
        ""
    };
    let name_attr = if fn_name == py_name {
        String::new()
    } else {
        format!("\n#[pyo3(name = \"{py_name}\")]")
    };

    // Single per-symbol body drives both surfaces (async future_into_py +
    // blocking py.detach / block_on twin).
    let async_fn = format!(
        "{doc}{name_attr}\nfn {fn_name}<'py>(&self, py: Python<'py>, args_json: String) -> PyResult<Bound<'py, PyAny>> {{{discard}\n    let client = Arc::clone(&self.client);\n    pyo3_async_runtimes::tokio::future_into_py(py, async move {{\n        Ok::<_, PyErr>({inner})\n    }})\n}}"
    );
    let blocking_doc =
        format!("/// Blocking twin of [`Self::{fn_name}`] (interpreter detached while awaiting).");
    let blocking_fn = format!(
        "{blocking_doc}\n#[pyo3(name = \"{blocking_name}\")]\nfn {blocking_name}(&self, py: Python<'_>, args_json: String) -> String {{{discard}\n    let client = Arc::clone(&self.client);\n    py.detach(|| {{\n        runtime::get_runtime().block_on(async move {{ {inner} }})\n    }})\n}}"
    );
    Ok(format!("{async_fn}\n\n{blocking_fn}"))
}

fn emit_client_method(sym: &IrBindingSymbol, toolchain: Toolchain) -> GenResult<String> {
    let doc = render_doc(&sym.doc);
    let attr = attr_macro(toolchain, &sym.id);
    let clone = clone_ty(toolchain);
    let fn_name = &sym.rust_fn_name;
    let (param, inner) = client_call_body(sym)?;

    Ok(format!(
        "{doc}\n{attr}\npub async fn {fn_name}(&self, {param}: String) -> String {{\n    let client = {clone}::clone(&self.client);\n    {inner}\n}}"
    ))
}

/// Shared per-symbol client body: returns the `args_json` param name (`_args_json`
/// for arg-ignoring methods) and the `run_envelope(async move { … }).await`
/// expression. Toolchain-agnostic — Node/Wasm wrap it in an `async fn`, Python
/// wraps it in `future_into_py` + a blocking `block_on` twin, Ruby wraps it in
/// `without_gvl` + `block_on`.
fn client_call_body(sym: &IrBindingSymbol) -> GenResult<(&'static str, String)> {
    let core = core_call(sym)?;

    let serialize = match &sym.call {
        IrBindingCall::Wrap { serialize, .. } => *serialize,
        IrBindingCall::Verbatim => {
            return Err(GenError::Parse(format!(
                "client symbol {} unexpectedly verbatim",
                sym.id
            )))
        }
    };

    let out = match serialize {
        IrSerializeKind::ClientIgnore => (
            "_args_json",
            format!("run_envelope(async move {{ client.{core}().await }}).await"),
        ),
        IrSerializeKind::ClientAwait => {
            let dto = sym.dto_type.as_deref().ok_or_else(|| {
                GenError::Parse(format!("client {} clientAwait missing dtoType", sym.id))
            })?;
            (
                "args_json",
                format!(
                    "run_envelope(async move {{\n            let params: {dto} = parse_args_json(&args_json)?;\n            client.{core}(params).await\n        }})\n        .await"
                ),
            )
        }
        IrSerializeKind::ClientSplit => {
            let keys = sym
                .split_path_refs
                .iter()
                .map(|k| format!("\"{k}\""))
                .collect::<Vec<_>>()
                .join(", ");
            let call_args = sym.client_call_args.join(", ");
            let body = match &sym.dto_type {
                Some(dto) => {
                    let body_local = body_local_name(sym);
                    format!(
                        "run_envelope(async move {{\n            let (refs, body) = split_path_refs(&args_json, &[{keys}])?;\n            let {body_local}: {dto} = serde_json::from_value(body).map_err(|err| {{\n                SdkError::transport(format!(\"invalid {id} body: {{err}}\"), false)\n            }})?;\n            client.{core}({call_args}).await\n        }})\n        .await",
                        id = sym.id
                    )
                }
                None => format!(
                    "run_envelope(async move {{\n            let (refs, _) = split_path_refs(&args_json, &[{keys}])?;\n            client.{core}({call_args}).await\n        }})\n        .await"
                ),
            };
            ("args_json", body)
        }
        other => {
            return Err(GenError::Parse(format!(
                "client symbol {} has non-client serialize {other:?}",
                sym.id
            )))
        }
    };

    Ok(out)
}

// --- shared sync fn body -----------------------------------------------------

fn emit_sync_fn(sym: &IrBindingSymbol, toolchain: Toolchain) -> String {
    let doc = render_doc(pick_doc(sym, toolchain));
    let export_name = match toolchain {
        Toolchain::Python => sym.names.py.as_str(),
        Toolchain::Ruby => sym.names.rb.as_str(),
        Toolchain::Node | Toolchain::Wasm => sym.id.as_str(),
    };
    let attr = attr_macro(toolchain, export_name);
    let attr_line = if attr.is_empty() {
        String::new()
    } else {
        format!("{attr}\n")
    };
    let fn_name = &sym.rust_fn_name;
    let body = sync_body(sym, toolchain);
    format!(
        "{doc}\n{attr_line}pub fn {fn_name}(args_json: String) -> String {{\n    run_envelope_sync(|| {{\n{body}\n    }})\n}}"
    )
}

/// Emits Python `register.rs` — wires every sync `#[pyfunction]` into `_solvapay`.
fn emit_python_register(ir: &Ir) -> GenResult<String> {
    let mut imports: Vec<String> = Vec::new();
    let mut registrations: Vec<String> = Vec::new();

    for (module, artifact) in [
        ("decisions", IrBindingArtifact::Decisions),
        ("payload_builders", IrBindingArtifact::PayloadBuilders),
    ] {
        let symbols = symbols_for(ir, artifact);
        for sym in symbols {
            let fn_name = &sym.rust_fn_name;
            imports.push(format!("use crate::{module}::{fn_name};"));
            registrations.push(format!(
                "    m.add_function(wrap_pyfunction!({fn_name}, m)?)?;"
            ));
        }
    }

    Ok(format!(
        "{GENERATED_HEADER}//! Registers generated sync PyO3 free functions on `_solvapay` (Step 41-b).\n\nuse pyo3::prelude::*;\nuse pyo3::wrap_pyfunction;\n\n{}\n\n/// Adds every generated decision + payload-builder `#[pyfunction]` to `m`.\n///\n/// # Errors\n///\n/// Propagates [`PyErr`] from [`PyModule::add_function`].\npub(crate) fn register_generated(m: &Bound<'_, PyModule>) -> PyResult<()> {{\n{}\n    Ok(())\n}}\n",
        imports.join("\n"),
        registrations.join("\n")
    ))
}

fn emit_ruby_register(ir: &Ir) -> String {
    let mut imports = vec!["use crate::client::SolvaPayClient;".to_string()];
    let mut registrations = Vec::new();
    for (module, artifact) in [
        ("decisions", IrBindingArtifact::Decisions),
        ("payload_builders", IrBindingArtifact::PayloadBuilders),
    ] {
        for symbol in symbols_for(ir, artifact) {
            imports.push(format!("use crate::{module}::{};", symbol.rust_fn_name));
            registrations.push(format!(
                "    native.define_singleton_method(\"{}\", function!({}, 1))?;",
                symbol.names.rb, symbol.rust_fn_name
            ));
        }
    }
    for symbol in symbols_for(ir, IrBindingArtifact::Client) {
        registrations.push(format!(
            "    client.define_method(\"{}\", method!(SolvaPayClient::{}, 1))?;",
            symbol.names.rb, symbol.names.rb
        ));
    }
    format!(
        "{GENERATED_HEADER}//! Registers every generated Magnus envelope function (Step 44).\n\nuse magnus::prelude::*;\nuse magnus::{{function, method, Error, RClass, RModule}};\n\n{}\n\n/// Registers generated sync functions and client methods.\npub(crate) fn register_generated(native: RModule, client: RClass) -> Result<(), Error> {{\n{}\n    Ok(())\n}}\n",
        imports.join("\n"),
        registrations.join("\n")
    )
}

fn sync_body(sym: &IrBindingSymbol, toolchain: Toolchain) -> String {
    match &sym.call {
        IrBindingCall::Verbatim => {
            let node = sym.verbatim_body.as_deref().unwrap_or_default();
            match toolchain {
                Toolchain::Wasm => sym
                    .verbatim_body_wasm
                    .as_deref()
                    .unwrap_or(node)
                    .to_string(),
                Toolchain::Node | Toolchain::Python | Toolchain::Ruby => node.to_string(),
            }
        }
        IrBindingCall::Wrap { serialize, args } => {
            let mut lines: Vec<String> = Vec::new();
            let args_bind = if sym.args.is_empty() { "_args" } else { "args" };
            lines.push(format!("let {args_bind} = args_map(&args_json)?;"));
            for arg in &sym.args {
                lines.push(extract_line(arg));
            }
            let call_args = args.join(", ");
            let core = sym.core_call.as_deref().unwrap_or_default();
            lines.push(serialize_expr(*serialize, core, &call_args));
            lines.join("\n")
        }
    }
}

fn serialize_expr(kind: IrSerializeKind, core: &str, args: &str) -> String {
    match kind {
        IrSerializeKind::ToValue => format!("to_value(&{core}({args}))"),
        IrSerializeKind::ValueBool => format!("Ok(Value::Bool({core}({args})))"),
        IrSerializeKind::ValueString => format!("Ok(Value::String({core}({args})))"),
        IrSerializeKind::ValueArray => format!("Ok(Value::Array({core}({args})))"),
        IrSerializeKind::OptionHelperErr => format!("option_helper_err({core}({args}))"),
        IrSerializeKind::ResultAsValue => format!("result_as_value({core}({args}))"),
        IrSerializeKind::ClientAwait
        | IrSerializeKind::ClientSplit
        | IrSerializeKind::ClientIgnore => {
            // Client serialize forms never reach the sync body emitter.
            String::new()
        }
    }
}

fn extract_line(arg: &IrBindingArg) -> String {
    let local = arg
        .local
        .clone()
        .unwrap_or_else(|| default_snake(&arg.name));
    let name = &arg.name;
    match arg.extract {
        IrExtractKind::RequireString => {
            format!("let {local} = require_string(&args, \"{name}\")?;")
        }
        IrExtractKind::OptionalString => {
            format!("let {local} = optional_string(&args, \"{name}\")?;")
        }
        IrExtractKind::RequireF64 => format!("let {local} = require_f64(&args, \"{name}\")?;"),
        IrExtractKind::OptionalF64 => format!("let {local} = optional_f64(&args, \"{name}\")?;"),
        IrExtractKind::RequireI64 => format!("let {local} = require_i64(&args, \"{name}\")?;"),
        IrExtractKind::RequireU32 => format!("let {local} = require_u32(&args, \"{name}\")?;"),
        IrExtractKind::OptionalU16 => format!("let {local} = optional_u16(&args, \"{name}\")?;"),
        IrExtractKind::OptionalU32 => format!("let {local} = optional_u32(&args, \"{name}\")?;"),
        IrExtractKind::OptionalU64 => format!("let {local} = optional_u64(&args, \"{name}\")?;"),
        IrExtractKind::RequireBool => format!("let {local} = require_bool(&args, \"{name}\")?;"),
        IrExtractKind::RequireObject => {
            format!("let {local} = require_object(&args, \"{name}\")?;")
        }
        IrExtractKind::RequireArray => format!("let {local} = require_array(&args, \"{name}\")?;"),
        IrExtractKind::RequireTyped => typed_line("require_typed", arg, &local),
        IrExtractKind::OptionalTyped => typed_line("optional_typed", arg, &local),
        IrExtractKind::OptionalValue => format!("let {local} = optional_value(&args, \"{name}\");"),
        IrExtractKind::RawValueOrNull => {
            format!("let {local} = args.get(\"{name}\").cloned().unwrap_or(Value::Null);")
        }
    }
}

fn typed_line(helper: &str, arg: &IrBindingArg, local: &str) -> String {
    let name = &arg.name;
    let ty = arg.typed_as.as_deref().unwrap_or("Value");
    match arg.typed_style {
        IrTypedStyle::Turbofish => {
            format!("let {local} = {helper}::<{ty}>(&args, \"{name}\")?;")
        }
        IrTypedStyle::Annotation => {
            format!("let {local}: {ty} = {helper}(&args, \"{name}\")?;")
        }
    }
}

// --- helpers -----------------------------------------------------------------

fn symbols_for(ir: &Ir, artifact: IrBindingArtifact) -> Vec<&IrBindingSymbol> {
    let mut out: Vec<&IrBindingSymbol> = ir
        .binding_symbols
        .values()
        .filter(|s| s.artifact == artifact)
        .collect();
    out.sort_by(|a, b| a.emit_order.cmp(&b.emit_order).then(a.id.cmp(&b.id)));
    out
}

fn maybe_push_section<'a>(
    chunks: &mut Vec<String>,
    prev: &mut Option<&'a str>,
    sym: &'a IrBindingSymbol,
    render: impl Fn(&str) -> String,
) {
    if sym.section.as_deref() != *prev {
        *prev = sym.section.as_deref();
        if let Some(section) = sym.section.as_deref() {
            chunks.push(render(section));
        }
    }
}

fn plain_section(section: &str) -> String {
    format!("// --- {section} ---")
}

fn payload_wasm_section(section: &str) -> String {
    let suffix = if section == MCP_SECTION {
        "edge-only"
    } else {
        "public-safe"
    };
    format!("// --- {section} ({suffix}) ---")
}

fn client_section(section: &str) -> String {
    // Committed format: 4-space indent + `// --- {section} ` padded with dashes
    // to a total line width of 80.
    let prefix = format!("    // --- {section} ");
    let dashes = 80usize.saturating_sub(prefix.len());
    format!("{prefix}{}", "-".repeat(dashes))
}

fn attr_macro(toolchain: Toolchain, export_name: &str) -> String {
    match toolchain {
        Toolchain::Node => format!("#[napi(js_name = \"{export_name}\")]"),
        Toolchain::Wasm => format!("#[wasm_bindgen(js_name = \"{export_name}\")]"),
        Toolchain::Python => format!("#[pyfunction(name = \"{export_name}\")]"),
        Toolchain::Ruby => String::new(),
    }
}

fn clone_ty(toolchain: Toolchain) -> &'static str {
    match toolchain {
        Toolchain::Node | Toolchain::Python | Toolchain::Ruby => "Arc",
        Toolchain::Wasm => "Rc",
    }
}

fn pick_doc(sym: &IrBindingSymbol, toolchain: Toolchain) -> &str {
    match toolchain {
        Toolchain::Wasm => sym.doc_wasm.as_deref().unwrap_or(&sym.doc),
        Toolchain::Node | Toolchain::Python | Toolchain::Ruby => &sym.doc,
    }
}

fn render_doc(doc: &str) -> String {
    if doc.is_empty() {
        return String::new();
    }
    doc.split('\n')
        .map(|line| {
            if line.is_empty() {
                "///".to_string()
            } else {
                format!("/// {line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn core_call(sym: &IrBindingSymbol) -> GenResult<&str> {
    sym.core_call
        .as_deref()
        .ok_or_else(|| GenError::Parse(format!("symbol {} missing coreCall", sym.id)))
}

/// Body-parse local name for a `clientSplit` method, derived from the last
/// call arg (`"params"` or `"Some(overrides)"` → `overrides`).
fn body_local_name(sym: &IrBindingSymbol) -> String {
    let last = sym
        .client_call_args
        .last()
        .map(String::as_str)
        .unwrap_or("");
    last.trim_start_matches("Some(")
        .trim_end_matches(')')
        .to_string()
}

fn default_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn with_generated_header(content: &str) -> String {
    if content.starts_with(GENERATED_HEADER) {
        content.to_string()
    } else {
        format!("{GENERATED_HEADER}{content}")
    }
}

fn chrome_str<'a>(art: &'a Value, path: &[&str]) -> GenResult<&'a str> {
    let mut cur = art;
    for key in path {
        cur = cur.get(*key).ok_or_else(|| {
            GenError::Parse(format!("snapshot chrome missing {}", path.join(".")))
        })?;
    }
    cur.as_str().ok_or_else(|| {
        GenError::Parse(format!(
            "snapshot chrome {} is not a string",
            path.join(".")
        ))
    })
}

fn mcp_symbol_ids(chrome: &Value) -> GenResult<Vec<String>> {
    let ids = chrome
        .get("artifacts")
        .and_then(|a| a.get("wasm"))
        .and_then(|w| w.get("payloadBuilders"))
        .and_then(|p| p.get("mcpPayloadModuleSymbolIds"))
        .and_then(Value::as_array)
        .ok_or_else(|| GenError::Parse("snapshot missing mcpPayloadModuleSymbolIds".into()))?;
    Ok(ids
        .iter()
        .filter_map(|v| v.as_str().map(str::to_owned))
        .collect())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::lower_bindings::lower_bindings;
    use crate::manifest::Manifest;
    use std::collections::BTreeMap;

    fn ir_from_yaml(yaml: &str) -> Ir {
        let manifest: Manifest = serde_norway::from_str(yaml).unwrap();
        let mut ir = Ir {
            types: BTreeMap::new(),
            overlay_helpers: BTreeMap::new(),
            overlays: BTreeMap::new(),
            routes: vec![],
            error_templates: crate::ir::IrErrorTemplates::default(),
            entry_points: BTreeMap::new(),
            binding_symbols: BTreeMap::new(),
        };
        lower_bindings(&mut ir, &manifest).unwrap();
        ir
    }

    #[test]
    fn generated_header_is_prepended_once() {
        assert_eq!(
            with_generated_header("//! x\n"),
            "//! @generated by dto-gen — do not edit.\n//! x\n"
        );
        let twice = with_generated_header(&with_generated_header("//! x\n"));
        assert_eq!(twice.matches("@generated").count(), 1);
    }

    #[test]
    fn client_section_is_80_wide() {
        let line = client_section("Group B");
        assert_eq!(line.len(), 80);
        assert!(line.starts_with("    // --- Group B "));
        assert!(line.ends_with('-'));
    }

    #[test]
    fn extract_line_require_string() {
        let arg = IrBindingArg {
            name: "customerRef".into(),
            ty: crate::ir::IrBoundaryType::String,
            required: true,
            host_injected: false,
            extract: IrExtractKind::RequireString,
            typed_as: None,
            typed_style: IrTypedStyle::Turbofish,
            local: Some("customer_ref".into()),
        };
        assert_eq!(
            extract_line(&arg),
            "let customer_ref = require_string(&args, \"customerRef\")?;"
        );
    }

    #[test]
    fn extract_line_typed_annotation_vs_turbofish() {
        let base = IrBindingArg {
            name: "structuredContent".into(),
            ty: crate::ir::IrBoundaryType::Value,
            required: true,
            host_injected: false,
            extract: IrExtractKind::RequireTyped,
            typed_as: Some("PaywallGate".into()),
            typed_style: IrTypedStyle::Annotation,
            local: Some("gate".into()),
        };
        assert_eq!(
            extract_line(&base),
            "let gate: PaywallGate = require_typed(&args, \"structuredContent\")?;"
        );
        let turbofish = IrBindingArg {
            typed_style: IrTypedStyle::Turbofish,
            ..base
        };
        assert_eq!(
            extract_line(&turbofish),
            "let gate = require_typed::<PaywallGate>(&args, \"structuredContent\")?;"
        );
    }

    #[test]
    fn serialize_expr_forms() {
        assert_eq!(
            serialize_expr(
                IrSerializeKind::ToValue,
                "classify_customer_ref",
                "&customer_ref"
            ),
            "to_value(&classify_customer_ref(&customer_ref))"
        );
        assert_eq!(
            serialize_expr(IrSerializeKind::OptionHelperErr, "f", "a, b"),
            "option_helper_err(f(a, b))"
        );
    }

    #[test]
    fn emits_verbatim_body_for_retry() {
        let yaml = r#"
bindings:
  retryNextDelayMs:
    core: solvapay_core::retry::retry_next_delay_ms
    names:
      ts: retryNextDelayMs
      py: retry_next_delay_ms
      rb: retry_next_delay_ms
      go: RetryNextDelayMs
      rust: retry_next_delay_ms
    catalog:
      kind: none
    args: []
    splitPathRefs: []
    return: value
    sync: sync
    envelope: sync
    artifact: decisions
    emitOrder: 0
    section: retry
    doc: Binding for `retryNextDelayMs`.
    rustFnName: retry_next_delay_ms
    call:
      kind: verbatim
    verbatimBody: |-
      let x = 1;
      Ok(Value::from(x))
"#;
        let ir = ir_from_yaml(yaml);
        let sym = ir.binding_symbols.get("retryNextDelayMs").unwrap();
        let out = emit_sync_fn(sym, Toolchain::Node);
        assert!(out.contains("#[napi(js_name = \"retryNextDelayMs\")]"));
        assert!(out.contains("pub fn retry_next_delay_ms(args_json: String) -> String"));
        assert!(out.contains("Ok(Value::from(x))"));
    }

    #[test]
    fn emits_client_await_and_split() {
        let yaml = r#"
bindings:
  createCustomer:
    core: solvapay_transport::SolvaPayClient::create_customer
    names:
      ts: createCustomer
      py: create_customer
      rb: create_customer
      go: CreateCustomer
      rust: create_customer
    catalog:
      kind: operation
      id: createCustomer
    args: []
    splitPathRefs: []
    return: value
    sync: async
    envelope: async
    artifact: client
    emitOrder: 0
    section: Group A
    doc: "`POST /v1/sdk/customers`"
    rustFnName: create_customer
    dtoType: CreateCustomerRequest
    coreCall: create_customer
    call:
      kind: wrap
      serialize: clientAwait
  updateCustomer:
    core: solvapay_transport::SolvaPayClient::update_customer
    names:
      ts: updateCustomer
      py: update_customer
      rb: update_customer
      go: UpdateCustomer
      rust: update_customer
    catalog:
      kind: operation
      id: updateCustomer
    args: []
    splitPathRefs:
      - customerRef
    return: value
    sync: async
    envelope: async
    artifact: client
    emitOrder: 1
    section: Group A
    doc: "`PATCH /v1/sdk/customers/{customerRef}`"
    rustFnName: update_customer
    dtoType: UpdateCustomerParams
    coreCall: update_customer
    clientCallArgs:
      - "&refs[0]"
      - params
    call:
      kind: wrap
      serialize: clientSplit
"#;
        let ir = ir_from_yaml(yaml);
        let create = ir.binding_symbols.get("createCustomer").unwrap();
        let node = emit_client_method(create, Toolchain::Node).unwrap();
        assert!(node.contains("let client = Arc::clone(&self.client);"));
        assert!(node.contains("let params: CreateCustomerRequest = parse_args_json(&args_json)?;"));

        let wasm = emit_client_method(create, Toolchain::Wasm).unwrap();
        assert!(wasm.contains("let client = Rc::clone(&self.client);"));
        assert!(wasm.contains("#[wasm_bindgen(js_name = \"createCustomer\")]"));

        let update = ir.binding_symbols.get("updateCustomer").unwrap();
        let split = emit_client_method(update, Toolchain::Node).unwrap();
        assert!(
            split.contains("let (refs, body) = split_path_refs(&args_json, &[\"customerRef\"])?;")
        );
        assert!(split.contains("let params: UpdateCustomerParams = serde_json::from_value(body)"));
        assert!(split.contains("invalid updateCustomer body"));
        assert!(split.contains("client.update_customer(&refs[0], params).await"));
    }

    #[test]
    fn ruby_registration_does_not_require_function_attributes() {
        assert_eq!(attr_macro(Toolchain::Ruby, "get_merchant"), "");
    }

    #[test]
    fn clone_ty_ruby_is_arc() {
        assert_eq!(clone_ty(Toolchain::Ruby), "Arc");
    }

    #[test]
    fn emits_full_ruby_client_and_registration() {
        let yaml = r#"
bindings:
  getMerchant:
    core: solvapay_transport::SolvaPayClient::get_merchant
    names:
      ts: getMerchant
      py: get_merchant
      rb: get_merchant
      go: GetMerchant
      rust: get_merchant
    catalog:
      kind: operation
      id: getMerchant
    args: []
    splitPathRefs: []
    return: value
    sync: async
    envelope: async
    artifact: client
    emitOrder: 0
    section: Group A
    doc: Merchant profile (`args_json` ignored; pass `"{}"`).
    rustFnName: get_merchant
    call:
      kind: wrap
      serialize: clientIgnore
    coreCall: get_merchant
  createCustomer:
    core: solvapay_transport::SolvaPayClient::create_customer
    names:
      ts: createCustomer
      py: create_customer
      rb: create_customer
      go: CreateCustomer
      rust: create_customer
    catalog:
      kind: operation
      id: createCustomer
    args: []
    splitPathRefs: []
    return: value
    sync: async
    envelope: async
    artifact: client
    emitOrder: 1
    section: Group A
    doc: "`POST /v1/sdk/customers`"
    rustFnName: create_customer
    dtoType: CreateCustomerRequest
    coreCall: create_customer
    call:
      kind: wrap
      serialize: clientAwait
"#;
        let ir = ir_from_yaml(yaml);
        let emitted = emit_bindings(&ir, Toolchain::Ruby).unwrap();
        assert!(emitted
            .client_rs
            .contains("pub(crate) fn get_merchant(&self, args_json: String) -> String"));
        assert!(emitted.client_rs.contains("without_gvl(||"));
        assert!(emitted
            .client_rs
            .contains("runtime::get_runtime().block_on"));
        assert!(emitted.client_rs.contains("client.get_merchant().await"));
        assert!(
            emitted.client_rs.contains("fn create_customer"),
            "Step 44 emits all client methods"
        );
        assert!(emitted.register_rs.contains("\"create_customer\""));
        assert!(emitted.args_rs.contains("fn args_map"));
    }
}
