/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sdk/payment-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment intents for the provider
         * @description Retrieves a paginated list of all payment intents created by the authenticated provider. Supports pagination through limit and offset query parameters.
         */
        get: operations["PaymentIntentSdkController_getPaymentIntents"];
        put?: never;
        /**
         * Create a payment intent
         * @description Creates a new payment intent for a customer to purchase a plan. Requires an idempotency key to prevent duplicate charges. Returns client secret and publishable key needed for frontend integration.
         */
        post: operations["PaymentIntentSdkController_createPaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/payment-intents/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific payment intent
         * @description Retrieves detailed information about a specific payment intent including amount, currency, and client secret.
         */
        get: operations["PaymentIntentSdkController_getPaymentIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/payment-intents/{processorPaymentId}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process payment intent after client-side confirmation
         * @description Processes a payment intent that has been confirmed on the client side. Polls the database for payment intent status to become succeeded (up to 10 seconds). Returns the current status of the payment intent.
         */
        post: operations["PaymentIntentSdkController_processPaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/checkout-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a checkout session
         * @description Creates a hosted checkout session for a customer to purchase a product plan. Returns a session ID and checkout URL for redirect.
         */
        post: operations["CheckoutSessionSdkController_createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products/{productRef}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plans for a product */
        get: operations["PlanSdkController_listPlans"];
        put?: never;
        /** Create a plan for a product */
        post: operations["PlanSdkController_createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products/{productRef}/plans/{planRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a plan for a product */
        get: operations["PlanSdkController_getPlan"];
        /** Update a plan for a product */
        put: operations["PlanSdkController_updatePlan"];
        post?: never;
        /** Delete a plan from a product */
        delete: operations["PlanSdkController_deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products
         * @description Retrieves a paginated list of products for the authenticated provider. Supports filtering by status, search term, and MCP Pay flag.
         */
        get: operations["ProductSdkController_listProducts"];
        put?: never;
        /**
         * Create a product
         * @description Creates a new product for the authenticated provider.
         */
        post: operations["ProductSdkController_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products/{productRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product by reference
         * @description Retrieves a product by its reference or ID, including embedded plans.
         */
        get: operations["ProductSdkController_getProduct"];
        /**
         * Update a product
         * @description Updates an existing product. Only provided fields are updated.
         */
        put: operations["ProductSdkController_updateProduct"];
        post?: never;
        /**
         * Delete a product
         * @description Deletes a product permanently in sandbox. In live mode, soft-deletes (preserves data but hides from listings). If the product has purchases in live mode, deactivates instead.
         */
        delete: operations["ProductSdkController_deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products/mcp/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap MCP product integration
         * @description Creates an MCP-enabled product with a unified plans array, configures origin URL, and maps tools to plans in one request.
         */
        post: operations["ProductSdkController_bootstrapMcpProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products/{productRef}/mcp/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Configure MCP plans on an MCP product
         * @description Configures plans and optional tool-to-plan mappings for an MCP product.
         */
        put: operations["ProductSdkController_configureMcpPlans"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/products/{productRef}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone a product
         * @description Deep-copies a product including all its plans. Generates new references for the clone.
         */
        post: operations["ProductSdkController_cloneProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/usages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a usage event
         * @description Records a usage event into the Usage timeseries collection.
         */
        post: operations["UsageSdkController_recordUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/usages/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record bulk usage events
         * @description Same persistence rules as POST /sdk/usages for each item: validate batch first, then one insert per event.
         */
        post: operations["UsageSdkController_recordBulkUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/meter-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a meter event
         * @description Records a single usage event against a named meter.
         */
        post: operations["MeterEventsSdkController_recordEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/meter-events/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record meter events in bulk
         * @description Persists each event with recordUsage (same shape as single POST), after shared meter/customer checks.
         */
        post: operations["MeterEventsSdkController_recordBulkEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List purchases for provider
         * @description Retrieves all purchases for the authenticated provider with optional filtering by status, product, or customer.
         */
        get: operations["PurchaseSdkController_listPurchases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/purchases/customer/{customerRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get purchases for a customer
         * @description Retrieves all purchases for a specific customer. Useful for billing history and access checks.
         */
        get: operations["PurchaseSdkController_getPurchasesForCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/purchases/product/{productRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get purchases for a product
         * @description Retrieves all purchases for a specific product. Each billing period creates a new purchase document.
         */
        get: operations["PurchaseSdkController_getPurchasesForProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/purchases/{purchaseRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a purchase by reference
         * @description Retrieves a single purchase including plan snapshot, usage, and billing details.
         */
        get: operations["PurchaseSdkController_getPurchase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/purchases/{purchaseRef}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a purchase
         * @description Cancels an active purchase. For recurring purchases, cancellation takes effect at the end of the current billing period.
         */
        post: operations["PurchaseSdkController_cancelPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/purchases/{purchaseRef}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate a cancelled purchase
         * @description Reactivates a purchase that was cancelled but has not yet reached its end date. Restores auto-renewal and clears cancellation fields.
         */
        post: operations["PurchaseSdkController_reactivatePurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check usage limits for a customer and product
         * @description Checks whether a customer has an active purchase for a product and is within their usage limits. Returns a checkout URL if payment is required.
         */
        post: operations["LimitsSdkController_checkLimits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ActivateSdkController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer by reference, externalRef, or email
         * @description Retrieves a customer's details using their unique reference ID, externalRef, or email. Use query parameter 'reference' to look up by customer reference, 'externalRef' for external auth ID, or 'email' for customer email. Exactly one parameter must be provided. Returns the customer's name, email, and active purchases. Only customers owned by the authenticated provider can be accessed.
         */
        get: operations["CustomerSdkController_getCustomerByQuery"];
        put?: never;
        /**
         * Create a new customer
         * @description Creates a new customer record for the authenticated provider. Customers represent end-users who will purchase your products. Email is required and must be unique per provider. The name field is optional but recommended for better tracking.
         */
        post: operations["CustomerSdkController_createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/customers/{reference}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer credit balance
         * @description Returns the credit balance for a customer identified by reference.
         */
        get: operations["CustomerSdkController_getCustomerBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/customers/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer by reference
         * @description Retrieves a customer's details using their unique reference ID. Returns the customer's name, email, and active purchases. Only customers owned by the authenticated provider can be accessed.
         */
        get: operations["CustomerSdkController_getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/customers/customer-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a customer session
         * @description Creates a customer session URL that can be used to redirect customers to the customer page. Returns the customer URL and session ID. The session is short-lived (15 minutes) for security reasons.
         */
        post: operations["CustomerSdkController_createCustomerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/customers/customer-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer session by sessionId
         * @description Retrieves a customer session by its sessionId with all data hydrated including customer details and purchases. The session must belong to the authenticated provider.
         */
        get: operations["CustomerSdkController_getCustomerSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdk/user-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get user info and purchase status
         * @description Returns customer profile, active purchase details including usage and plan info, and a customer portal URL.
         */
        post: operations["UserInfoSdkController_getUserInfo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePaymentIntentDto: {
            productRef?: string;
            customerRef: string;
            planRef?: string;
            pricingTier?: string;
            /**
             * @default product
             * @enum {string}
             */
            purpose: "product" | "credit_topup" | "usage_billing";
            amount?: number;
            currency?: string;
            description?: string;
        };
        CreateCheckoutSessionRequest: {
            customerRef: string;
            productRef?: string;
            planRef?: string;
            returnUrl?: string;
            /** @enum {string} */
            purpose?: "credit_topup";
        };
        CancelPurchaseRequest: {
            reason?: string;
        };
        ProcessPaymentIntentDto: {
            productRef: string;
            customerRef: string;
            planRef?: string;
        };
        CreateCheckoutSessionResponse: {
            /**
             * Checkout session ID/token
             * @example e3f1c2d4b6a89f001122334455667788
             */
            sessionId: string;
            /**
             * Full checkout URL based on backend configuration (ready to redirect customer)
             * @example https://solvapay.com/customer/checkout?id=e3f1c2d4b6a89f001122334455667788
             */
            checkoutUrl: string;
        };
        Plan: {
            /**
             * Plan type exposed in SDK
             * @example recurring
             * @enum {string}
             */
            type: "recurring" | "one-time" | "usage-based" | "hybrid";
            /**
             * Plan reference
             * @example pln_1A2B3C4D
             */
            reference: string;
            /**
             * Meter reference for usage-based plans
             * @example mtr_1A2B3C4D
             */
            meterRef?: string;
            /**
             * Plan name
             * @example Starter
             */
            name?: string;
            /**
             * Plan description
             * @example Best for teams getting started
             */
            description?: string;
            /**
             * Plan price in cents
             * @example 2999
             */
            price: number;
            /**
             * Currency code (ISO 4217)
             * @example USD
             */
            currency: string;
            /**
             * Currency symbol (derived from currency)
             * @example $
             */
            currencySymbol?: string;
            /**
             * Number of free units included
             * @example 100
             */
            freeUnits?: number;
            /**
             * One-time setup fee
             * @example 500
             */
            setupFee?: number;
            /**
             * Free trial period in days
             * @example 14
             */
            trialDays?: number;
            /**
             * Billing cycle
             * @example monthly
             */
            billingCycle?: string;
            /**
             * Billing model
             * @example pre-paid
             * @enum {string}
             */
            billingModel?: "pre-paid" | "post-paid";
            /**
             * Credits per usage unit (integer, >= 1)
             * @example 1
             */
            creditsPerUnit?: number;
            /**
             * What the plan measures for usage tracking
             * @example requests
             */
            measures?: string;
            /**
             * Usage limit for the meter
             * @example 10000
             */
            limit?: number;
            /**
             * Whether unused units roll over to next period
             * @example false
             */
            rolloverUnusedUnits?: boolean;
            /** @description Usage limits */
            limits?: {
                [key: string]: unknown;
            };
            /** @description Plan features */
            features?: {
                [key: string]: unknown;
            };
            /**
             * Whether payment is required
             * @example true
             */
            requiresPayment: boolean;
            /**
             * Whether the plan is active (derived from status)
             * @example true
             */
            isActive: boolean;
            /** @description Maximum number of active users */
            maxActiveUsers?: number;
            /** @description Access expiry in days */
            accessExpiryDays?: number;
            /**
             * Plan status
             * @example active
             */
            status: string;
            /** @description Creation timestamp */
            createdAt: string;
            /** @description Last update timestamp */
            updatedAt: string;
        };
        CreatePlanRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            type?: "recurring" | "usage-based" | "one-time" | "hybrid";
            /** @enum {string} */
            billingCycle?: "weekly" | "monthly" | "quarterly" | "yearly" | "custom";
            price?: number;
            creditsPerUnit?: number;
            currency?: string;
            /** @enum {string} */
            billingModel?: "pre-paid" | "post-paid";
            freeUnits?: number;
            limit?: number;
            basePrice?: number;
            setupFee?: number;
            trialDays?: number;
            rolloverUnusedUnits?: boolean;
            autoRenew?: boolean;
            usageTracking: {
                /** @enum {string} */
                method?: "automatic" | "manual" | "hybrid";
                /** @enum {string} */
                granularity?: "hourly" | "daily" | "weekly" | "monthly";
            };
            limits: {
                [key: string]: unknown;
            };
            metadata: {
                [key: string]: unknown;
            };
            features: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status?: "active" | "inactive" | "archived";
            maxActiveUsers?: number;
            accessExpiryDays?: number;
            default?: boolean;
        };
        UpdatePlanRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            billingCycle?: "weekly" | "monthly" | "quarterly" | "yearly" | "custom";
            price?: number;
            creditsPerUnit?: number;
            currency?: string;
            /** @enum {string} */
            billingModel?: "pre-paid" | "post-paid";
            freeUnits?: number;
            limit?: number;
            limits: {
                [key: string]: unknown;
            };
            features: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status?: "active" | "inactive" | "archived";
            maxActiveUsers?: number;
            accessExpiryDays?: number;
            metadata: {
                [key: string]: unknown;
            };
            default?: boolean;
        };
        CreateProductRequest: {
            name: string;
            description?: string;
            imageUrl?: string;
            productType?: string;
            isMcpPay?: boolean;
            config: {
                fulfillmentType?: string;
                validityPeriod?: number;
                deliveryMethod?: string;
            };
            metadata: {
                [key: string]: unknown;
            };
        };
        ProductConfigDto: {
            /**
             * Fulfillment type
             * @example digital
             */
            fulfillmentType?: string;
            /**
             * Validity period in days
             * @example 30
             */
            validityPeriod?: number;
            /**
             * Delivery method
             * @example api
             */
            deliveryMethod?: string;
        };
        SdkPlanResponse: {
            /**
             * Plan reference
             * @example pln_1A2B3C4D
             */
            reference: string;
            /**
             * Plan price in cents
             * @example 2999
             */
            price: number;
            /**
             * Currency code (ISO 4217)
             * @example USD
             */
            currency: string;
            /**
             * Currency symbol
             * @example $
             */
            currencySymbol?: string;
            /**
             * One-time setup fee
             * @example 500
             */
            setupFee?: number;
            /**
             * Free trial period in days
             * @example 14
             */
            trialDays?: number;
            /**
             * Billing cycle
             * @example monthly
             */
            billingCycle?: string;
            /**
             * Billing model
             * @example pre-paid
             */
            billingModel?: string;
            /**
             * Credits per usage unit (integer, >= 1)
             * @example 1
             */
            creditsPerUnit?: number;
            /**
             * What the plan measures for usage tracking
             * @example requests
             */
            measures?: string;
            /**
             * Meter reference for usage-based limits
             * @example mtr_1A2B3C4D
             */
            meterRef?: string;
            /**
             * Usage limit for the meter
             * @example 10000
             */
            limit?: number;
            /**
             * Whether unused units roll over to next period
             * @example false
             */
            rolloverUnusedUnits?: boolean;
            /**
             * Included free units
             * @example 1000
             */
            freeUnits?: number;
            /** @description Usage limits */
            limits?: {
                [key: string]: unknown;
            };
            /** @description Plan features */
            features?: {
                [key: string]: unknown;
            };
            /**
             * Whether payment is required
             * @example true
             */
            requiresPayment: boolean;
            /**
             * Whether the plan is active
             * @example true
             */
            isActive: boolean;
            /**
             * Plan status
             * @example active
             */
            status: string;
            /** @description Creation timestamp */
            createdAt: string;
            /** @description Last update timestamp */
            updatedAt: string;
        };
        SdkProductResponse: {
            /**
             * Product reference
             * @example prd_1A2B3C4D
             */
            reference: string;
            /**
             * Product name
             * @example AI Writing Assistant
             */
            name: string;
            /** @description Product description */
            description?: string;
            /** @description URL to the product image */
            imageUrl?: string;
            /** @description Free-form product type */
            productType?: string;
            /**
             * Product status
             * @example active
             */
            status: string;
            /**
             * Product balance in cents
             * @example 0
             */
            balance: number;
            /**
             * Total number of transactions
             * @example 0
             */
            totalTransactions: number;
            /**
             * Whether this product uses MCP Pay proxy
             * @example false
             */
            isMcpPay: boolean;
            /** @description Product-specific configuration */
            config?: components["schemas"]["ProductConfigDto"];
            /** @description Arbitrary key-value metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Creation timestamp */
            createdAt: string;
            /** @description Last update timestamp */
            updatedAt: string;
            /** @description Plans associated with this product */
            plans?: components["schemas"]["SdkPlanResponse"][];
            /**
             * MCP linkage details for MCP-enabled products
             * @example {
             *       "mcpServerRef": "mcp_ABC123",
             *       "mcpSubdomain": "acme-docs",
             *       "mcpProxyUrl": "https://acme-docs.mcp.solvapay.com/mcp",
             *       "originUrl": "https://origin.example.com/mcp",
             *       "defaultPlanRef": "pln_FREE123"
             *     }
             */
            mcp?: {
                [key: string]: unknown;
            };
        };
        UpdateProductRequest: {
            name?: string;
            description?: string;
            imageUrl?: string;
            productType?: string;
            /** @enum {string} */
            status?: "active" | "inactive" | "suspended";
            config: {
                fulfillmentType?: string;
                validityPeriod?: number;
                deliveryMethod?: string;
            };
            metadata: {
                [key: string]: unknown;
            };
        };
        McpBootstrapDto: {
            name?: string;
            description?: string;
            imageUrl?: string;
            productType?: string;
            /** Format: uri */
            originUrl: string;
            mcpDomain?: string;
            authHeaderName?: string;
            authApiKey?: string;
            plans?: {
                key: string;
                name: string;
                price: number;
                currency: string;
                /** @enum {string} */
                billingCycle?: "weekly" | "monthly" | "quarterly" | "yearly" | "custom";
                /** @enum {string} */
                type?: "recurring" | "one-time" | "usage-based";
                creditsPerUnit?: number;
                /** @enum {string} */
                billingModel?: "pre-paid" | "post-paid";
                freeUnits?: number;
                limit?: number;
                features?: {
                    [key: string]: unknown;
                };
            }[];
            tools?: {
                name: string;
                description?: string;
                noPlan?: boolean;
                planKeys?: string[];
            }[];
            metadata: {
                [key: string]: unknown;
            };
        };
        McpBootstrapResult: {
            /** @description Created product */
            product: components["schemas"]["SdkProductResponse"];
            /**
             * Created or updated MCP server identity
             * @example {
             *       "reference": "mcp_ABC123",
             *       "subdomain": "acme-docs",
             *       "mcpProxyUrl": "https://acme-docs.mcp.solvapay.com/mcp",
             *       "url": "https://origin.example.com/mcp",
             *       "defaultPlanRef": "pln_FREE123"
             *     }
             */
            mcpServer: {
                [key: string]: unknown;
            };
            /**
             * Resolved plan mapping by bootstrap key
             * @example {
             *       "free": {
             *         "reference": "pln_FREE123",
             *         "name": "Free"
             *       }
             *     }
             */
            planMap: {
                [key: string]: unknown;
            };
            /**
             * True when tools were auto-discovered from origin because the request omitted tools
             * @example true
             */
            toolsAutoMapped?: boolean;
            /** @description Auto-discovered tools used during bootstrap */
            autoMappedTools?: {
                name?: string;
                description?: string;
            }[];
        };
        ConfigureMcpPlansDto: {
            plans?: {
                key: string;
                name: string;
                price: number;
                currency: string;
                /** @enum {string} */
                billingCycle?: "weekly" | "monthly" | "quarterly" | "yearly" | "custom";
                /** @enum {string} */
                type?: "recurring" | "one-time" | "usage-based";
                creditsPerUnit?: number;
                /** @enum {string} */
                billingModel?: "pre-paid" | "post-paid";
                freeUnits?: number;
                limit?: number;
                features?: {
                    [key: string]: unknown;
                };
            }[];
            toolMapping?: {
                name: string;
                planKeys: string[];
            }[];
        };
        ConfigureMcpPlansResult: {
            /** @description Updated product */
            product: components["schemas"]["SdkProductResponse"];
            /** @description Updated MCP server identity */
            mcpServer: {
                [key: string]: unknown;
            };
            /** @description Resolved plan mapping by key (includes existing free plan) */
            planMap: {
                [key: string]: unknown;
            };
        };
        CloneProductDto: {
            name?: string;
        };
        CreateUsageRequest: {
            customerRef: string;
            /**
             * @default api_call
             * @enum {string}
             */
            actionType: "transaction" | "api_call" | "hour" | "email" | "storage" | "custom";
            /** @default 1 */
            units: number;
            /**
             * @default success
             * @enum {string}
             */
            outcome: "success" | "paywall" | "fail";
            productRef?: string;
            purchaseRef?: string;
            description?: string;
            errorMessage?: string;
            metadata: {
                [key: string]: unknown;
            };
            duration?: number;
            /** Format: date-time */
            timestamp: string;
            idempotencyKey?: string;
        };
        BulkCreateUsageRequest: {
            events: {
                customerRef: string;
                /**
                 * @default api_call
                 * @enum {string}
                 */
                actionType: "transaction" | "api_call" | "hour" | "email" | "storage" | "custom";
                /** @default 1 */
                units: number;
                /**
                 * @default success
                 * @enum {string}
                 */
                outcome: "success" | "paywall" | "fail";
                productRef?: string;
                purchaseRef?: string;
                description?: string;
                errorMessage?: string;
                metadata?: {
                    [key: string]: unknown;
                };
                duration?: number;
                /** Format: date-time */
                timestamp: string;
                idempotencyKey?: string;
            }[];
        };
        RecordMeterEventZodDto: {
            meterName: string;
            customerRef: string;
            value?: number;
            properties: {
                [key: string]: unknown;
            };
            productRef?: string;
            timestamp?: string;
        };
        RecordBulkMeterEventsZodDto: {
            events: {
                meterName: string;
                customerRef: string;
                value?: number;
                properties?: {
                    [key: string]: unknown;
                };
                productRef?: string;
                timestamp?: string;
            }[];
        };
        UsageBillingDto: {
            /**
             * Units consumed in current period
             * @example 150
             */
            used: number;
            /**
             * Units exceeding the plan limit
             * @example 0
             */
            overageUnits: number;
            /**
             * Overage cost in cents
             * @example 0
             */
            overageCost: number;
            /**
             * Period start date
             * @example 2025-10-01T00:00:00Z
             */
            periodStart?: string;
            /**
             * Period end date
             * @example 2025-11-01T00:00:00Z
             */
            periodEnd?: string;
        };
        SdkPlanSnapshotDto: {
            /**
             * Plan reference
             * @example pln_1A2B3C4D
             */
            reference?: string;
            /**
             * Plan price in cents
             * @example 2999
             */
            price: number;
            /**
             * Currency code
             * @example USD
             */
            currency: string;
            /**
             * Plan type
             * @example recurring
             */
            planType: string;
            /**
             * Billing cycle
             * @example monthly
             */
            billingCycle?: string | null;
            /** @description Plan features */
            features?: {
                [key: string]: unknown;
            } | null;
            /** @description Usage limits */
            limits?: {
                [key: string]: unknown;
            } | null;
            /**
             * Meter reference
             * @example mtr_1A2B3C4D
             */
            meterRef?: string;
            /**
             * Usage limit for the meter
             * @example 5000
             */
            limit?: number;
            /**
             * Number of free units included
             * @example 100
             */
            freeUnits?: number;
            /**
             * Credits per usage unit (integer, >= 1)
             * @example 1
             */
            creditsPerUnit?: number;
        };
        SdkPurchaseResponse: {
            /**
             * Purchase reference
             * @example pur_1A2B3C4D
             */
            reference: string;
            /**
             * Customer reference
             * @example cus_3C4D5E6F
             */
            customerRef: string;
            /**
             * Customer email
             * @example customer@example.com
             */
            customerEmail: string;
            /**
             * Product reference
             * @example prd_1A2B3C4D
             */
            productRef: string;
            /**
             * Product name
             * @example API Gateway Manager
             */
            productName?: string;
            /** @description Plan snapshot at time of purchase (null for credit topups) */
            planSnapshot?: components["schemas"]["SdkPlanSnapshotDto"];
            /**
             * Purchase status
             * @example active
             */
            status: string;
            /**
             * Amount in USD cents (normalised for aggregation)
             * @example 9900
             */
            amount: number;
            /**
             * Original amount in the payment currency (cents/pence)
             * @example 10000
             */
            originalAmount?: number;
            /**
             * Original payment currency code
             * @example GBP
             */
            currency: string;
            /**
             * Exchange rate from original currency to USD
             * @example 1.3082
             */
            exchangeRate?: number;
            /** @description Start date */
            startDate: string;
            /** @description End date */
            endDate?: string;
            /** @description Paid at timestamp */
            paidAt?: string;
            /** @description Usage billing state for usage-based plans */
            usage?: components["schemas"]["UsageBillingDto"];
            /**
             * Is recurring
             * @example true
             */
            isRecurring: boolean;
            /**
             * Billing cycle
             * @enum {string}
             */
            billingCycle?: "weekly" | "monthly" | "quarterly" | "yearly";
            /** @description Next billing date */
            nextBillingDate?: string;
            /** @description Auto-renew enabled */
            autoRenew?: boolean;
            /** @description Cancelled at */
            cancelledAt?: string;
            /** @description Cancellation reason */
            cancellationReason?: string;
            /** @description Arbitrary metadata attached to the purchase */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Created at */
            createdAt: string;
        };
        CheckLimitRequest: {
            customerRef: string;
            productRef: string;
            meterName?: string;
            usageType?: string;
        };
        LimitPlanItemDto: {
            reference: string;
            name?: string;
            type: string;
            /** @description Price in smallest currency unit (e.g. cents) */
            price: number;
            currency: string;
            requiresPayment: boolean;
            freeUnits?: number;
            /** @description Credits per usage unit (usage-based plans) */
            creditsPerUnit?: number;
            billingModel?: string;
            billingCycle?: string;
        };
        LimitBalanceDto: {
            /** @description Credit balance in mils */
            creditBalance: number;
            /** @description Credits per usage unit */
            creditsPerUnit: number;
            currency: string;
            /** @description Estimated whole units remaining from prepaid credit balance */
            remainingUnits?: number;
        };
        LimitProductBriefDto: {
            reference: string;
            name?: string;
        };
        LimitResponse: {
            /**
             * Whether the customer is within their usage limits
             * @example true
             */
            withinLimits: boolean;
            /**
             * Remaining usage units before hitting the limit
             * @example 997
             */
            remaining: number;
            /**
             * Checkout session ID if payment is required
             * @example e3f1c2d4b6a89f001122334455667788
             */
            checkoutSessionId?: string;
            /**
             * Checkout URL if payment is required
             * @example https://solvapay.com/customer/checkout?id=e3f1c2d4b6a89f001122334455667788
             */
            checkoutUrl?: string;
            /**
             * The meter name to use when tracking usage events
             * @example requests
             */
            meterName?: string;
            /** @description Credit balance in mils (for pre-paid usage-based plans) */
            creditBalance?: number;
            /** @description Credits per usage unit (for pre-paid usage-based plans) */
            creditsPerUnit?: number;
            /** @description ISO 4217 currency code for credit fields */
            currency?: string;
            /** @description True when the customer must activate a priced default plan before usage is allowed */
            activationRequired?: boolean;
            /** @description Active plans on the product available for activation or checkout */
            plans?: components["schemas"]["LimitPlanItemDto"][];
            /** @description Prepaid usage balance context when the default plan is usage-based */
            balance?: components["schemas"]["LimitBalanceDto"];
            /** @description Product the limit check applies to */
            product?: components["schemas"]["LimitProductBriefDto"];
            /** @description Customer portal confirmation URL when activation is required (fallback when not starting checkout) */
            confirmationUrl?: string;
        };
        ActivatePlanDto: {
            customerRef: string;
            productRef: string;
            planRef: string;
        };
        ActivatePlanResponseDto: {
            /** @enum {string} */
            status: "activated" | "already_active" | "topup_required" | "payment_required" | "invalid";
            purchaseRef?: string;
            message?: string;
            creditBalance?: number;
            creditsPerUnit?: number;
            currency?: string;
            checkoutUrl?: string;
            checkoutSessionId?: string;
        };
        CreateCustomerRequest: {
            /** Format: email */
            email: string;
            name?: string;
            telephone?: string;
            metadata: {
                [key: string]: unknown;
            };
            externalRef?: string;
        };
        CreateCustomerSessionRequest: {
            customerRef: string;
            productRef?: string;
        };
        PurchaseInfo: {
            /**
             * Purchase reference
             * @example pur_1A2B3C4D
             */
            reference: string;
            /**
             * Product name
             * @example API Gateway Manager
             */
            productName: string;
            /**
             * Product reference
             * @example prd_abc123
             */
            productRef?: string;
            /**
             * Purchase status
             * @example active
             */
            status: string;
            /**
             * Start date
             * @example 2025-10-27T10:00:00Z
             */
            startDate: string;
            /**
             * Amount in USD cents (normalised for aggregation)
             * @example 9900
             */
            amount: number;
            /**
             * Original amount in the payment currency (minor units)
             * @example 7500
             */
            originalAmount?: number;
            /**
             * ISO 4217 currency code of the customer-facing charge
             * @example GBP
             */
            currency: string;
            /**
             * Exchange rate from original currency to USD
             * @example 1.32
             */
            exchangeRate?: number;
            /**
             * End date of purchase
             * @example 2025-11-27T10:00:00Z
             */
            endDate?: string;
            /**
             * When purchase was cancelled
             * @example 2025-10-28T10:00:00Z
             */
            cancelledAt?: string;
            /**
             * Reason for cancellation
             * @example Customer request
             */
            cancellationReason?: string;
            /**
             * Plan reference from the plan snapshot, for reliable plan matching
             * @example pln_abc123
             */
            planRef?: string;
            /** @description Snapshot of the plan at time of purchase */
            planSnapshot?: Record<string, never>;
        };
        CustomerResponse: {
            /**
             * Customer reference identifier
             * @example cus_3c4d5e6f7g8h
             */
            reference: string;
            /**
             * Customer full name
             * @example John Doe
             */
            name: string;
            /**
             * Customer email address
             * @example customer@example.com
             */
            email: string;
            /**
             * External reference ID from your auth system (if set during creation or update)
             * @example auth_user_12345
             */
            externalRef?: string;
            /** @description Active purchases */
            purchases?: components["schemas"]["PurchaseInfo"][];
        };
        CreateCustomerSessionResponse: {
            /**
             * Customer session ID/token
             * @example e3f1c2d4b6a89f001122334455667788
             */
            sessionId: string;
            /**
             * Full customer URL based on backend configuration (ready to redirect customer)
             * @example https://solvapay.com/customer/manage?id=e3f1c2d4b6a89f001122334455667788
             */
            customerUrl: string;
        };
        GetCustomerSessionResponse: {
            /**
             * Customer session ID/token
             * @example e3f1c2d4b6a89f001122334455667788
             */
            sessionId: string;
            /**
             * Session status
             * @example active
             * @enum {string}
             */
            status: "active" | "expired" | "used";
            /**
             * Full customer URL based on backend configuration (ready to redirect customer)
             * @example https://solvapay.com/customer/manage?id=e3f1c2d4b6a89f001122334455667788
             */
            customerUrl: string;
            /**
             * Session expiration date
             * @example 2025-01-01T12:00:00.000Z
             */
            expiresAt: string;
            /** @description Customer object from session data */
            customer: components["schemas"]["CustomerResponse"];
            /**
             * Session creation date
             * @example 2025-01-01T11:45:00.000Z
             */
            createdAt: string;
            /**
             * Session last update date
             * @example 2025-01-01T11:45:00.000Z
             */
            updatedAt: string;
        };
        UserInfoRequest: {
            customerRef: string;
            productRef: string;
        };
        UserInfoUserDto: {
            /** @example cus_3C4D5E6F */
            reference: string;
            /** @example John Doe */
            name?: string | null;
            /** @example john@example.com */
            email: string;
            /** @example auth_user_12345 */
            externalRef?: string | null;
        };
        UserInfoUsageDto: {
            /** @example 1000 */
            total: number;
            /** @example 250 */
            used: number;
            /** @example 750 */
            remaining: number;
            /**
             * Meter reference
             * @example meter_ABC123
             */
            meterRef?: string | null;
            /** @example 25 */
            percentUsed?: number | null;
        };
        UserInfoPlanDto: {
            /** @example pln_2B3C4D5E */
            reference: string;
            /**
             * Price in minor currency units (e.g. cents)
             * @example 2999
             */
            price: number;
            /** @example USD */
            currency: string;
            /** @example recurring */
            type: string;
            /** @example monthly */
            billingCycle?: string | null;
            features?: string[] | null;
            limits?: {
                [key: string]: unknown;
            } | null;
        };
        UserInfoPurchaseDto: {
            /** @example pur_1A2B3C4D */
            reference: string;
            /** @example active */
            status: string;
            /** @example My API Product */
            productName: string;
            /** @example recurring */
            planType: string;
            /** @example 2025-10-27T10:00:00Z */
            startDate?: string | null;
            /** @example 2025-11-27T10:00:00Z */
            endDate?: string | null;
            usage?: components["schemas"]["UserInfoUsageDto"];
            plan?: components["schemas"]["UserInfoPlanDto"];
        };
        UserInfoResponse: {
            /**
             * Human-readable status summary
             * @example Active subscription: My API Product (25% usage consumed)
             */
            status: string;
            /**
             * Customer portal session URL
             * @example https://solvapay.com/customer/manage?id=abc123
             */
            verifyUrl?: string | null;
            user?: components["schemas"]["UserInfoUserDto"];
            purchase?: components["schemas"]["UserInfoPurchaseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PaymentIntentSdkController_getPaymentIntents: {
        parameters: {
            query?: {
                /** @description Maximum number of results */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment intents retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    PaymentIntentSdkController_createPaymentIntent: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique idempotency key to prevent duplicate payments (required) */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description Payment intent creation data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentIntentDto"];
            };
        };
        responses: {
            /** @description Payment intent created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing required fields or invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    PaymentIntentSdkController_getPaymentIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Payment intent reference or processor payment ID */
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment intent retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Payment intent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    PaymentIntentSdkController_processPaymentIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Payment processor ID returned from createPaymentIntent */
                processorPaymentId: string;
            };
            cookie?: never;
        };
        /** @description Payment processing data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessPaymentIntentDto"];
            };
        };
        responses: {
            /** @description Payment intent status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Payment intent status
                         * @example succeeded
                         * @enum {string}
                         */
                        status?: "succeeded" | "timeout" | "failed" | "cancelled";
                        /**
                         * Optional message, only present for timeout status
                         * @example Timeout while waiting for payment intent confirmation, try again later. This could be due to payment webhooks not being configured correctly.
                         */
                        message?: string;
                    };
                };
            };
            /** @description Payment not succeeded, invalid request, or forbidden */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CheckoutSessionSdkController_createCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Checkout session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCheckoutSessionResponse"];
                };
            };
            /** @description Missing customerRef or productRef */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanSdkController_listPlans: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plans retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plans?: components["schemas"]["Plan"][];
                        /** @description Total number of plans for the product */
                        total?: number;
                        limit?: number;
                        offset?: number;
                    };
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanSdkController_createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanSdkController_getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
                /** @description Plan reference or ID */
                planRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Plan or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanSdkController_updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
                /** @description Plan reference or ID */
                planRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Plan or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanSdkController_deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
                /** @description Plan reference or ID */
                planRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plan or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_listProducts: {
        parameters: {
            query?: {
                /** @description Max results (1-100) */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
                /** @description Search by name or description */
                search?: string;
                /** @description Filter by status */
                status?: "active" | "inactive" | "suspended";
                /** @description Filter MCP Pay products */
                isMcpPay?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Product created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdkProductResponse"];
                };
            };
            /** @description Missing required fields or validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdkProductResponse"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description Product updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdkProductResponse"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted or deactivated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_bootstrapMcpProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpBootstrapDto"];
            };
        };
        responses: {
            /** @description MCP product bootstrapped successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpBootstrapResult"];
                };
            };
            /** @description Invalid bootstrap request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_configureMcpPlans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureMcpPlansDto"];
            };
        };
        responses: {
            /** @description MCP plans configured successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureMcpPlansResult"];
                };
            };
            /** @description Invalid MCP plans request or product is not MCP-enabled */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSdkController_cloneProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID to clone */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneProductDto"];
            };
        };
        responses: {
            /** @description Product cloned successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdkProductResponse"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsageSdkController_recordUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUsageRequest"];
            };
        };
        responses: {
            /** @description Usage recorded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /** @example usage_A1B2C3D4 */
                        reference?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsageSdkController_recordBulkUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCreateUsageRequest"];
            };
        };
        responses: {
            /** @description Bulk usage events processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeterEventsSdkController_recordEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMeterEventZodDto"];
            };
        };
        responses: {
            /** @description Event recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
            /** @description Invalid meter name or meter is archived */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeterEventsSdkController_recordBulkEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordBulkMeterEventsZodDto"];
            };
        };
        responses: {
            /** @description Events recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /** @example 50 */
                        inserted?: number;
                    };
                };
            };
            /** @description Invalid meter name or meter is archived */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseSdkController_listPurchases: {
        parameters: {
            query?: {
                /** @description Filter by purchase status */
                status?: "pending" | "active" | "trialing" | "past_due" | "cancelled" | "expired" | "suspended" | "refunded";
                /** @description Filter by product reference */
                productRef?: string;
                /** @description Filter by customer reference */
                customerRef?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchases retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        purchases?: components["schemas"]["SdkPurchaseResponse"][];
                    };
                };
            };
        };
    };
    PurchaseSdkController_getPurchasesForCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer reference or ID */
                customerRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer purchases retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        purchases?: components["schemas"]["SdkPurchaseResponse"][];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseSdkController_getPurchasesForProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product reference or ID */
                productRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product purchases retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        purchases?: components["schemas"]["SdkPurchaseResponse"][];
                    };
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseSdkController_getPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Purchase reference or ID */
                purchaseRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdkPurchaseResponse"];
                };
            };
            /** @description Purchase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseSdkController_cancelPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Purchase reference or ID */
                purchaseRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelPurchaseRequest"];
            };
        };
        responses: {
            /** @description Purchase cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        purchase?: components["schemas"]["SdkPurchaseResponse"];
                    };
                };
            };
            /** @description Purchase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchaseSdkController_reactivatePurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Purchase reference or ID */
                purchaseRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase reactivated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        purchase?: components["schemas"]["SdkPurchaseResponse"];
                    };
                };
            };
            /** @description Purchase cannot be reactivated */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Purchase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LimitsSdkController_checkLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckLimitRequest"];
            };
        };
        responses: {
            /** @description Limit check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitResponse"];
                };
            };
            /** @description Missing customerRef or productRef */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ActivateSdkController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivatePlanDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivatePlanResponseDto"];
                };
            };
        };
    };
    CustomerSdkController_getCustomerByQuery: {
        parameters: {
            query?: {
                /** @description Customer reference identifier (use exactly one query parameter) */
                reference?: string;
                /** @description External reference ID from your auth system (use exactly one query parameter) */
                externalRef?: string;
                /** @description Customer email address (use exactly one query parameter) */
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description Invalid request - must provide exactly one of reference, externalRef, or email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CustomerSdkController_createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Customer creation data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description Customer created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description Invalid email or missing required fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CustomerSdkController_getCustomerBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer reference identifier */
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer balance retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CustomerSdkController_getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer reference identifier */
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CustomerSdkController_createCustomerSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Customer session creation request data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerSessionRequest"];
            };
        };
        responses: {
            /** @description Customer session created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCustomerSessionResponse"];
                };
            };
            /** @description Invalid request data or customer not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CustomerSdkController_getCustomerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer session ID/token */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer session retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCustomerSessionResponse"];
                };
            };
            /** @description Customer session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UserInfoSdkController_getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInfoRequest"];
            };
        };
        responses: {
            /** @description User info with purchase status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            /** @description Missing customerRef or productRef */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
