/**
 * @generated by dto-gen (--core-types-ts-out) — do not edit. Regenerate with: pnpm gen
 */

import type { SupportedBusinessCountry, TaxIdType } from '../business-details'

/**
 * Degraded allow reason. Absent on a plain allow.
 */
export type AllowConsequence = 'throttled' | 'overage'

/**
 * Inputs for [`resolve_authenticated_user`] (facade resolves env / Request).
 */
export type AuthResolutionInput = {
  /**
   * `x-user-id` header value when present.
   */
  headerUserId: string | null
  /**
   * Raw `Authorization` header value when present.
   */
  authorizationHeader: string | null
  /**
   * JWT secret (`SOLVAPAY_JWT_SECRET` || `SUPABASE_JWT_SECRET`).
   */
  jwtSecret: string | null
  /**
   * `SOLVAPAY_AUTH_STRICT === 'true'`.
   */
  strictMode: boolean
  /**
   * Facade default: `options.includeEmail !== false`.
   */
  includeEmail: boolean
  /**
   * Facade default: `options.includeName !== false`.
   */
  includeName: boolean
  /**
   * Explicit clock for `exp` / `nbf` (jose uses wall clock; fixtures use far dates).
   */
  nowUnixSecs: number
}

/**
 * Successful authenticated-user payload (email/name serialize as explicit `null`).
 */
export type AuthenticatedUser = {
  /**
   * Subject / middleware user id.
   */
  userId: string
  /**
   * Email when extracted; otherwise JSON `null`.
   */
  email: string | null
  /**
   * Display name when extracted; otherwise JSON `null`.
   */
  name: string | null
}

/**
 * A billing-cycle option — present only on recurring plans.
 */
export type BillingCycle = {
  /**
   * Recurring cadence of this cycle.
   */
  interval: BillingInterval
  /**
   * Interval count when greater than 1; omitted for the default of 1.
   */
  count?: number
}

/**
 * Recurring cadence of a billing cycle.
 */
export type BillingInterval = 'week' | 'month' | 'year'

/**
 * Input shape for [`validate_business_details`] (parity with `BusinessDetailsInput` in TS).
 */
export type BusinessDetailsInput = {
  /**
   * Whether the purchaser is buying as a business.
   */
  isBusiness: boolean
  /**
   * Legal business name (trimmed when present).
   */
  businessName?: string
  /**
   * Business country ISO code (required when `is_business` is true).
   */
  country?: string
  /**
   * Billing country for non-business purchases (tax calculation).
   */
  customerCountry?: string
  /**
   * Customer display name (max 100 characters).
   */
  customerName?: string
  /**
   * Tax ID to validate against the business country matcher.
   */
  taxId?: string
  /**
   * Explicit tax-ID type override (normally derived from country).
   */
  taxIdType?: unknown
}

/**
 * Validation failure payload returned by [`validate_business_details`].
 */
export type BusinessDetailsValidationError = {
  /**
   * One or more field-level validation issues.
   */
  issues: BusinessDetailsValidationIssue[]
}

/**
 * Cache-hit path evaluation (host applies `evict` to the Map).
 */
export type CachedLimitsEvaluation = {
  /**
   * Whether the request is within limits.
   */
  withinLimits: boolean
  /**
   * Remaining after optimistic decrement (or `0` on the block-once path).
   */
  remaining: number
  /**
   * When true, host must delete the cache entry.
   */
  evict: boolean
}

/**
 * A charge option. `amount_minor` is in `currency`'s minor units.
 */
export type Charge = {
  /**
   * Which quantity the amount is charged against.
   */
  per: ChargePer
  /**
   * Amount in the charge currency's minor units.
   */
  amountMinor: number
  /**
   * ISO currency code as shipped on the wire (not normalised).
   */
  currency: string
  /**
   * Meter name when `per` is `unit`.
   */
  meter?: string
  /**
   * Setup-fee flag; omitted unless `true`.
   */
  oneTime?: boolean
}

/**
 * Which quantity the amount is charged against.
 */
export type ChargePer = 'flat' | 'unit' | 'seat'

/**
 * Resolved check-limits query params.
 */
export type CheckLimitsParams = {
  /**
   * Required product reference.
   */
  productRef: string
  /**
   * Meter name (`'requests'` when the input was falsy).
   */
  meterName: string
}

/**
 * Coerced email/name options (`null`/`''` → omitted).
 */
export type CoercedCustomerOptions = {
  /**
   * Email when non-empty.
   */
  email?: string
  /**
   * Name when non-empty.
   */
  name?: string
}

/**
 * createCustomer request params.
 */
export type CreateCustomerParams = {
  /**
   * Email (provided or generated fallback).
   */
  email: string
  /**
   * Optional display name.
   */
  name?: string
  /**
   * Optional external reference.
   */
  externalRef?: string
  /**
   * Always `{}` today.
   */
  metadata: Record<string, unknown>
}

/**
 * createCustomer error classification for 409 recovery.
 */
export type CreateErrorKind = 'conflict' | 'other'

/**
 * Classification of a customerRef before ensure/lookup.
 */
export type CustomerRefKind = 'anonymous' | 'backend' | 'needsEnsure'

/**
 * Merchant-facing customer projection from the last limits check.
 * 
 * Rust applies `creditBalance ?? 0` and `withinLimits ?? true` so hosts do not
 * re-derive those defaults.
 */
export type CustomerSnapshot = {
  /**
   * Backend customer ref.
   */
  ref: string
  /**
   * `creditBalance` from limits, or `0` when absent.
   */
  balance: number
  /**
   * Remaining allowance from limits (JSON `null` when absent).
   */
  remaining: unknown
  /**
   * `withinLimits` from limits, or `true` when absent.
   */
  withinLimits: boolean
  /**
   * Plan field from limits; omitted when absent / JSON `null`.
   */
  plan: unknown
  /**
   * `throttled` from limits, or `false` when absent.
   */
  throttled: boolean
  /**
   * `overage` from limits, or `false` when absent.
   */
  overage: boolean
}

/**
 * Next host action or a terminal resolve.
 */
export type EnsureCustomerAction =
  | { kind: 'readCustomerCache'; key: string }
  | { kind: 'getCustomer'; byExternalRef?: string; byEmail?: string }
  | { kind: 'createCustomer'; params: CreateCustomerParams }
  | { kind: 'updateCustomer'; customerRef: string; patch: Record<string, unknown> }
  | { kind: 'resolved'; backendRef: string; cache?: EnsureCustomerCacheWrite }

/**
 * Cache write bundled onto [`EnsureCustomerAction::Resolved`].
 */
export type EnsureCustomerCacheWrite = {
  /**
   * Cache key.
   */
  key: string
  /**
   * Backend customer ref to store.
   */
  backendRef: string
  /**
   * Host `nowMs` — authoritative; hosts must not restamp.
   */
  timestampMs: number
}

/**
 * Driver output.
 */
export type EnsureCustomerNextOutput = {
  /**
   * State to pass into the next call.
   */
  state: EnsureCustomerState
  /**
   * Host action or terminal result.
   */
  action: EnsureCustomerAction
}

/**
 * Driver state between ensure-customer steps.
 */
export type EnsureCustomerState = {
  /**
   * App customer ref from `start`.
   */
  customerRef: string
  /**
   * Optional explicit external ref (lookup/create key when set).
   */
  externalRef?: string
  /**
   * Optional explicit email.
   */
  email?: string
  /**
   * Optional display name.
   */
  name?: string
  /**
   * Host can call `createCustomer`.
   */
  canCreateCustomer: boolean
  /**
   * Host can call `updateCustomer`.
   */
  canUpdateCustomer: boolean
  /**
   * Dedup TTL in ms.
   */
  dedupTTLMs: number
  /**
   * Cache map key (`externalRef` or `customerRef`).
   */
  cacheKey: string
  /**
   * Which result event the driver is waiting for.
   */
  pending: EnsurePending
  /**
   * Last create/lookup error message (409 ladder).
   */
  lastError?: string
  /**
   * Backend ref held across `updateCustomer`.
   */
  pendingBackendRef?: string
  /**
   * First `createCustomer` already issued in this session.
   */
  createAttempted: boolean
  /**
   * Generated-email retry already issued.
   */
  generatedEmailAttempted: boolean
}

/**
 * In-flight step the next host event must complete.
 */
export type EnsurePending = 'none' | 'cache' | 'lookupInitial' | 'create' | 'lookupConflictExternal' | 'lookupConflictEmail' | 'updateBackfill' | 'createGeneratedEmail'

/**
 * Cache-miss path evaluation after `checkLimits` returns.
 */
export type FreshLimitsEvaluation = {
  /**
   * Whether the request is within limits.
   */
  withinLimits: boolean
  /**
   * Remaining after optimistic consume (unchanged when not consumed).
   */
  remaining: number
  /**
   * When true, host should write the decremented entry into the cache.
   */
  shouldCache: boolean
}

/**
 * Next host action, or a terminal allow/gate.
 */
export type GateAction =
  | { kind: 'ensureCustomer'; customerRef: string }
  | { kind: 'readLimitsCache'; key: string }
  | { kind: 'checkLimits'; customerRef: string; productRef: string; meterName: string; includeCheckoutSession: boolean; cacheDeleteKey?: string }
  | { kind: 'allow'; customerRef: string; product: string; meterName: string; limits: unknown; customer: CustomerSnapshot; consequence?: AllowConsequence; cache?: GateCacheOp }
  | { kind: 'gate'; customerRef: string; product: string; meterName: string; limits: unknown; customer: CustomerSnapshot; gate: unknown; cache?: GateCacheOp; request: unknown }
  | { kind: 'emitUsage'; request: unknown }
  | { kind: 'skipUsage' }

/**
 * Cache mutation the host must apply before continuing / returning.
 */
export type GateCacheOp =
  | { op: 'set'; key: string; remaining: number; limits: unknown; timestamp: number; checkoutUrl?: string; meterName?: string }
  | { op: 'updateRemaining'; key: string; remaining: number }
  | { op: 'delete'; key: string }

/**
 * Opaque-enough driver state passed back on every step.
 */
export type GateDriverState = {
  /**
   * Product reference used for limits and the assembled gate.
   */
  product: string
  /**
   * Resolved meter name (`usageType` with the `requests` default).
   */
  meterName: string
  /**
   * Customer ref supplied on `start`.
   */
  originalCustomerRef: string
  /**
   * Backend customer ref after classify / ensure.
   */
  backendRef?: string
  /**
   * Host clock at `start` (ms). Used for paywall `track` duration.
   */
  startedMs: number
  /**
   * `backendRef:product:meterName` once the backend ref is known.
   */
  limitsKey?: string
  /**
   * Limits-cache TTL in ms (`limitsCacheTTLMs`, default 10000).
   */
  limitsCacheTTLMs: number
}

/**
 * Driver output: updated state plus the next action.
 */
export type GateNextOutput = {
  /**
   * State to pass into the next `gate_next` call.
   */
  state: GateDriverState
  /**
   * Host action or terminal result.
   */
  action: GateAction
}

/**
 * Included-usage counters emitted on gates when `freeUnits` is a positive cap.
 */
export type IncludedUsage = {
  /**
   * Included units for the period (`freeUnits`).
   */
  total: number
  /**
   * Derived as `max(0, total - remaining)`.
   */
  used: number
  /**
   * Remaining included units from the limits response.
   */
  remaining: number
}

/**
 * Next host action or a formatted tool result.
 */
export type InvokePayableAction =
  | { kind: 'runGate'; customerRef: string; product: string; usageType: string }
  | { kind: 'invokeHandler'; customerRef: string; limits: unknown }
  | { kind: 'done'; result: unknown; track?: InvokePayableTrack }

/**
 * Driver output.
 */
export type InvokePayableNextOutput = {
  /**
   * State to pass into the next call.
   */
  state: InvokePayableState
  /**
   * Host action or terminal result.
   */
  action: InvokePayableAction
}

/**
 * Driver state between payable steps.
 */
export type InvokePayableState = {
  /**
   * Product the tool is protected against.
   */
  product: string
  /**
   * Meter / usage type.
   */
  usageType: string
  /**
   * Customer ref after host resolution.
   */
  customerRef: string
  /**
   * Host clock at start (ms).
   */
  startedMs: number
}

/**
 * Post-handler usage track.
 */
export type InvokePayableTrack = {
  /**
   * `"success"` or `"fail"`.
   */
  outcome: string
  /**
   * Elapsed ms from start.
   */
  durationMs: number
  /**
   * Complete `trackUsage` body rendered by core. Host POSTs this verbatim.
   */
  request: unknown
}

/**
 * Lookup-error classification for getCustomer misses.
 */
export type LookupErrorKind = 'expectedMissing' | 'unexpected'

/**
 * MCP tool result for an allowed payable handler (`SolvaPayCallToolResult` allow path).
 * 
 * `is_error` is omitted (`skip_serializing_if`) — allow is not a tool error.
 */
export type McpPayableToolResult = {
  /**
   * Omitted on the allow path.
   */
  isError?: boolean
  /**
   * Emitted blocks, then one `{ type: "text", text }` primary block.
   */
  content: unknown[]
  /**
   * Raw merchant `data` (not the branded envelope).
   */
  structuredContent: unknown
}

/**
 * Projected create-PI / create-topup helper return shape.
 */
export type PaymentIntentProjection = {
  /**
   * Processor payment id.
   */
  processorPaymentId: string
  /**
   * Client secret for confirmation.
   */
  clientSecret: string
  /**
   * Publishable key.
   */
  publishableKey: string
  /**
   * Connected account id (skip-absent when [`None`]).
   */
  accountId?: string
  /**
   * Synced customer reference.
   */
  customerRef: string
}

/**
 * Result of [`evaluate_product_readiness`].
 */
export type ProductReadinessResult = {
  /**
   * True when status is active and at least one plan is active.
   */
  ready: boolean
  /**
   * Human-readable reasons `ready` is false. Empty when ready.
   */
  issues: string[]
  /**
   * Count of active plans.
   */
  activePlans: number
  /**
   * Total plan count (including inactive).
   */
  totalPlans: number
}

/**
 * Resolved seller identity rows. Absent rows serialize as JSON `null`.
 */
export type SellerIdentityDisplay = {
  /**
   * Country-aware tax / VAT / EIN row, if a value is available.
   */
  taxIdentifier: SellerIdentityRow | null
  /**
   * Company-number row when distinct from the tax identifier.
   */
  companyNumber: SellerIdentityRow | null
}

/**
 * One labeled identity row.
 */
export type SellerIdentityRow = {
  /**
   * Human-readable field label (e.g. `"VAT number"`).
   */
  label: string
  /**
   * Stored identifier value to display.
   */
  value: string
}

/**
 * One band of a tiered price. `[from, to)` in metered units; `to: null` is unbounded.
 */
export type Tier = {
  /**
   * Inclusive floor of this band, in metered units.
   */
  from: number
  /**
   * Exclusive ceiling, or `None` for the unbounded top band.
   */
  to: number | null
  /**
   * Graduated vs volume pricing of this stack.
   */
  mode: TierMode
  /**
   * Per-unit charge that prices units in this band.
   */
  charge: Charge
}

/**
 * How a tier stack prices successive bands.
 */
export type TierMode = 'graduated' | 'volume'

/**
 * In-flight step the next host event must complete.
 */
export type TopupPending = 'none' | 'syncCustomer' | 'baselineBalance' | 'processPayment' | 'sleep' | 'pollBalance'

/**
 * Next host action or a terminal resolve.
 */
export type TopupProcessAction =
  | { kind: 'syncCustomer' }
  | { kind: 'getCustomerBalance'; customerRef: string }
  | { kind: 'processPaymentIntent'; paymentIntentId: string; customerRef: string }
  | { kind: 'sleep'; ms: number }
  | { kind: 'resolved'; status: string; message?: string; creditsAdded?: number }

/**
 * Driver output.
 */
export type TopupProcessNextOutput = {
  /**
   * State to pass into the next call.
   */
  state: TopupProcessState
  /**
   * Host action or terminal result.
   */
  action: TopupProcessAction
}

/**
 * Driver state between top-up process steps.
 */
export type TopupProcessState = {
  /**
   * Processor payment intent id.
   */
  paymentIntentId: string
  /**
   * Synced customer ref, once known.
   */
  customerRef?: string
  /**
   * Host can call `getCustomerBalance`.
   */
  canGetBalance: boolean
  /**
   * Baseline credits captured before `/process`. Absent means skip polling.
   */
  baselineCredits?: number
  /**
   * Zero-based poll attempt index into [`BalancePollPolicy::topup`].
   */
  pollAttempt: number
  /**
   * Which result event the driver is waiting for.
   */
  pending: TopupPending
}

/**
 * What one metered unit costs, and whether that rate is the first of several bands.
 */
export type UsageRate = {
  /**
   * Which quantity the amount is charged against.
   */
  per: ChargePer
  /**
   * Amount in the charge currency's minor units.
   */
  amountMinor: number
  /**
   * ISO currency code as shipped on the wire (not normalised).
   */
  currency: string
  /**
   * Meter name when `per` is `unit`.
   */
  meter?: string
  /**
   * Setup-fee flag; omitted unless `true`.
   */
  oneTime?: boolean
  /**
   * True when `amount_minor` is the entry rate of a multi-band stack.
   */
  tiered: boolean
}

/**
 * Usage snapshot projected from an active purchase (or none).
 */
export type UsageSnapshot = {
  /**
   * Meter name from `checkLimits`; explicit `null` when absent or uncapped.
   */
  meterRef: string | null
  /**
   * `used + remaining` when the meter has a finite cap; else `null`.
   */
  total: number | null
  /**
   * Units used (defaults to `0`).
   */
  used: number
  /**
   * `max(0, total - used)` when `total` is known; else `null`.
   */
  remaining: number | null
  /**
   * 0–100 rounded to 2dp; `null` when `total` is unknown or zero.
   */
  percentUsed: number | null
  /**
   * Billing period start (skip-absent).
   */
  periodStart?: string
  /**
   * Billing period end (skip-absent).
   */
  periodEnd?: string
  /**
   * Purchase reference when an active purchase exists (skip-absent).
   */
  purchaseRef?: string
}

export type BusinessDetails =
  | { isBusiness: false; customerCountry?: SupportedBusinessCountry; customerName?: string }
  | {
      isBusiness: true
      country: SupportedBusinessCountry
      businessName?: string
      taxId?: string
      taxIdType?: TaxIdType
      customerName?: string
    }

export type BusinessDetailsValidationIssue = {
  path: PropertyKey[]
  message: string
}

export type PaymentIntentSource = {
  processorPaymentId: string
  clientSecret: string
  publishableKey: string
  accountId?: string
}

export type PaywallDecisionLimits = {
  withinLimits?: boolean
  remaining?: number
  plan?: string
  checkoutUrl?: string
  confirmationUrl?: string
  activationRequired?: boolean
  plans?: unknown
  balance?: unknown
  product?: unknown
  creditBalance?: number
}

export type PaywallOutcome<TGate = unknown> =
  | { outcome: 'allow' }
  | { outcome: 'gate'; gate: TGate }

export type ProductReadinessInput = {
  status: string
  plans?: Array<{ isActive: boolean }>
}

export type RouteErrorInput = {
  kind: RouteErrorKind
  message: string | null
  status?: number | null
  operationName: string
  defaultMessage?: string | null
}

export type RouteErrorKind = 'solvapay' | 'paywall' | 'error' | 'unknown'

export type TopupProcessOutcome =
  | { status: 'timeout'; message?: string }
  | { status: 'failed' }
  | { status: 'cancelled' }
  | { status: 'succeeded' }

export type ValidateBusinessDetailsResult =
  | { success: true; data: BusinessDetails }
  | { success: false; error: BusinessDetailsValidationError }

export type ActivatePlanValidationError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
}

export type CheckoutHelperError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
}

export type LimitsHelperError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
}

export type PaymentHelperError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
}

export type PlansHelperError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
}

export type ProductHelperError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
}

export type RenewalHelperError = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
  /**
   * Optional detail string; skipped when [`None`].
   */
  details?: string
}

export type RouteErrorResult = {
  /**
   * Human-readable error label (e.g. `"Unauthorized"`).
   */
  error: string
  /**
   * HTTP status code.
   */
  status: number
  /**
   * Optional detail string; skipped when [`None`].
   */
  details?: string
}

export type UsageSnapshotPurchase = {
  reference?: string
  productRef?: string
  planSnapshot?: {
    isMetered?: boolean
    options?: Record<string, unknown>[]
  } | null
  usage?: {
    used?: number
    periodStart?: string
    periodEnd?: string
  } | null
}
